import 'package:flutter/material.dart';

const bg = Color(0xFFF7FAF7);
const green = Color(0xFF2E9E4F);
const gold = Color(0xFFD6AD45);
const text = Color(0xFF172019);
const muted = Color(0xFF667066);
const surface = Colors.white;
const border = Color(0xFFDCE5DC);

void main() => runApp(const FarmPlugApp());
void push(BuildContext context, Widget page) => Navigator.of(context).push(MaterialPageRoute(builder: (_) => page));
void home(BuildContext context) => Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder: (_) => const HomeShell()), (r) => false);

class FarmPlugApp extends StatelessWidget {
  const FarmPlugApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'FarmPlug AI',
    theme: ThemeData(useMaterial3: true, brightness: Brightness.light, scaffoldBackgroundColor: bg, colorScheme: ColorScheme.fromSeed(seedColor: green, brightness: Brightness.light), appBarTheme: const AppBarTheme(backgroundColor: bg, foregroundColor: text, elevation: 0), cardTheme: const CardThemeData(color: surface, elevation: 0), inputDecorationTheme: InputDecorationTheme(filled: true, fillColor: surface, border: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(14)), borderSide: BorderSide(color: border)), enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(14)), borderSide: BorderSide(color: border)), focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.all(Radius.circular(14)), borderSide: BorderSide(color: green, width: 1.5)))),
    home: const SplashPage(),
  );
}

class SplashPage extends StatefulWidget { const SplashPage({super.key}); @override State<SplashPage> createState() => _SplashState(); }
class _SplashState extends State<SplashPage> { @override void initState(){super.initState();Future.delayed(const Duration(milliseconds:500),go);} void go(){if(!mounted)return;Navigator.of(context).pushReplacement(MaterialPageRoute(builder:(_)=>const WelcomePage()));} @override Widget build(BuildContext context)=>const Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.eco,color:green,size:64),SizedBox(height:12),Text('FarmPlug AI',style:TextStyle(color:text,fontSize:30,fontWeight:FontWeight.w800)),SizedBox(height:8),Text('Smart farming. Better decisions. Greater yields.',textAlign:TextAlign.center,style:TextStyle(color:muted)),SizedBox(height:20),CircularProgressIndicator(color:green)]))); }
class Frame extends StatelessWidget { final String title; final String subtitle; final List<Widget> children; const Frame({super.key,required this.title,required this.subtitle,required this.children}); @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),leading:Navigator.canPop(context)?const BackButton():null),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,12,20,28),keyboardDismissBehavior:ScrollViewKeyboardDismissBehavior.onDrag,children:[Text(subtitle,style:const TextStyle(color:muted)),const SizedBox(height:18),...children.map((w)=>Padding(padding:const EdgeInsets.only(bottom:14),child:w))]))); }
Widget primary(String label,VoidCallback onTap)=>SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:onTap,style:FilledButton.styleFrom(backgroundColor:green,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))),child:Text(label,style:const TextStyle(fontWeight:FontWeight.w700))));
Widget outline(String label,VoidCallback onTap)=>SizedBox(width:double.infinity,height:50,child:OutlinedButton(onPressed:onTap,style:OutlinedButton.styleFrom(foregroundColor:green,side:const BorderSide(color:green),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))),child:Text(label,style:const TextStyle(fontWeight:FontWeight.w700))));
Widget input(String label,IconData icon,{TextEditingController? controller,bool obscure=false,TextInputType? type,String? Function(String?)? validator})=>TextFormField(controller:controller,obscureText:obscure,keyboardType:type,validator:validator,decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon)));
Widget cardLink(BuildContext context,String title,String detail,IconData icon,Widget page,{Color color=green})=>Card(child:ListTile(onTap:()=>push(context,page),leading:CircleAvatar(backgroundColor:color.withAlpha(25),foregroundColor:color,child:Icon(icon)),title:Text(title,style:const TextStyle(color:text,fontWeight:FontWeight.w700)),subtitle:Text(detail,style:const TextStyle(color:muted)),trailing:const Icon(Icons.chevron_right,color:muted)));
Widget notice(String title,String detail,{Color color=green})=>Container(width:double.infinity,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:color.withAlpha(20),borderRadius:BorderRadius.circular(14),border:Border.all(color:color.withAlpha(60))),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.info_outline,color:color),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(color:color,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(detail,style:const TextStyle(color:text))]))]));

class WelcomePage extends StatelessWidget { const WelcomePage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Welcome to FarmPlug AI',subtitle:'From Farm Intelligence to the Right Market.',children:[const Icon(Icons.agriculture,color:green,size:76),const Text('One workspace for your farm, AI guidance, produce sales and orders.',style:TextStyle(color:text,fontSize:18)),primary('Get Started',()=>push(context,const SignInPage())),outline('Explore Demo',()=>push(context,const DemoPage()))]); }
class SignInPage extends StatefulWidget { const SignInPage({super.key}); @override State<SignInPage> createState()=>_SignInState(); }
class _SignInState extends State<SignInPage> { final form=GlobalKey<FormState>(); final login=TextEditingController(); final pass=TextEditingController(); @override void dispose(){login.dispose();pass.dispose();super.dispose();} @override Widget build(BuildContext context)=>Frame(title:'Sign In',subtitle:'Use your FarmPlug account.',children:[Form(key:form,child:Column(children:[input('Phone or email',Icons.person,controller:login,validator:(v)=>v==null||v.trim().isEmpty?'Enter phone or email':null),const SizedBox(height:12),input('Password',Icons.lock,controller:pass,obscure:true,validator:(v)=>v==null||v.length<6?'Minimum 6 characters':null)])),TextButton(onPressed:()=>push(context,const ForgotPage()),child:const Text('Forgot password?')),primary('Sign In',(){if(form.currentState!.validate())home(context);}),outline('Continue with Google',()=>push(context,const GooglePage())),TextButton(onPressed:()=>push(context,const SignUpPage()),child:const Text('New to FarmPlug? Sign Up'))]); }
class SignUpPage extends StatefulWidget { const SignUpPage({super.key}); @override State<SignUpPage> createState()=>_SignUpState(); }
class _SignUpState extends State<SignUpPage> { final form=GlobalKey<FormState>(); final name=TextEditingController(); final phone=TextEditingController(); final pass=TextEditingController(); final confirm=TextEditingController(); @override void dispose(){name.dispose();phone.dispose();pass.dispose();confirm.dispose();super.dispose();} @override Widget build(BuildContext context)=>Frame(title:'Create Account',subtitle:'Create your farmer workspace.',children:[Form(key:form,child:Column(children:[input('Full name',Icons.person,controller:name,validator:(v)=>v==null||v.trim().isEmpty?'Enter your name':null),const SizedBox(height:12),input('Phone number',Icons.phone,controller:phone,type:TextInputType.phone,validator:(v)=>v==null||v.trim().length<10?'Enter valid phone':null),const SizedBox(height:12),input('Password',Icons.lock,controller:pass,obscure:true,validator:(v)=>v==null||v.length<6?'Minimum 6 characters':null),const SizedBox(height:12),input('Confirm password',Icons.lock_reset,controller:confirm,obscure:true,validator:(v){if(v==null||v.isEmpty)return'Confirm your password';if(v!=pass.text)return'Passwords do not match';return null;})])),primary('Create Account',(){if(form.currentState!.validate())home(context);})]); }
class GooglePage extends StatelessWidget { const GooglePage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Google Login',subtitle:'Google authentication.',children:[notice('Demo build','Google authentication is not connected in this prototype.'),primary('Continue',()=>push(context,const RolePage()))]); }
class ForgotPage extends StatefulWidget { const ForgotPage({super.key}); @override State<ForgotPage> createState()=>_ForgotState(); }
class _ForgotState extends State<ForgotPage> { final email=TextEditingController(); bool sent=false; @override void dispose(){email.dispose();super.dispose();} @override Widget build(BuildContext context)=>Frame(title:'Forgot Password',subtitle:'Request a reset.',children:[input('Phone or email',Icons.person,controller:email),primary(sent?'Request Sent':'Send Reset Request',()=>setState(()=>sent=true)),if(sent)notice('Request created','Check your registered contact.')]); }
class RolePage extends StatelessWidget { const RolePage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Choose Your Role',subtitle:'Select how you use FarmPlug.',children:[cardLink(context,'Farmer','Manage farms, crops and sales',Icons.agriculture,const HomeShell()),cardLink(context,'Buyer','Source verified produce',Icons.storefront,const MarketplacePage()),cardLink(context,'FPO','Aggregate farmers and supply',Icons.groups,const AggregationPage())]); }
class DemoPage extends StatelessWidget { const DemoPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Demo Mode',subtitle:'Seeded simulated workflow.',children:[notice('DEMO MODE','Data is simulated and never changes production records.',color:gold),cardLink(context,'Farmer Demo','Farm, AI and sales workspace',Icons.agriculture,const HomeShell()),cardLink(context,'Buyer Demo','Marketplace and requirements',Icons.storefront,const MarketplacePage()),cardLink(context,'FPO Demo','Aggregation and collection',Icons.groups,const AggregationPage())]); }
class HomeShell extends StatefulWidget { const HomeShell({super.key}); @override State<HomeShell> createState()=>_ShellState(); }
class _ShellState extends State<HomeShell> { int tab=0; final pages=const[HomePage(),AiPage(),FarmPage(),OrdersPage(),ProfilePage()]; @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(backgroundColor:surface,selectedIndex:tab,indicatorColor:Color(0x232E9E4F),onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.auto_awesome_outlined),selectedIcon:Icon(Icons.auto_awesome),label:'AI Center'),NavigationDestination(icon:Icon(Icons.agriculture_outlined),selectedIcon:Icon(Icons.agriculture),label:'My Farm'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),selectedIcon:Icon(Icons.receipt_long),label:'Orders'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile')])); }
class HomePage extends StatelessWidget { const HomePage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'FarmPlug AI',subtitle:'Your farm at a glance.',children:[notice('Farm health','Healthy · 3 farms · 6 crops'),cardLink(context,'AI Center','Crop, irrigation and market guidance',Icons.auto_awesome,const AiPage()),cardLink(context,'Marketplace','Buyer opportunities',Icons.storefront,const MarketplacePage()),cardLink(context,'Notifications','Orders, prices and weather',Icons.notifications,const NotificationsPage())]); }
class AiPage extends StatefulWidget { const AiPage({super.key}); @override State<AiPage> createState()=>_AiState(); }
class _AiState extends State<AiPage> { final q=TextEditingController(); String answer='Ask about crops, irrigation, pests, demand or selling windows.'; @override void dispose(){q.dispose();super.dispose();} void ask(){final s=q.text.toLowerCase();setState(()=>answer=s.contains('water')?'Check soil moisture before irrigation and avoid watering during heavy rainfall.':s.contains('market')||s.contains('price')?'Use verified market data before selling. Demo values are clearly marked.':'FarmPlug AI can guide crop health, demand, selling windows and buyer matching.');} @override Widget build(BuildContext context)=>Frame(title:'AI Center',subtitle:'Farmer-first decision support.',children:[input('Ask FarmPlug AI',Icons.auto_awesome,controller:q),primary('Ask AI',ask),notice('AI guidance',answer)]); }
class FarmPage extends StatelessWidget { const FarmPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'My Farm',subtitle:'Farm and crop overview.',children:[notice('Farm status','3 farms · 6 active crops'),cardLink(context,'Crops','Tomato · Banana · Coconut',Icons.grass,const CropsPage()),cardLink(context,'Crop Health','Review observations',Icons.health_and_safety,const CropHealthPage()),cardLink(context,'Add Produce','Create a marketplace listing',Icons.add_box,const AddProducePage())]); }
class OrdersPage extends StatelessWidget { const OrdersPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Orders',subtitle:'Track sales and deliveries.',children:[notice('ORD1234','5,000 kg Grade A Tomato · DEMO ORDER',color:gold),cardLink(context,'Order Details','Collection → Pickup → Transit → Delivery',Icons.local_shipping,const OrderDetailsPage()),cardLink(context,'Completed','ORD1232 · Delivered',Icons.check_circle,const OrderDetailsPage())]); }
class ProfilePage extends StatelessWidget { const ProfilePage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Profile',subtitle:'Account and settings.',children:[notice('Gokul S','Farmer · FarmPlug AI'),cardLink(context,'Settings','Preferences and security',Icons.settings,const SettingsPage()),cardLink(context,'Notifications','View alerts',Icons.notifications,const NotificationsPage()),cardLink(context,'Help & Support','Get assistance',Icons.help_outline,const HelpPage()),outline('Sign Out',()=>Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder:(_)=>const WelcomePage()),(r)=>false))]); }
class MarketplacePage extends StatelessWidget { const MarketplacePage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Marketplace',subtitle:'DEMO DATA · Simulated listings.',children:[cardLink(context,'Grade A Tomato','1,200 kg · DEMO FARMER',Icons.eco,const ListingPage()),cardLink(context,'Grade A Tomato','1,800 kg · DEMO FARMER',Icons.eco,const ListingPage()),cardLink(context,'Grade A Tomato','2,000 kg · DEMO FARMER',Icons.eco,const ListingPage())]); }
class ListingPage extends StatelessWidget { const ListingPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Produce Details',subtitle:'DEMO DATA',children:[notice('5,000 kg Grade A Tomato','Combined supply from three demo farmers.'),primary('Request Quote',()=>push(context,const OrderDetailsPage()))]); }
class AggregationPage extends StatelessWidget { const AggregationPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Aggregation',subtitle:'Bulk supply coordination.',children:[notice('5,000 kg matched','1,200 + 1,800 + 2,000 kg Grade A tomato',color:gold),cardLink(context,'Collection Center','Plan collection and pickup',Icons.warehouse,const LogisticsPage()),cardLink(context,'Logistics','Estimated route and cost',Icons.route,const LogisticsPage())]); }
class LogisticsPage extends StatelessWidget { const LogisticsPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Logistics',subtitle:'Estimated logistics information.',children:[notice('Estimated route','Collection → Buyer · ESTIMATED LOGISTICS COST'),primary('View Delivery Timeline',()=>push(context,const OrderDetailsPage()))]); }
class OrderDetailsPage extends StatelessWidget { const OrderDetailsPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Order ORD1234',subtitle:'DEMO ORDER · PAYMENT SIMULATION',children:[notice('5,000 kg Grade A Tomato','Matched and aggregated.'),Stepper(currentStep:3,physics:const NeverScrollableScrollPhysics(),steps:const[Step(title:Text('Collection'),content:Text('Collection planned.')),Step(title:Text('Pickup'),content:Text('Pickup scheduled.')),Step(title:Text('Transit'),content:Text('In transit.')),Step(title:Text('Delivery'),content:Text('Delivery planned.')),Step(title:Text('Completed'),content:Text('Pending completion.'))])]); }
class NotificationsPage extends StatelessWidget { const NotificationsPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Notifications',subtitle:'Your latest alerts.',children:[cardLink(context,'New Order Received','ORD1234 · 10:30 AM',Icons.receipt_long,const OrderDetailsPage()),cardLink(context,'Price Alert','Tomato price changed · 9:15 AM',Icons.trending_up,const MarketplacePage()),cardLink(context,'Weather Alert','Rain expected tomorrow · 8:00 AM',Icons.cloud,const AiPage()),cardLink(context,'Pest Alert','Watch for tomato leaf curl',Icons.bug_report,const CropHealthPage())]); }
class SettingsPage extends StatelessWidget { const SettingsPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Settings',subtitle:'Preferences and account security.',children:[cardLink(context,'Language','English',Icons.language,const LanguagePage()),cardLink(context,'Security','Password and privacy',Icons.security,const SecurityPage()),cardLink(context,'Help','Support and guidance',Icons.help_outline,const HelpPage())]); }
class LanguagePage extends StatelessWidget { const LanguagePage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Language',subtitle:'Choose app language.',children:[notice('English','Currently selected'),outline('Tamil',(){}),outline('Hindi',(){})]); }
class SecurityPage extends StatelessWidget { const SecurityPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Security',subtitle:'Account protection.',children:[notice('Secure session','Demo build does not store passwords locally.'),cardLink(context,'Change Password','Update password',Icons.lock,const HelpPage())]); }
class HelpPage extends StatelessWidget { const HelpPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Help & Support',subtitle:'FarmPlug assistance.',children:[notice('Need help?','Use the support channel configured for your FarmPlug account.'),primary('Contact Support',(){})]); }
class CropsPage extends StatelessWidget { const CropsPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Crops',subtitle:'Active crops.',children:[cardLink(context,'Tomato','Grade A · 2 acres',Icons.grass,const CropHealthPage()),cardLink(context,'Banana','1.5 acres',Icons.grass,const CropHealthPage()),cardLink(context,'Coconut','2 acres',Icons.grass,const CropHealthPage())]); }
class CropHealthPage extends StatelessWidget { const CropHealthPage({super.key}); @override Widget build(BuildContext context)=>Frame(title:'Crop Health',subtitle:'Observation and AI guidance.',children:[notice('Tomato health','Monitor leaves, moisture and pest symptoms.'),primary('Ask AI About This Crop',()=>push(context,const AiPage()))]); }
class AddProducePage extends StatefulWidget { const AddProducePage({super.key}); @override State<AddProducePage> createState()=>_AddProduceState(); }
class _AddProduceState extends State<AddProducePage> { final crop=TextEditingController(); final quantity=TextEditingController(); @override void dispose(){crop.dispose();quantity.dispose();super.dispose();} @override Widget build(BuildContext context)=>Frame(title:'Add Produce',subtitle:'Create a marketplace listing.',children:[input('Crop',Icons.eco,controller:crop),input('Quantity (kg)',Icons.scale,controller:quantity,type:TextInputType.number),primary('Publish Listing',(){if(crop.text.trim().isEmpty||quantity.text.trim().isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter crop and quantity.')));return;}ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Listing saved in demo mode.')));})]); }
