import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
const bg=Color(0xFFF7FAF7),surface=Colors.white,surface2=Color(0xFFF0F5F0),green=Color(0xFF2E9E4F),greenDark=Color(0xFF1E7A3D),gold=Color(0xFFD6AD45),text=Color(0xFF172019),muted=Color(0xFF667066),warning=Color(0xFFD58A00),danger=Color(0xFFC83C3C);const site='https://farmplugaisxd.vercel.app';
void main()=>runApp(const FarmPlug());
class FarmPlug extends StatelessWidget{const FarmPlug({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'FarmPlug AI',theme:ThemeData(useMaterial3:true,brightness:Brightness.light,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:green,brightness:Brightness.light),cardTheme:const CardThemeData(color:surface,elevation:0,margin:EdgeInsets.zero),inputDecorationTheme:InputDecorationTheme(filled:true,fillColor:surface,border:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(14)),borderSide:BorderSide(color:Color(0xFFDCE5DC))),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(14)),borderSide:BorderSide(color:Color(0xFFDCE5DC))),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(14)),borderSide:BorderSide(color:green,width:1.5)))),home:const Splash());}
Future<void> openSite(BuildContext c,String path)async{final ok=await launchUrl(Uri.parse('$site$path'),mode:LaunchMode.externalApplication);if(!ok&&c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Unable to open FarmPlug')));}void push(BuildContext c,Widget p)=>Navigator.push(c,MaterialPageRoute(builder:(_)=>p));void pop(BuildContext c)=>Navigator.pop(c);
class Splash extends StatefulWidget{const Splash({super.key});@override State<Splash> createState()=>_SplashState();}class _SplashState extends State<Splash>{@override void initState(){super.initState();Future.delayed(const Duration(milliseconds:700),(){if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const Welcome()));});}@override Widget build(BuildContext c)=>const Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.eco_rounded,color:green,size:68),SizedBox(height:16),Text('FarmPlug AI',style:TextStyle(color:text,fontSize:30,fontWeight:FontWeight.w800)),SizedBox(height:7),Text('Smart farming. Better decisions. Greater yields.',textAlign:TextAlign.center,style:TextStyle(color:muted)),SizedBox(height:24),CircularProgressIndicator(color:green,strokeWidth:2)])));}
class Welcome extends StatelessWidget{const Welcome({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Welcome to FarmPlug AI',subtitle:'From Farm Intelligence to the Right Market.',children:[const Icon(Icons.agriculture_rounded,color:green,size:80),const SizedBox(height:20),const Text('One simple workspace for your farm, AI guidance, produce sales and orders.',style:TextStyle(color:text,fontSize:18,height:1.4)),Btn('Get Started',()=>push(c,const Onboarding())),BtnOutline('Explore Demo',()=>push(c,const DemoRole()))]);}
class Onboarding extends StatelessWidget{const Onboarding({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Onboarding',subtitle:'A few details help FarmPlug give better recommendations.',children:[field('Your name',Icons.person_outline),field('Phone number',Icons.phone_outlined),field('Main crop',Icons.spa_outlined),Btn('Continue',()=>push(c,const FarmSetup()))]);}
class FarmSetup extends StatelessWidget{const FarmSetup({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Farm Setup',subtitle:'Add your first farm to start tracking crops.',children:[field('Farm name',Icons.agriculture_outlined),field('Location',Icons.location_on_outlined),field('Area in acres',Icons.square_foot_outlined),Btn('Save Farm',()=>push(c,const SignIn()))]);}
class SignIn extends StatelessWidget{const SignIn({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Sign In',subtitle:'Manage your FarmPlug workspace.',children:[field('Phone or email',Icons.person_outline),field('Password',Icons.lock_outline,true),Align(alignment:Alignment.centerRight,child:TextButton(onPressed:()=>openSite(c,'/forgot-password'),child:const Text('Forgot password?'))),Btn('Sign In',()=>push(c,const RoleSelection())),BtnOutline('Google Login',()=>push(c,const GoogleLogin())),TextButton(onPressed:()=>push(c,const SignUp()),child:const Text('New to FarmPlug? Sign Up'))]);}
class SignUp extends StatelessWidget{const SignUp({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Sign Up',subtitle:'Start your digital farm workspace.',children:[field('Full name',Icons.person_outline),field('Phone number',Icons.phone_outlined),field('Password',Icons.lock_outline,true),field('Confirm password',Icons.lock_reset_outlined,true),const Text('By continuing you agree to the Terms and Privacy Policy.',style:TextStyle(color:muted,fontSize:12)),Btn('Create Account',()=>push(c,const RoleSelection()))]);}
class GoogleLogin extends StatelessWidget{const GoogleLogin({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Google Login',subtitle:'Continue securely with your Google account.',children:[const Icon(Icons.account_circle,color:green,size:72),Btn('Continue with Google',()=>push(c,const RoleSelection()))]);}
class RoleSelection extends StatelessWidget{const RoleSelection({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Choose Your Role',subtitle:'Select how you use FarmPlug.',children:[ChoiceCard('Farmer','Manage farms, crops and sales',Icons.agriculture,()=>push(c,const ProfileCompletion())),ChoiceCard('Buyer','Source verified produce',Icons.storefront,()=>push(c,const ProfileCompletion())),ChoiceCard('FPO','Aggregate farmers and supply',Icons.groups,()=>push(c,const ProfileCompletion()))]);}
class ProfileCompletion extends StatelessWidget{const ProfileCompletion({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Profile Completion',subtitle:'Keep your details ready for matching and payments.',children:[field('Display name',Icons.badge_outlined),field('Village / city',Icons.location_city_outlined),field('Preferred language',Icons.language),Btn('Finish Setup',()=>push(c,const HomeShell()))]);}
class HomeShell extends StatefulWidget{const HomeShell({super.key});@override State<HomeShell> createState()=>_HomeShellState();}class _HomeShellState extends State<HomeShell>{int tab=0;final pages=const[FarmerHome(),AiCenter(),MyFarm(),Orders(),Profile()];@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(backgroundColor:surface,selectedIndex:tab,indicatorColor:green.withValues(alpha:.14),onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.auto_awesome_outlined),selectedIcon:Icon(Icons.auto_awesome),label:'AI Center'),NavigationDestination(icon:Icon(Icons.agriculture_outlined),selectedIcon:Icon(Icons.agriculture),label:'My Farm'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),selectedIcon:Icon(Icons.receipt_long),label:'Orders'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile')]));}
class FarmerHome extends StatelessWidget{const FarmerHome({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Good morning, farmer',subtitle:'Smart farming. Better decisions. Greater yields.',children:[CardBox(icon:Icons.wb_sunny_outlined,title:'28°C · Partly cloudy',body:'Coimbatore · Good conditions for field work',accent:green),const Section('Farm Overview'),Row(children:[Expanded(child:Stat('3','Farms')),const SizedBox(width:8),Expanded(child:Stat('6','Crops'))]),Row(children:[Expanded(child:Stat('2','Orders')),const SizedBox(width:8),Expanded(child:Stat('1','Alert',accent:warning))]),const Section('Today’s Tasks'),ActionTile('Irrigation check','Tomato plot · due today',Icons.water_drop,green,()=>push(c,const CropDetails())),ActionTile('Review market price','Tomato · local market',Icons.trending_up,gold,()=>push(c,const Marketplace())),ActionTile('Crop health review','One crop needs attention',Icons.health_and_safety,warning,()=>push(c,const CropHealth()))]);}
class AiCenter extends StatelessWidget{const AiCenter({super.key});@override Widget build(BuildContext c)=>AppPage(title:'AI Center',subtitle:'Practical guidance based on your farm.',children:[CardBox(icon:Icons.auto_awesome,title:'FarmPlug Intelligence',body:'Ask a question or choose a quick action.',accent:green),ActionTile('Disease diagnosis','Check crop symptoms',Icons.bug_report,green,()=>push(c,const CropHealth())),ActionTile('Fertilizer recommendation','Plan crop nutrition',Icons.eco,gold,()=>push(c,const FarmIntelligence())),ActionTile('Market prices','See price signals',Icons.trending_up,green,()=>push(c,const Marketplace())),ActionTile('Weather','Plan field work',Icons.cloud_outlined,warning,()=>push(c,const FarmIntelligence())),field('Ask FarmPlug AI…',Icons.chat_bubble_outline)]);}
class MyFarm extends StatelessWidget{const MyFarm({super.key});@override Widget build(BuildContext c)=>AppPage(title:'My Farm',subtitle:'Manage plots, crops and farm health.',children:[Align(alignment:Alignment.centerRight,child:BtnSmall('Add Farm',()=>push(c,const FarmSetup()))),FarmCard('North Field','2.5 acres','Coimbatore','Healthy',green,()=>push(c,const Crops())),FarmCard('Greenhouse Plot','1.2 acres','Coimbatore','Needs Attention',warning,()=>push(c,const Crops())),const Section('Crops'),CropTile('Tomato','1.4 acres · 42 days to harvest','Healthy',green,()=>push(c,const CropDetails())),CropTile('Chilli','0.8 acres · 58 days to harvest','Healthy',green,()=>push(c,const CropDetails()))]);}
class Crops extends StatelessWidget{const Crops({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Crops',subtitle:'All crops across your farms.',children:[CropTile('Tomato','North Field · 1.4 acres','Healthy',green,()=>push(c,const CropDetails())),CropTile('Chilli','North Field · 0.8 acres','Healthy',green,()=>push(c,const CropDetails())),Btn('Add Crop',()=>push(c,const CropDetails()))]);}
class CropDetails extends StatelessWidget{const CropDetails({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Crop Details',subtitle:'Tomato · North Field · 1.4 acres',children:[CardBox(icon:Icons.spa,title:'Crop Health',body:'Healthy · 42 days to harvest',accent:green),Info('Sowing date','20 Jul 2026'),Info('Irrigation','Next check today'),Info('Area','1.4 acres'),Btn('Open Crop Health',()=>push(c,const CropHealth())),BtnOutline('Farm Intelligence',()=>push(c,const FarmIntelligence()))]);}
class CropHealth extends StatelessWidget{const CropHealth({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Crop Health',subtitle:'Monitor symptoms and recommended actions.',children:[StatusBox('Healthy','No critical issue detected.',green),Info('Latest check','Today'),Info('Risk','Low'),Info('Action','Continue planned irrigation'),Btn('Get AI Diagnosis',()=>push(c,const AiDecision()))]);}
class FarmIntelligence extends StatelessWidget{const FarmIntelligence({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Farm Intelligence',subtitle:'Signals that can improve your next farm decision.',children:[Info('Weather','28°C · Partly cloudy'),Info('Water','Irrigation check due'),Info('Market','Tomato price signal positive'),Info('Crop','Tomato healthy'),Btn('Open AI Decision Center',()=>push(c,const AiDecision()))]);}
class AiDecision extends StatelessWidget{const AiDecision({super.key});@override Widget build(BuildContext c)=>AppPage(title:'AI Decision Center',subtitle:'Recommended next actions.',children:[CardBox(icon:Icons.auto_awesome,title:'Recommendation',body:'Check tomato irrigation today and review local tomato prices before listing.',accent:green),Btn('Open Market',()=>push(c,const Marketplace())),BtnOutline('FarmPlug Intelligence',()=>push(c,const FarmIntelligence()))]);}
class FarmPlugIntelligence extends StatelessWidget{const FarmPlugIntelligence({super.key});@override Widget build(BuildContext c)=>generic(c,'FarmPlug Intelligence','AI-powered farm signals and recommendations.',Icons.auto_awesome);}
class Market extends StatelessWidget{const Market({super.key});@override Widget build(BuildContext c)=>const Marketplace();}
class Marketplace extends StatelessWidget{const Marketplace({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Marketplace',subtitle:'Find demand and compare produce prices.',children:[field('Search produce',Icons.search),Wrap(spacing:8,runSpacing:8,children:['All','Vegetables','Fruits','Grains','Spices'].map((x)=>Chip(label:Text(x))).toList()),Product('Tomato','₹42/kg','Fresh · verified supply',()=>push(c,const ListingDetails())),Product('Chilli','₹86/kg','Fresh · verified supply',()=>push(c,const ListingDetails())),Btn('List My Produce',()=>push(c,const AddProduce()))]);}
class BuyerDetails extends StatelessWidget{const BuyerDetails({super.key});@override Widget build(BuildContext c)=>generic(c,'Buyer Details','Fresh Foods Pvt Ltd · Verified buyer',Icons.business);}
class AddProduce extends StatelessWidget{const AddProduce({super.key});@override Widget build(BuildContext c)=>AppPage(title:'List Produce',subtitle:'Create a clear listing buyers can trust.',children:[field('Produce type',Icons.spa_outlined),field('Quantity (kg)',Icons.scale_outlined),field('Price per kg',Icons.currency_rupee),field('Photo',Icons.photo_camera_outlined),Btn('Publish Listing',()=>push(c,const MyListings()))]);}
class MyListings extends StatelessWidget{const MyListings({super.key});@override Widget build(BuildContext c)=>AppPage(title:'My Listings',subtitle:'Manage your active produce listings.',children:[Product('Tomato','₹42/kg','500 kg · Active',()=>push(c,const ListingDetails())),Product('Chilli','₹86/kg','250 kg · Active',()=>push(c,const ListingDetails())),Btn('Add Another Listing',()=>push(c,const AddProduce()))]);}
class ListingDetails extends StatelessWidget{const ListingDetails({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Listing Details',subtitle:'Tomato · Fresh produce',children:[Info('Quantity','500 kg'),Info('Price','₹42/kg'),Info('Location','Coimbatore'),StatusBox('Active','Visible to matched buyers.',green),Btn('View Buyer Matches',()=>push(c,const BuyerMatches()))]);}
class BuyerMatches extends StatelessWidget{const BuyerMatches({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Buyer Matches',subtitle:'Buyers whose requirements match your listing.',children:[MatchCard('Fresh Foods Pvt Ltd','300 kg · ₹42/kg',()=>push(c,const BuyerDetails())),MatchCard('Coimbatore Retail Hub','200 kg · ₹41/kg',()=>push(c,const BuyerDetails())),Btn('View Offers',()=>push(c,const Offers()))]);}
class Offers extends StatelessWidget{const Offers({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Offers',subtitle:'Review offers from matched buyers.',children:[OfferCard('#OF-204','Fresh Foods Pvt Ltd','500 kg · ₹42/kg',()=>push(c,const OfferDetails())),OfferCard('#OF-199','Retail Hub','200 kg · ₹41/kg',()=>push(c,const OfferDetails()))]);}
class OfferDetails extends StatelessWidget{const OfferDetails({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Offer Details',subtitle:'#OF-204 · Fresh Foods Pvt Ltd',children:[Info('Quantity','500 kg'),Info('Rate','₹42/kg'),Info('Payment','Bank transfer'),Btn('Accept Offer',()=>push(c,const AcceptOffer())),BtnOutline('Decline',()=>pop(c))]);}
class AcceptOffer extends StatelessWidget{const AcceptOffer({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Accept Offer',subtitle:'Confirm the sale details before accepting.',children:[StatusBox('Ready to confirm','500 kg Tomato · ₹21,000',green),Btn('Confirm Offer',()=>push(c,const Orders())),BtnOutline('Cancel',()=>pop(c))]);}
class Orders extends StatelessWidget{const Orders({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Orders',subtitle:'Track sales from confirmation to delivery.',children:[Wrap(spacing:8,children:['All','Pending','Confirmed','Completed'].map((x)=>ChoiceChip(label:Text(x),selected:x=='All',onSelected:(_){ })).toList()),OrderCard('#FP-1042','Tomato · 500 kg','Confirmed',green,()=>push(c,const OrderDetails())),OrderCard('#FP-1038','Chilli · 250 kg','Pending',warning,()=>push(c,const OrderDetails()))]);}
class OrderDetails extends StatelessWidget{const OrderDetails({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Order Details',subtitle:'#FP-1042 · Today',children:[Info('Buyer','Fresh Foods Pvt Ltd'),Info('Item','Tomato · 500 kg'),Info('Payment','₹21,000 · Bank transfer'),StatusBox('Confirmed','Ready for collection.',green),Btn('Track Order',()=>push(c,const OrderTracking())),BtnOutline('View Notifications',()=>push(c,const Notifications()))]);}
class OrderTracking extends StatelessWidget{const OrderTracking({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Order Tracking',subtitle:'#FP-1042',children:[StepItem('Order confirmed',true),StepItem('Collection scheduled',true),StepItem('In transit',false),StepItem('Delivered',false),Btn('Done',()=>pop(c))]);}
class Aggregation extends StatelessWidget{const Aggregation({super.key});@override Widget build(BuildContext c)=>generic(c,'Aggregation','Combine farmer supply into buyer-ready lots.',Icons.inventory_2);}
class AggregationDetails extends StatelessWidget{const AggregationDetails({super.key});@override Widget build(BuildContext c)=>generic(c,'Aggregation Details','Lot #AG-120 · 2,500 kg Tomato',Icons.inventory);}
class CollectionCenter extends StatelessWidget{const CollectionCenter({super.key});@override Widget build(BuildContext c)=>generic(c,'Collection Center','Schedule produce collection and quality checks.',Icons.warehouse);}
class Logistics extends StatelessWidget{const Logistics({super.key});@override Widget build(BuildContext c)=>generic(c,'Logistics','Coordinate pickup, transit and delivery.',Icons.local_shipping);}
class DeliveryDetails extends StatelessWidget{const DeliveryDetails({super.key});@override Widget build(BuildContext c)=>generic(c,'Delivery Details','Track destination, driver and delivery status.',Icons.location_on);}
class Notifications extends StatelessWidget{const Notifications({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Notifications',subtitle:'Important updates from FarmPlug.',children:[Notice('New order confirmed','Tomato · 500 kg',Icons.shopping_bag,green),Notice('Market price update','Tomato price changed today',Icons.trending_up,gold),Notice('Weather alert','Plan irrigation around rain',Icons.cloud_outlined,warning),Notice('Produce delivered','Previous order completed',Icons.check_circle,green)]);}
class Profile extends StatelessWidget{const Profile({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Profile',subtitle:'Account, farms and preferences.',children:[CardBox(icon:Icons.person,title:'Farm owner',body:'Coimbatore, Tamil Nadu',accent:green),Menu('My Farms',Icons.agriculture,()=>push(c,const MyFarm())),Menu('Bank Details',Icons.account_balance,()=>push(c,const Generic(title:'Bank Details',subtitle:'Secure payment account information.',icon:Icons.account_balance))),Menu('Address',Icons.location_on,()=>push(c,const Generic(title:'Address',subtitle:'Manage farm and delivery addresses.',icon:Icons.location_on))),Menu('Payment History',Icons.payments,()=>push(c,const Generic(title:'Payment History',subtitle:'Review completed payments.',icon:Icons.payments))),Menu('Help & Support',Icons.help_outline,()=>openSite(c,'/contact')),Menu('Settings',Icons.settings_outlined,()=>push(c,const SettingsPage())),Menu('Notifications',Icons.notifications_none,()=>push(c,const Notifications()))]);}
class SettingsPage extends StatelessWidget{const SettingsPage({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Settings',subtitle:'Control your FarmPlug preferences.',children:[Menu('Language',Icons.language,()=>push(c,const LanguagePage())),Menu('Units',Icons.straighten,()=>push(c,const UnitsPage())),Menu('Security',Icons.security,()=>push(c,const SecurityPage())),Menu('Change Password',Icons.lock_reset,()=>push(c,const ChangePasswordPage())),Menu('Privacy',Icons.privacy_tip_outlined,()=>openSite(c,'/privacy')),Menu('Terms',Icons.description_outlined,()=>openSite(c,'/terms')),Menu('Download Farmer App',Icons.android,()=>push(c,const DownloadApp())),Menu('Logout',Icons.logout,()=>push(c,const LogoutConfirm()))]);}
class LanguagePage extends StatelessWidget{const LanguagePage({super.key});@override Widget build(BuildContext c)=>generic(c,'Language','English · Tamil and more languages can be added.',Icons.language);}
class UnitsPage extends StatelessWidget{const UnitsPage({super.key});@override Widget build(BuildContext c)=>generic(c,'Units','Acres · kilograms · Indian Rupees.',Icons.straighten);}
class SecurityPage extends StatelessWidget{const SecurityPage({super.key});@override Widget build(BuildContext c)=>generic(c,'Security','Manage account security and sign-in protection.',Icons.security);}
class ChangePasswordPage extends StatelessWidget{const ChangePasswordPage({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Change Password',subtitle:'Update your account password securely.',children:[field('Current password',Icons.lock_outline,true),field('New password',Icons.lock_reset,true),field('Confirm password',Icons.lock_reset,true),Btn('Update Password',()=>pop(c))]);}
class LogoutConfirm extends StatelessWidget{const LogoutConfirm({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Log out?',subtitle:'You can sign in again anytime.',children:[Btn('Log out',()=>push(c,const Welcome())),BtnOutline('Cancel',()=>pop(c))]);}
class DemoRole extends StatelessWidget{const DemoRole({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Demo Role Selection',subtitle:'Explore FarmPlug without an account.',children:[ChoiceCard('Farmer Demo','Explore the farmer workspace',Icons.agriculture,()=>push(c,const DemoWorkspace())),ChoiceCard('Buyer Demo','Explore sourcing workflows',Icons.storefront,()=>push(c,const DemoWorkspace())),ChoiceCard('FPO Demo','Explore aggregation workflows',Icons.groups,()=>push(c,const DemoWorkspace()))]);}
class DemoWorkspace extends StatelessWidget{const DemoWorkspace({super.key});@override Widget build(BuildContext c)=>AppPage(title:'Demo Workspace',subtitle:'Sample data only · no real transactions.',children:[CardBox(icon:Icons.auto_awesome,title:'FarmPlug Demo',body:'Try AI, farm management, marketplace and order flows.',accent:green),Btn('Open Farmer Home',()=>push(c,const HomeShell()))]);}
class ErrorPage extends StatelessWidget{const ErrorPage({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Something went wrong',subtitle:'We could not load this screen.',children:[const Icon(Icons.error_outline,color:danger,size:64),Btn('Try Again',()=>pop(c))]);}
class OfflinePage extends StatelessWidget{const OfflinePage({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'You’re offline',subtitle:'Some FarmPlug features need an internet connection.',children:[const Icon(Icons.cloud_off,color:warning,size:64),Btn('Retry',()=>pop(c))]);}
class EmptyState extends StatelessWidget{const EmptyState({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Nothing here yet',subtitle:'Your new FarmPlug workspace will appear here.',children:[const Icon(Icons.inbox_outlined,color:muted,size:64),Btn('Go Home',()=>push(c,const HomeShell()))]);}
class DownloadApp extends StatelessWidget{const DownloadApp({super.key});@override Widget build(BuildContext c)=>PageFrame(title:'Download Farmer App',subtitle:'Install the latest FarmPlug Android app.',children:[const Icon(Icons.android,color:green,size:76),const Info('Version','2.0.0'),const Info('Package','com.farmplug.farmer'),const Info('Security','Release APK verified by build workflow'),Btn('Open FarmPlug Download',()=>openSite(c,'/download-app'))]);}
class Generic extends StatelessWidget{final String title,subtitle;final IconData icon;const Generic({super.key,required this.title,required this.subtitle,required this.icon});@override Widget build(BuildContext c)=>PageFrame(title:title,subtitle:subtitle,children:[Icon(icon,color:green,size:64),Btn('Continue',()=>pop(c))]);}
Widget generic(BuildContext c,String title,String subtitle,IconData icon)=>PageFrame(title:title,subtitle:subtitle,children:[Icon(icon,color:green,size:64),const Info('Status','Ready'),Btn('Continue',()=>pop(c))]);
class PageFrame extends StatelessWidget{final String title,subtitle;final List<Widget>children;const PageFrame({super.key,required this.title,required this.subtitle,required this.children});@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(22,34,22,28),children:[const Icon(Icons.eco_rounded,color:green,size:38),const SizedBox(height:22),Text(title,style:const TextStyle(color:text,fontSize:28,fontWeight:FontWeight.w800)),const SizedBox(height:7),Text(subtitle,style:const TextStyle(color:muted,height:1.45)),const SizedBox(height:22),...children.map((w)=>Padding(padding:const EdgeInsets.only(bottom:12),child:w))])));}
class AppPage extends StatelessWidget{final String title,subtitle;final List<Widget>children;const AppPage({super.key,required this.title,required this.subtitle,required this.children});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.fromLTRB(18,18,18,24),children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:text,fontSize:27,fontWeight:FontWeight.w800)),const SizedBox(height:5),Text(subtitle,style:const TextStyle(color:muted,height:1.4))])),IconButton(onPressed:()=>push(c,const Notifications()),icon:const Icon(Icons.notifications_none,color:muted))]),const SizedBox(height:18),...children.map((w)=>Padding(padding:const EdgeInsets.only(bottom:10),child:w))]);}
class CardBox extends StatelessWidget{final IconData icon;final String title,body;final Color accent;const CardBox({super.key,required this.icon,required this.title,required this.body,required this.accent});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:accent,borderRadius:BorderRadius.circular(16)),child:Row(children:[Icon(icon,color:Colors.white,size:40),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:4),Text(body,style:const TextStyle(color:Colors.white))]))]));}
class Stat extends StatelessWidget{final String value,label;final Color accent;const Stat(this.value,this.label,{super.key,this.accent=green});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:surface,borderRadius:BorderRadius.circular(14),border:Border.all(color:const Color(0xFFDCE5DC))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.insights,color:accent),const SizedBox(height:12),Text(value,style:const TextStyle(color:text,fontSize:23,fontWeight:FontWeight.w800)),Text(label,style:const TextStyle(color:muted))]));}
class Section extends StatelessWidget{final String title;const Section(this.title,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(top:8,bottom:2),child:Text(title,style:const TextStyle(color:text,fontSize:18,fontWeight:FontWeight.w800)));}
class ActionTile extends StatelessWidget{final String title,body;final IconData icon;final Color color;final VoidCallback onTap;const ActionTile(this.title,this.body,this.icon,this.color,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:onTap,leading:CircleAvatar(backgroundColor:color.withValues(alpha:.12),child:Icon(icon,color:color)),title:Text(title,style:const TextStyle(color:text,fontWeight:FontWeight.w700)),subtitle:Text(body,style:const TextStyle(color:muted)),trailing:const Icon(Icons.chevron_right,color:muted)));}
class FarmCard extends StatelessWidget{final String name,area,loc,status;final Color color;final VoidCallback onTap;const FarmCard(this.name,this.area,this.loc,this.status,this.color,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:onTap,leading:const Icon(Icons.landscape,color:green),title:Text(name,style:const TextStyle(color:text,fontWeight:FontWeight.w800)),subtitle:Text('$area · $loc',style:const TextStyle(color:muted)),trailing:Status(status,color)));}
class CropTile extends StatelessWidget{final String name,detail,health;final Color color;final VoidCallback onTap;const CropTile(this.name,this.detail,this.health,this.color,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:onTap,leading:const Icon(Icons.spa,color:green),title:Text(name,style:const TextStyle(color:text,fontWeight:FontWeight.w800)),subtitle:Text(detail,style:const TextStyle(color:muted)),trailing:Status(health,color)));}
class OrderCard extends StatelessWidget{final String id,item,status;final Color color;final VoidCallback onTap;const OrderCard(this.id,this.item,this.status,this.color,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:onTap,title:Text(item,style:const TextStyle(color:text,fontWeight:FontWeight.w800)),subtitle:Text(id,style:const TextStyle(color:muted)),trailing:Status(status,color)));}
class Product extends StatelessWidget{final String name,price,detail;final VoidCallback onTap;const Product(this.name,this.price,this.detail,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:onTap,leading:const Icon(Icons.inventory_2_outlined,color:green),title:Text(name,style:const TextStyle(color:text,fontWeight:FontWeight.w800)),subtitle:Text(detail,style:const TextStyle(color:muted)),trailing:Text(price,style:const TextStyle(color:greenDark,fontWeight:FontWeight.w800))));}
class MatchCard extends StatelessWidget{final String name,detail;final VoidCallback onTap;const MatchCard(this.name,this.detail,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:onTap,leading:const Icon(Icons.business,color:green),title:Text(name,style:const TextStyle(color:text,fontWeight:FontWeight.w800)),subtitle:Text(detail,style:const TextStyle(color:muted)),trailing:const Icon(Icons.chevron_right,color:muted)));}
class OfferCard extends StatelessWidget{final String id,name,detail;final VoidCallback onTap;const OfferCard(this.id,this.name,this.detail,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:onTap,title:Text(name,style:const TextStyle(color:text,fontWeight:FontWeight.w800)),subtitle:Text('$id · $detail',style:const TextStyle(color:muted)),trailing:const Icon(Icons.chevron_right,color:muted)));}
class Notice extends StatelessWidget{final String title,body;final IconData icon;final Color color;const Notice(this.title,this.body,this.icon,this.color,{super.key});@override Widget build(BuildContext c)=>ActionTile(title,body,icon,color,(){});}
class Menu extends StatelessWidget{final String title;final IconData icon;final VoidCallback onTap;const Menu(this.title,this.icon,this.onTap,{super.key});@override Widget build(BuildContext c)=>ActionTile(title,'Open',icon,green,onTap);}
class Info extends StatelessWidget{final String label,value;const Info(this.label,this.value,{super.key});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:surface,borderRadius:BorderRadius.circular(14),border:Border.all(color:const Color(0xFFDCE5DC))),child:Row(children:[Expanded(child:Text(label,style:const TextStyle(color:muted))),Text(value,style:const TextStyle(color:text,fontWeight:FontWeight.w700))]));}
class Status extends StatelessWidget{final String label;final Color color;const Status(this.label,this.color,{super.key});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:5),decoration:BoxDecoration(color:color.withValues(alpha:.12),borderRadius:BorderRadius.circular(30)),child:Text(label,style:TextStyle(color:color,fontSize:11,fontWeight:FontWeight.w700)));}
class StatusBox extends StatelessWidget{final String title,body;final Color color;const StatusBox(this.title,this.body,this.color,{super.key});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:surface,borderRadius:BorderRadius.circular(14),border:Border.all(color:color.withValues(alpha:.35))),child:Row(children:[Icon(Icons.check_circle_outline,color:color),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(color:color,fontWeight:FontWeight.w800)),Text(body,style:const TextStyle(color:muted))]))]));}
class StepItem extends StatelessWidget{final String title;final bool done;const StepItem(this.title,this.done,{super.key});@override Widget build(BuildContext c)=>ListTile(leading:Icon(done?Icons.check_circle:Icons.radio_button_unchecked,color:done?green:muted),title:Text(title,style:const TextStyle(color:text)));}
class ChoiceCard extends StatelessWidget{final String title,body;final IconData icon;final VoidCallback onTap;const ChoiceCard(this.title,this.body,this.icon,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:onTap,leading:Icon(icon,color:green,size:30),title:Text(title,style:const TextStyle(color:text,fontWeight:FontWeight.w800)),subtitle:Text(body,style:const TextStyle(color:muted)),trailing:const Icon(Icons.chevron_right,color:muted)));}
class Btn extends StatelessWidget{final String label;final VoidCallback onTap;const Btn(this.label,this.onTap,{super.key});@override Widget build(BuildContext c)=>SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:onTap,style:FilledButton.styleFrom(backgroundColor:green,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))),child:Text(label,style:const TextStyle(fontWeight:FontWeight.w800))));}
class BtnSmall extends StatelessWidget{final String label;final VoidCallback onTap;const BtnSmall(this.label,this.onTap,{super.key});@override Widget build(BuildContext c)=>FilledButton.icon(onPressed:onTap,icon:const Icon(Icons.add),label:Text(label));}
class BtnOutline extends StatelessWidget{final String label;final VoidCallback onTap;const BtnOutline(this.label,this.onTap,{super.key});@override Widget build(BuildContext c)=>SizedBox(width:double.infinity,height:50,child:OutlinedButton(onPressed:onTap,style:OutlinedButton.styleFrom(foregroundColor:greenDark,side:const BorderSide(color:green),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))),child:Text(label)));}
Widget field(String hint,IconData icon,[bool password=false])=>Padding(padding:const EdgeInsets.only(bottom:2),child:TextField(obscureText:password,decoration:InputDecoration(labelText:hint,prefixIcon:Icon(icon))));