import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

const bg=Color(0xFFF7FAF7), surface=Colors.white, surface2=Color(0xFFF0F5F0), green=Color(0xFF2E9E4F), greenDark=Color(0xFF1E7A3D), gold=Color(0xFFD6AD45), text=Color(0xFF172019), muted=Color(0xFF667066), warning=Color(0xFFD58A00), dangerColor=Color(0xFFC83C3C), border=Color(0xFFDCE5DC);
const site='https://farmplugaisxd.vercel.app';
void main()=>runApp(const FarmPlug());

class FarmPlug extends StatelessWidget{const FarmPlug({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'FarmPlug AI',theme:ThemeData(useMaterial3:true,brightness:Brightness.light,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:green,brightness:Brightness.light),cardTheme:const CardThemeData(color:surface,elevation:0,margin:EdgeInsets.zero),inputDecorationTheme:const InputDecorationTheme(filled:true,fillColor:surface,border:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(14)),borderSide:BorderSide(color:border)),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(14)),borderSide:BorderSide(color:border)),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(14)),borderSide:BorderSide(color:green,width:1.5)))),home:const Splash());}
void push(BuildContext c,Widget p)=>Navigator.of(c).push(MaterialPageRoute(builder:(_)=>p));
void root(BuildContext c,Widget p)=>Navigator.of(c).pushAndRemoveUntil(MaterialPageRoute(builder:(_)=>p),(_)=>false);
Future<void> openSite(BuildContext c,String path)async{final ok=await launchUrl(Uri.parse('$site$path'),mode:LaunchMode.externalApplication);if(!ok&&c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Unable to open FarmPlug')));}

class Splash extends StatefulWidget{const Splash({super.key});@override State<Splash> createState()=>_SplashState();}
class _SplashState extends State<Splash>{@override void initState(){super.initState();Future.delayed(const Duration(milliseconds:700),(){if(!mounted)return;Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const Welcome()));});}@override Widget build(BuildContext c)=>const Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.eco_rounded,color:green,size:68),SizedBox(height:16),Text('FarmPlug AI',style:TextStyle(color:text,fontSize:30,fontWeight:FontWeight.w800)),SizedBox(height:8),Text('Smart farming. Better decisions. Greater yields.',textAlign:TextAlign.center,style:TextStyle(color:muted)),SizedBox(height:24),CircularProgressIndicator(color:green)])));}

class Frame extends StatelessWidget{final String title,subtitle;final List<Widget> children;const Frame({super.key,required this.title,required this.subtitle,required this.children});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),backgroundColor:bg,foregroundColor:text,elevation:0,leading:Navigator.of(c).canPop()?const BackButton():null),body:SafeArea(child:GestureDetector(onTap:()=>FocusScope.of(c).unfocus(),child:ListView(padding:const EdgeInsets.fromLTRB(20,12,20,28),keyboardDismissBehavior:ScrollViewKeyboardDismissBehavior.onDrag,children:[Text(subtitle,style:const TextStyle(color:muted,height:1.35)),const SizedBox(height:18),...children.map((w)=>Padding(padding:const EdgeInsets.only(bottom:14),child:w))]))));}
Widget field(String label,IconData icon,{bool obscure=false,TextEditingController? controller,TextInputType? keyboardType,String? Function(String?)? validator})=>TextFormField(controller:controller,obscureText:obscure,keyboardType:keyboardType,validator:validator,autocorrect:!obscure,decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon),contentPadding:const EdgeInsets.symmetric(horizontal:14,vertical:15)));
Widget button(String label,VoidCallback onTap)=>SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:onTap,style:FilledButton.styleFrom(backgroundColor:green,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))),child:Text(label,style:const TextStyle(fontWeight:FontWeight.w700))));
Widget buttonOutline(String label,VoidCallback onTap)=>SizedBox(width:double.infinity,height:50,child:OutlinedButton(onPressed:onTap,style:OutlinedButton.styleFrom(foregroundColor:green,side:const BorderSide(color:green),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))),child:Text(label,style:const TextStyle(fontWeight:FontWeight.w700))));
Widget section(String s)=>Align(alignment:Alignment.centerLeft,child:Padding(padding:const EdgeInsets.only(top:4,bottom:2),child:Text(s,style:const TextStyle(color:text,fontSize:17,fontWeight:FontWeight.w800))));

class Welcome extends StatelessWidget{const Welcome({super.key});@override Widget build(BuildContext c)=>Frame(title:'Welcome to FarmPlug AI',subtitle:'From Farm Intelligence to the Right Market.',children:[const Icon(Icons.agriculture_rounded,color:green,size:80),const Text('One simple workspace for your farm, AI guidance, produce sales and orders.',style:TextStyle(color:text,fontSize:18,height:1.4)),button('Get Started',()=>push(c,const Onboarding())),buttonOutline('Explore Demo',()=>push(c,const DemoRole()))]);}
class Onboarding extends StatefulWidget{const Onboarding({super.key});@override State<Onboarding> createState()=>_OnboardingState();}
class _OnboardingState extends State<Onboarding>{final f=GlobalKey<FormState>();final name=TextEditingController(),phone=TextEditingController(),crop=TextEditingController();@override void dispose(){name.dispose();phone.dispose();crop.dispose();super.dispose();}@override Widget build(BuildContext c)=>Frame(title:'Onboarding',subtitle:'Tell us about yourself.',children:[Form(key:f,child:Column(children:[field('Your name',Icons.person_outline,controller:name,validator:(v)=>v==null||v.trim().isEmpty?'Enter your name':null),field('Phone number',Icons.phone_outlined,keyboardType:TextInputType.phone,controller:phone,validator:(v)=>v==null||v.trim().length<10?'Enter a valid phone number':null),field('Main crop',Icons.spa_outlined,controller:crop,validator:(v)=>v==null||v.trim().isEmpty?'Enter your main crop':null)])),button('Continue',(){if(f.currentState!.validate())push(c,const FarmSetup());})]);}
class FarmSetup extends StatefulWidget{const FarmSetup({super.key});@override State<FarmSetup> createState()=>_FarmSetupState();}
class _FarmSetupState extends State<FarmSetup>{final f=GlobalKey<FormState>();final farm=TextEditingController(),loc=TextEditingController(),area=TextEditingController();@override void dispose(){farm.dispose();loc.dispose();area.dispose();super.dispose();}@override Widget build(BuildContext c)=>Frame(title:'Farm Setup',subtitle:'Add your first farm.',children:[Form(key:f,child:Column(children:[field('Farm name',Icons.agriculture_outlined,controller:farm,validator:(v)=>v==null||v.isEmpty?'Required':null),field('Location',Icons.location_on_outlined,controller:loc,validator:(v)=>v==null||v.isEmpty?'Required':null),field('Area in acres',Icons.square_foot_outlined,keyboardType:const TextInputType.numberWithOptions(decimal:true),controller:area,validator:(v)=>double.tryParse(v??'')==null?'Enter area':null)])),button('Save Farm & Continue',(){if(f.currentState!.validate())push(c,const SignIn());})]);}
class SignIn extends StatefulWidget{const SignIn({super.key});@override State<SignIn> createState()=>_SignInState();}
class _SignInState extends State<SignIn>{final f=GlobalKey<FormState>();final login=TextEditingController(),pass=TextEditingController();bool loading=false,show=false;@override void dispose(){login.dispose();pass.dispose();super.dispose();}@override Widget build(BuildContext c)=>Frame(title:'Sign In',subtitle:'Use your FarmPlug account.',children:[Form(key:f,child:Column(children:[field('Phone or email',Icons.person_outline,controller:login,validator:(v)=>v==null||v.trim().isEmpty?'Enter phone or email':null),TextFormField(controller:pass,obscureText:!show,validator:(v)=>v==null||v.length<6?'Minimum 6 characters':null,decoration:InputDecoration(labelText:'Password',prefixIcon:const Icon(Icons.lock_outline),suffixIcon:IconButton(onPressed:()=>setState(()=>show=!show),icon:Icon(show?Icons.visibility_off:Icons.visibility)))])),Align(alignment:Alignment.centerRight,child:TextButton(onPressed:()=>push(c,const ForgotPassword()),child:const Text('Forgot password?'))),button(loading?'Signing in…':'Sign In',loading?(){}:(){if(f.currentState!.validate()){setState(()=>loading=true);Future.delayed(const Duration(milliseconds:400),(){if(mounted)root(c,const HomeShell());});}}),buttonOutline('Continue with Google',()=>push(c,const GoogleLogin())),TextButton(onPressed:()=>push(c,const SignUp()),child:const Text('New to FarmPlug? Sign Up'))]);}
class SignUp extends StatefulWidget{const SignUp({super.key});@override State<SignUp> createState()=>_SignUpState();}
class _SignUpState extends State<SignUp>{final f=GlobalKey<FormState>();final name=TextEditingController(),phone=TextEditingController(),p=TextEditingController(),cp=TextEditingController();@override void dispose(){name.dispose();phone.dispose();p.dispose();cp.dispose();super.dispose();}@override Widget build(BuildContext c){return Frame(title:'Create Account',subtitle:'Create your farmer workspace.',children:[Form(key:f,child:Column(children:[field('Full name',Icons.person_outline,controller:name,validator:(v)=>v==null||v.trim().isEmpty?'Enter your name':null),field('Phone number',Icons.phone_outlined,keyboardType:TextInputType.phone,controller:phone,validator:(v)=>v==null||v.length<10?'Enter valid phone':null),field('Password',Icons.lock_outline,obscure:true,controller:p,validator:(v)=>v==null||v.length<6?'Minimum 6 characters':null),field('Confirm password',Icons.lock_reset_outlined,obscure:true,controller:cp,validator:(v){if(v==null||v.isEmpty)return'Confirm your password';if(v!=p.text)return'Passwords do not match';return null;})])),const Text('By continuing you agree to the Terms and Privacy Policy.',style:TextStyle(color:muted,fontSize:12)),button('Create Account',(){if(f.currentState!.validate())root(c,const HomeShell());})]);}}
class GoogleLogin extends StatelessWidget{const GoogleLogin({super.key});@override Widget build(BuildContext c)=>Frame(title:'Google Login',subtitle:'Google sign-in demo.',children:[const Icon(Icons.account_circle,color:green,size:72),const Text('Google authentication is not connected in this demo build.',style:TextStyle(color:muted)),button('Continue',()=>push(c,const RoleSelection()))]);}
class ForgotPassword extends StatefulWidget{const ForgotPassword({super.key});@override State<ForgotPassword> createState()=>_ForgotPasswordState();}
class _ForgotPasswordState extends State<ForgotPassword>{final email=TextEditingController();bool sent=false;@override void dispose(){email.dispose();super.dispose();}@override Widget build(BuildContext c)=>Frame(title:'Forgot Password',subtitle:'Request a password reset.',children:[field('Phone or email',Icons.person_outline,controller:email,validator:(v)=>v==null||v.isEmpty?'Required':null),button(sent?'Reset requested':'Send reset request',(){setState(()=>sent=true);}),if(sent)const StatusBox('Request created','Check your registered contact.',green)]);}
class RoleSelection extends StatelessWidget{const RoleSelection({super.key});@override Widget build(BuildContext c)=>Frame(title:'Choose Your Role',subtitle:'Select how you use FarmPlug.',children:[ChoiceCard('Farmer','Manage farms, crops and sales',Icons.agriculture,()=>push(c,const ProfileCompletion())),ChoiceCard('Buyer','Source verified produce',Icons.storefront,()=>push(c,const ProfileCompletion())),ChoiceCard('FPO','Aggregate farmers and supply',Icons.groups,()=>push(c,const ProfileCompletion()))]);}
class ProfileCompletion extends StatefulWidget{const ProfileCompletion({super.key});@override State<ProfileCompletion> createState()=>_ProfileCompletionState();}
class _ProfileCompletionState extends State<ProfileCompletion>{final f=GlobalKey<FormState>();final name=TextEditingController(),city=TextEditingController();@override void dispose(){name.dispose();city.dispose();super.dispose();}@override Widget build(BuildContext c)=>Frame(title:'Profile Completion',subtitle:'Complete your workspace.',children:[Form(key:f,child:Column(children:[field('Display name',Icons.badge_outlined,controller:name,validator:(v)=>v==null||v.isEmpty?'Required':null),field('Village / city',Icons.location_city_outlined,controller:city,validator:(v)=>v==null||v.isEmpty?'Required':null),DropdownButtonFormField<String>(decoration:const InputDecoration(labelText:'Preferred language',prefixIcon:Icon(Icons.language)),items:const[DropdownMenuItem(value:'English',child:Text('English')),DropdownMenuItem(value:'Tamil',child:Text('Tamil')),DropdownMenuItem(value:'Hindi',child:Text('Hindi'))],onChanged:(_){})])),button('Finish Setup',(){if(f.currentState!.validate())root(c,const HomeShell());})]);}

class HomeShell extends StatefulWidget{const HomeShell({super.key});@override State<HomeShell> createState()=>_HomeShellState();}
class _HomeShellState extends State<HomeShell>{int tab=0;final pages=const[FarmerHome(),AiCenter(),MyFarm(),Orders(),Profile()];@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(backgroundColor:surface,selectedIndex:tab,indicatorColor:green.withAlpha(35),onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.auto_awesome_outlined),selectedIcon:Icon(Icons.auto_awesome),label:'AI Center'),NavigationDestination(icon:Icon(Icons.agriculture_outlined),selectedIcon:Icon(Icons.agriculture),label:'My Farm'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),selectedIcon:Icon(Icons.receipt_long),label:'Orders'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile')]));}

class FarmerHome extends StatelessWidget{const FarmerHome({super.key});@override Widget build(BuildContext c)=>Frame(title:'Good morning, farmer',subtitle:'Your farm at a glance.',children:[CardBox(icon:Icons.wb_sunny_outlined,title:'28°C · Partly cloudy',body:'Coimbatore · Demo weather data',accent:green),section('Farm Overview'),Row(children:[Expanded(child:Stat('3','Farms')),const SizedBox(width:8),Expanded(child:Stat('6','Crops'))]),Row(children:[Expanded(child:Stat('2','Orders')),const SizedBox(width:8),Expanded(child:Stat('1','Alert',accent:warning))]),section('Today’s Tasks'),ActionTile('Irrigation check','Tomato plot · due today',Icons.water_drop,green,()=>push(c,const CropDetails())),ActionTile('Review market price','Tomato · local market',Icons.trending_up,gold,()=>push(c,const Marketplace())),ActionTile('Crop health review','One crop needs attention',Icons.health_and_safety,warning,()=>push(c,const CropHealth())),ActionTile('Notifications','View latest updates',Icons.notifications_none,green,()=>push(c,const Notifications()))]);}
class AiCenter extends StatefulWidget{const AiCenter({super.key});@override State<AiCenter> createState()=>_AiCenterState();}
class _AiCenterState extends State<AiCenter>{final q=TextEditingController();String answer='';@override void dispose(){q.dispose();super.dispose();}void ask(){final s=q.text.trim();if(s.isEmpty)return;setState(()=>answer=s.toLowerCase().contains('water')?'Check soil moisture before irrigation and avoid waterlogging.':'Check crop stage, soil moisture, weather and local market conditions.');}@override Widget build(BuildContext c)=>Frame(title:'AI Center',subtitle:'Ask a farm question.',children:[CardBox(icon:Icons.auto_awesome,title:'FarmPlug Intelligence',body:'Practical recommendations for your next decision.',accent:green),TextField(controller:q,onSubmitted:(_)=>ask(),decoration:InputDecoration(labelText:'Ask FarmPlug AI',hintText:'When should I irrigate tomato?',prefixIcon:const Icon(Icons.chat_bubble_outline),suffixIcon:IconButton(onPressed:ask,icon:const Icon(Icons.send,color:green)))),if(answer.isNotEmpty)StatusBox('FarmPlug AI',answer,green),ActionTile('Disease diagnosis','Check crop symptoms',Icons.bug_report,green,()=>push(c,const CropHealth())),ActionTile('Market prices','See price signals',Icons.trending_up,gold,()=>push(c,const Marketplace()))]);}
class MyFarm extends StatelessWidget{const MyFarm({super.key});@override Widget build(BuildContext c)=>Frame(title:'My Farm',subtitle:'Manage plots, crops and farm health.',children:[Align(alignment:Alignment.centerRight,child:FilledButton.tonalIcon(onPressed:()=>push(c,const FarmSetup()),icon:const Icon(Icons.add),label:const Text('Add Farm'))),FarmCard('North Field','2.5 acres','Coimbatore','Healthy',green,()=>push(c,const Crops())),FarmCard('Greenhouse Plot','1.2 acres','Coimbatore','Needs Attention',warning,()=>push(c,const Crops())),section('Crops'),CropTile('Tomato','North Field · 1.4 acres','Healthy',green,()=>push(c,const CropDetails())),CropTile('Chilli','North Field · 0.8 acres','Healthy',green,()=>push(c,const CropDetails()))]);}
class Crops extends StatelessWidget{const Crops({super.key});@override Widget build(BuildContext c)=>Frame(title:'Crops',subtitle:'All crops across your farms.',children:[CropTile('Tomato','North Field · 1.4 acres','Healthy',green,()=>push(c,const CropDetails())),CropTile('Chilli','North Field · 0.8 acres','Healthy',green,()=>push(c,const CropDetails())),button('Add Crop',()=>push(c,const CropDetails()))]);}
class CropDetails extends StatelessWidget{const CropDetails({super.key});@override Widget build(BuildContext c)=>Frame(title:'Crop Details',subtitle:'Tomato · North Field · 1.4 acres',children:[CardBox(icon:Icons.spa,title:'Crop Health',body:'Healthy · 42 days to harvest',accent:green),const Info('Sowing date','20 Jul 2026'),const Info('Irrigation','Next check today'),const Info('Area','1.4 acres'),button('Open Crop Health',()=>push(c,const CropHealth())),buttonOutline('Farm Intelligence',()=>push(c,const FarmIntelligence()))]);}
class CropHealth extends StatelessWidget{const CropHealth({super.key});@override Widget build(BuildContext c)=>Frame(title:'Crop Health',subtitle:'Monitor symptoms and actions.',children:[const StatusBox('Healthy','No critical issue detected.',green),const Info('Latest check','Today'),const Info('Risk','Low'),const Info('Action','Continue planned irrigation'),button('Get AI Diagnosis',()=>push(c,const AiDecision()))]);}
class FarmIntelligence extends StatelessWidget{const FarmIntelligence({super.key});@override Widget build(BuildContext c)=>Frame(title:'Farm Intelligence',subtitle:'Signals for your next decision.',children:[const Info('Weather','28°C · Demo data'),const Info('Water','Irrigation check due'),const Info('Market','Tomato price signal positive'),const Info('Crop','Tomato healthy'),button('Open AI Decision Center',()=>push(c,const AiDecision()))]);}
class AiDecision extends StatelessWidget{const AiDecision({super.key});@override Widget build(BuildContext c)=>Frame(title:'AI Decision Center',subtitle:'Recommended next actions.',children:[const CardBox(icon:Icons.auto_awesome,title:'Recommendation',body:'Check tomato irrigation today and review local tomato prices before listing.',accent:green),button('Open Market',()=>push(c,const Marketplace())),buttonOutline('Farm Intelligence',()=>push(c,const FarmIntelligence()))]);}

class Marketplace extends StatefulWidget{const Marketplace({super.key});@override State<Marketplace> createState()=>_MarketplaceState();}
class _MarketplaceState extends State<Marketplace>{String query='',cat='All';final data=const[{'name':'Tomato','price':'₹42/kg','type':'Vegetables','detail':'Fresh · verified supply'},{'name':'Chilli','price':'₹86/kg','type':'Vegetables','detail':'Fresh · verified supply'},{'name':'Banana','price':'₹34/kg','type':'Fruits','detail':'Fresh · verified supply'},{'name':'Rice','price':'₹58/kg','type':'Grains','detail':'Verified supply'}];@override Widget build(BuildContext c){final items=data.where((x)=>(cat=='All'||x['type']==cat)&&('${x['name']} ${x['type']}'.toLowerCase().contains(query.toLowerCase()))).toList();return Frame(title:'Marketplace',subtitle:'Search produce and prices.',children:[TextField(onChanged:(v)=>setState(()=>query=v),decoration:const InputDecoration(labelText:'Search produce',hintText:'Tomato, chilli…',prefixIcon:Icon(Icons.search))),Wrap(spacing:8,children:['All','Vegetables','Fruits','Grains','Spices'].map((x)=>ChoiceChip(label:Text(x),selected:cat==x,onSelected:(_)=>setState(()=>cat=x))).toList()),if(items.isEmpty)const EmptyState('No matching produce','Try another search or category.'),...items.map((x)=>Product(x['name']!,x['price']!,x['detail']!,()=>push(c,const ListingDetails()))),button('List My Produce',()=>push(c,const AddProduce()))]);}}
class AddProduce extends StatefulWidget{const AddProduce({super.key});@override State<AddProduce> createState()=>_AddProduceState();}
class _AddProduceState extends State<AddProduce>{final f=GlobalKey<FormState>();final type=TextEditingController(),qty=TextEditingController(),price=TextEditingController();@override void dispose(){type.dispose();qty.dispose();price.dispose();super.dispose();}@override Widget build(BuildContext c)=>Frame(title:'List Produce',subtitle:'Create a clear listing.',children:[Form(key:f,child:Column(children:[field('Produce type',Icons.spa_outlined,controller:type,validator:(v)=>v==null||v.isEmpty?'Required':null),field('Quantity (kg)',Icons.scale_outlined,keyboardType:TextInputType.number,controller:qty,validator:(v)=>double.tryParse(v??'')==null?'Enter quantity':null),field('Price per kg',Icons.currency_rupee,keyboardType:TextInputType.number,controller:price,validator:(v)=>double.tryParse(v??'')==null?'Enter price':null)])),const CardBox(icon:Icons.photo_camera_outlined,title:'Photo',body:'Photo upload will be connected to storage in the backend build.',accent:green),button('Publish Listing',(){if(f.currentState!.validate())push(c,const MyListings());})]);}
class MyListings extends StatelessWidget{const MyListings({super.key});@override Widget build(BuildContext c)=>Frame(title:'My Listings',subtitle:'Manage active produce listings.',children:[Product('Tomato','₹42/kg','500 kg · Active',()=>push(c,const ListingDetails())),Product('Chilli','₹86/kg','250 kg · Active',()=>push(c,const ListingDetails())),button('Add Another Listing',()=>push(c,const AddProduce()))]);}
class ListingDetails extends StatelessWidget{const ListingDetails({super.key});@override Widget build(BuildContext c)=>Frame(title:'Listing Details',subtitle:'Tomato · Fresh produce',children:[const Info('Quantity','500 kg'),const Info('Price','₹42/kg'),const Info('Location','Coimbatore'),const StatusBox('Active','Visible to matched buyers.',green),button('View Buyer Matches',()=>push(c,const BuyerMatches()))]);}
class BuyerMatches extends StatelessWidget{const BuyerMatches({super.key});@override Widget build(BuildContext c)=>Frame(title:'Buyer Matches',subtitle:'Matched buyers.',children:[MatchCard('Fresh Foods Pvt Ltd','300 kg · ₹42/kg',()=>push(c,const BuyerDetails())),MatchCard('Coimbatore Retail Hub','200 kg · ₹41/kg',()=>push(c,const BuyerDetails())),button('View Offers',()=>push(c,const Offers()))]);}
class BuyerDetails extends StatelessWidget{const BuyerDetails({super.key});@override Widget build(BuildContext c)=>Frame(title:'Buyer Details',subtitle:'Verified buyer profile.',children:[const CardBox(icon:Icons.business,title:'Fresh Foods Pvt Ltd',body:'Verified buyer · Coimbatore',accent:green),const Info('Demand','300 kg tomato'),const Info('Expected rate','₹42/kg'),button('View Offers',()=>push(c,const Offers()))]);}
class Offers extends StatelessWidget{const Offers({super.key});@override Widget build(BuildContext c)=>Frame(title:'Offers',subtitle:'Review buyer offers.',children:[OfferCard('#OF-204','Fresh Foods Pvt Ltd','500 kg · ₹42/kg',()=>push(c,const OfferDetails())),OfferCard('#OF-199','Retail Hub','200 kg · ₹41/kg',()=>push(c,const OfferDetails()))]);}
class OfferDetails extends StatelessWidget{const OfferDetails({super.key});@override Widget build(BuildContext c)=>Frame(title:'Offer Details',subtitle:'#OF-204 · Fresh Foods Pvt Ltd',children:[const Info('Quantity','500 kg'),const Info('Rate','₹42/kg'),const Info('Payment','Bank transfer'),button('Accept Offer',()=>push(c,const AcceptOffer())),buttonOutline('Decline',()=>Navigator.pop(c))]);}
class AcceptOffer extends StatelessWidget{const AcceptOffer({super.key});@override Widget build(BuildContext c)=>Frame(title:'Accept Offer',subtitle:'Confirm sale details.',children:[const StatusBox('Ready to confirm','500 kg Tomato · ₹21,000',green),button('Confirm Offer',()=>push(c,const Orders())),buttonOutline('Cancel',()=>Navigator.pop(c))]);}

class Orders extends StatefulWidget{const Orders({super.key});@override State<Orders> createState()=>_OrdersState();}
class _OrdersState extends State<Orders>{String filter='All';final List<Map<String,dynamic>> orders=const[{'id':'#FP-1042','item':'Tomato · 500 kg','status':'Confirmed','color':green},{'id':'#FP-1038','item':'Chilli · 250 kg','status':'Pending','color':warning},{'id':'#FP-1022','item':'Banana · 100 kg','status':'Completed','color':green}];@override Widget build(BuildContext c){final items=orders.where((o)=>filter=='All'||o['status']==filter).toList();return Frame(title:'Orders',subtitle:'Track sales from confirmation to delivery.',children:[Wrap(spacing:8,children:['All','Pending','Confirmed','Completed'].map((x)=>ChoiceChip(label:Text(x),selected:filter==x,onSelected:(_)=>setState(()=>filter=x))).toList()),if(items.isEmpty)const EmptyState('No orders','There are no orders in this status.'),...items.map((o)=>OrderCard(o['id'] as String,o['item'] as String,o['status'] as String,o['color'] as Color,()=>push(c,const OrderDetails()))) ]);}}
class OrderDetails extends StatelessWidget{const OrderDetails({super.key});@override Widget build(BuildContext c)=>Frame(title:'Order Details',subtitle:'#FP-1042 · Today',children:[const Info('Buyer','Fresh Foods Pvt Ltd'),const Info('Item','Tomato · 500 kg'),const Info('Payment','₹21,000 · Bank transfer'),const StatusBox('Confirmed','Ready for collection.',green),button('Track Order',()=>push(c,const OrderTracking())),buttonOutline('View Notifications',()=>push(c,const Notifications()))]);}
class OrderTracking extends StatelessWidget{const OrderTracking({super.key});@override Widget build(BuildContext c)=>Frame(title:'Order Tracking',subtitle:'#FP-1042 · Delivery progress',children:[const StepItem('Order confirmed',true),const StepItem('Ready for collection',true),const StepItem('In transit',false),const StepItem('Delivered',false),const StatusBox('Next step','Keep produce ready for collection.',green)]);}
class Notifications extends StatelessWidget{const Notifications({super.key});@override Widget build(BuildContext c)=>Frame(title:'Notifications',subtitle:'Updates that need your attention.',children:[ActionTile('Order confirmed','#FP-1042 · 500 kg Tomato',Icons.check_circle_outline,green,()=>push(c,const OrderDetails())),ActionTile('Market signal','Tomato prices look positive',Icons.trending_up,gold,()=>push(c,const Marketplace())),ActionTile('Crop reminder','Check tomato irrigation today',Icons.water_drop,green,()=>push(c,const CropDetails()))]);}
class Profile extends StatelessWidget{const Profile({super.key});@override Widget build(BuildContext c)=>Frame(title:'Profile',subtitle:'Account and preferences.',children:[const CardBox(icon:Icons.person,title:'Farm owner',body:'Farmer · Coimbatore · Demo profile',accent:green),ActionTile('Settings','Account and app preferences',Icons.settings_outlined,green,()=>push(c,const SettingsPage())),ActionTile('Language','English',Icons.language,green,()=>push(c,const LanguagePage())),ActionTile('Security','Password and sign-in',Icons.lock_outline,green,()=>push(c,const SecurityPage())),ActionTile('Download Farmer App','Open the FarmPlug download page',Icons.download_outlined,gold,()=>openSite(c,'/download-app')),ActionTile('Log out','Return to welcome screen',Icons.logout,dangerColor,()=>push(c,const LogoutConfirm()))]);}
class SettingsPage extends StatelessWidget{const SettingsPage({super.key});@override Widget build(BuildContext c)=>Frame(title:'Settings',subtitle:'Control your preferences.',children:[ActionTile('Language','English',Icons.language,green,()=>push(c,const LanguagePage())),ActionTile('Units','Acres and kilograms',Icons.straighten,green,()=>push(c,const UnitsPage())),ActionTile('Security','Password and sign-in',Icons.security,green,()=>push(c,const SecurityPage())),ActionTile('Notifications','Manage updates',Icons.notifications,green,()=>push(c,const Notifications()))]);}
class LanguagePage extends StatefulWidget{const LanguagePage({super.key});@override State<LanguagePage> createState()=>_LanguagePageState();}
class _LanguagePageState extends State<LanguagePage>{String value='English';@override Widget build(BuildContext c)=>Frame(title:'Language',subtitle:'Choose your app language.',children:[...['English','Tamil','Hindi'].map((x)=>RadioListTile<String>(value:x,groupValue:value,onChanged:(v)=>setState(()=>value=v!),title:Text(x))),button('Save Language',()=>Navigator.pop(c))]);}
class UnitsPage extends StatelessWidget{const UnitsPage({super.key});@override Widget build(BuildContext c)=>Frame(title:'Units',subtitle:'Farm measurement units.',children:[const Info('Area','Acres'),const Info('Weight','Kilograms'),button('Save Units',()=>Navigator.pop(c))]);}
class SecurityPage extends StatelessWidget{const SecurityPage({super.key});@override Widget build(BuildContext c)=>Frame(title:'Security',subtitle:'Keep your account protected.',children:[const StatusBox('Account security','Use a strong password and never share verification codes.',green),ActionTile('Change password','Update your password',Icons.lock_reset,green,()=>push(c,const ChangePassword()))]);}
class ChangePassword extends StatefulWidget{const ChangePassword({super.key});@override State<ChangePassword> createState()=>_ChangePasswordState();}
class _ChangePasswordState extends State<ChangePassword>{final f=GlobalKey<FormState>();final a=TextEditingController(),b=TextEditingController();@override void dispose(){a.dispose();b.dispose();super.dispose();}@override Widget build(BuildContext c)=>Frame(title:'Change Password',subtitle:'Choose a password with at least 6 characters.',children:[Form(key:f,child:Column(children:[field('New password',Icons.lock_outline,obscure:true,controller:a,validator:(v)=>v==null||v.length<6?'Minimum 6 characters':null),field('Confirm password',Icons.lock_reset,obscure:true,controller:b,validator:(v)=>v!=a.text?'Passwords do not match':null)])),button('Save Password',(){if(f.currentState!.validate())Navigator.pop(c);})]);}
class LogoutConfirm extends StatelessWidget{const LogoutConfirm({super.key});@override Widget build(BuildContext c)=>Frame(title:'Log Out',subtitle:'You can sign in again anytime.',children:[const StatusBox('Ready to log out','Your current demo session will be cleared.',warning),button('Log Out',()=>root(c,const Welcome())),buttonOutline('Cancel',()=>Navigator.pop(c))]);}
class Aggregation extends StatelessWidget{const Aggregation({super.key});@override Widget build(BuildContext c)=>generic(c,'Aggregation','Group farmer supply for efficient selling.',Icons.inventory_2);}
class AggregationDetails extends StatelessWidget{const AggregationDetails({super.key});@override Widget build(BuildContext c)=>generic(c,'Aggregation Details','Tomato collection batch · 750 kg.',Icons.list_alt);}
class CollectionCenter extends StatelessWidget{const CollectionCenter({super.key});@override Widget build(BuildContext c)=>generic(c,'Collection Center','Nearest demo collection point: Coimbatore.',Icons.location_on);}
class Logistics extends StatelessWidget{const Logistics({super.key});@override Widget build(BuildContext c)=>generic(c,'Logistics','Track pickup and delivery coordination.',Icons.local_shipping);}
class DeliveryDetails extends StatelessWidget{const DeliveryDetails({super.key});@override Widget build(BuildContext c)=>generic(c,'Delivery Details','Delivery schedule and handover information.',Icons.route);}
class FarmPlugIntelligence extends StatelessWidget{const FarmPlugIntelligence({super.key});@override Widget build(BuildContext c)=>generic(c,'FarmPlug Intelligence','AI-powered farm signals and recommendations.',Icons.auto_awesome);}
class Market extends StatelessWidget{const Market({super.key});@override Widget build(BuildContext c)=>const Marketplace();}
class DemoRole extends StatelessWidget{const DemoRole({super.key});@override Widget build(BuildContext c)=>Frame(title:'Demo Role',subtitle:'Explore the farmer experience.',children:[ChoiceCard('Farmer Demo','See the farmer workspace',Icons.agriculture,()=>root(c,const HomeShell())),ChoiceCard('Buyer Demo','Explore marketplace workflows',Icons.storefront,()=>push(c,const Marketplace())),ChoiceCard('FPO Demo','Explore aggregation tools',Icons.groups,()=>push(c,const Aggregation()))]);}
class DemoWorkspace extends StatelessWidget{const DemoWorkspace({super.key});@override Widget build(BuildContext c)=>const HomeShell();}
class ErrorPage extends StatelessWidget{const ErrorPage({super.key});@override Widget build(BuildContext c)=>Frame(title:'Something went wrong',subtitle:'Try again or return home.',children:[const StatusBox('Error','The requested screen could not be completed.',dangerColor),button('Go Home',()=>root(c,const HomeShell()))]);}
class Offline extends StatelessWidget{const Offline({super.key});@override Widget build(BuildContext c)=>Frame(title:'You’re Offline',subtitle:'Some live features need internet.',children:[const StatusBox('Offline','Your local demo data is still available.',warning),button('Continue Offline',()=>root(c,const HomeShell()))]);}
class EmptyState extends StatelessWidget{final String title,body;const EmptyState(this.title,this.body,{super.key});@override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:surface,border:Border.all(color:border),borderRadius:BorderRadius.circular(16)),child:Column(children:[const Icon(Icons.inbox_outlined,color:muted,size:42),const SizedBox(height:8),Text(title,style:const TextStyle(fontWeight:FontWeight.w800,color:text)),const SizedBox(height:4),Text(body,textAlign:TextAlign.center,style:const TextStyle(color:muted))]));}
Widget generic(BuildContext c,String title,String subtitle,IconData icon)=>Frame(title:title,subtitle:subtitle,children:[CardBox(icon:icon,title:title,body:'This section is ready for the connected backend workflow.',accent:green),const EmptyState('Demo data','Connect the production data source to populate this section.')]);
class CardBox extends StatelessWidget{final IconData icon;final String title,body;final Color accent;const CardBox({super.key,required this.icon,required this.title,required this.body,required this.accent});@override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:surface2,borderRadius:BorderRadius.circular(16)),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[CircleAvatar(backgroundColor:accent.withAlpha(31),foregroundColor:accent,child:Icon(icon)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:text,fontWeight:FontWeight.w800)),const SizedBox(height:4),Text(body,style:const TextStyle(color:muted,height:1.35))]))]));}
class StatusBox extends StatelessWidget{final String title,body;final Color color;const StatusBox(this.title,this.body,this.color,{super.key});@override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:color.withAlpha(20),borderRadius:BorderRadius.circular(14),border:Border.all(color:color.withAlpha(64))),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.check_circle_outline,color:color),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:TextStyle(color:color,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(body,style:const TextStyle(color:text))]))]));}
class Info extends StatelessWidget{final String label,value;const Info(this.label,this.value,{super.key});@override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.symmetric(vertical:12),decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:border))),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:115,child:Text(label,style:const TextStyle(color:muted))),Expanded(child:Text(value,textAlign:TextAlign.right,style:const TextStyle(color:text,fontWeight:FontWeight.w700)))]));}
class Stat extends StatelessWidget{final String value,label;final Color accent;const Stat(this.value,this.label,{super.key,this.accent=green});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:surface,border:Border.all(color:border),borderRadius:BorderRadius.circular(14)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(value,style:TextStyle(color:accent,fontSize:25,fontWeight:FontWeight.w800)),Text(label,style:const TextStyle(color:muted))]));}
class ActionTile extends StatelessWidget{final String title,body;final IconData icon;final Color color;final VoidCallback onTap;const ActionTile(this.title,this.body,this.icon,this.color,this.onTap,{super.key});@override Widget build(BuildContext c)=>Card(child:ListTile(onTap:onTap,contentPadding:const EdgeInsets.symmetric(horizontal:14,vertical:4),leading:CircleAvatar(backgroundColor:color.withAlpha(26),foregroundColor:color,child:Icon(icon)),title:Text(title,style:const TextStyle(color:text,fontWeight:FontWeight.w700)),subtitle:Text(body,style:const TextStyle(color:muted)),trailing:const Icon(Icons.chevron_right,color:muted)));}
class ChoiceCard extends StatelessWidget{final String title,body;final IconData icon;final VoidCallback onTap;const ChoiceCard(this.title,this.body,this.icon,this.onTap,{super.key});@override Widget build(BuildContext c)=>ActionTile(title,body,icon,green,onTap);}
class FarmCard extends StatelessWidget{final String title,area,location,status;final Color color;final VoidCallback onTap;const FarmCard(this.title,this.area,this.location,this.status,this.color,this.onTap,{super.key});@override Widget build(BuildContext c)=>ActionTile(title,'$area · $location · $status',Icons.agriculture,color,onTap);}
class CropTile extends StatelessWidget{final String title,body,status;final Color color;final VoidCallback onTap;const CropTile(this.title,this.body,this.status,this.color,this.onTap,{super.key});@override Widget build(BuildContext c)=>ActionTile(title,'$body · $status',Icons.spa,color,onTap);}
class Product extends StatelessWidget{final String title,price,detail;final VoidCallback onTap;const Product(this.title,this.price,this.detail,this.onTap,{super.key});@override Widget build(BuildContext c)=>ActionTile(title,'$price · $detail',Icons.inventory_2,green,onTap);}
class MatchCard extends StatelessWidget{final String title,body;final VoidCallback onTap;const MatchCard(this.title,this.body,this.onTap,{super.key});@override Widget build(BuildContext c)=>ActionTile(title,body,Icons.handshake,green,onTap);}
class OfferCard extends StatelessWidget{final String id,title,body;final VoidCallback onTap;const OfferCard(this.id,this.title,this.body,this.onTap,{super.key});@override Widget build(BuildContext c)=>ActionTile('$id · $title',body,Icons.local_offer,green,onTap);}
class OrderCard extends StatelessWidget{final String id,item,status;final Color color;final VoidCallback onTap;const OrderCard(this.id,this.item,this.status,this.color,this.onTap,{super.key});@override Widget build(BuildContext c)=>ActionTile('$id · $status',item,Icons.receipt_long,color,onTap);}
class StepItem extends StatelessWidget{final String title;final bool done;const StepItem(this.title,this.done,{super.key});@override Widget build(BuildContext c)=>ListTile(contentPadding:EdgeInsets.zero,leading:CircleAvatar(backgroundColor:(done?green:muted).withAlpha(31),foregroundColor:done?green:muted,child:Icon(done?Icons.check:Icons.circle_outlined)),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w700,color:text)),subtitle:Text(done?'Completed':'Pending',style:const TextStyle(color:muted)));}
