'use client';
import './v2.css';
import { useEffect, useState } from 'react';
import { ArrowRight, Bell, Check, ChevronLeft, Home, Leaf, LogIn, Package, Search, ShoppingBag, Sparkles, User, Wheat, UserPlus, LogOut } from 'lucide-react';
import { supabase } from '../../lib/supabase';

type Screen='splash'|'login'|'signup'|'home'|'ai'|'farm'|'market'|'produce'|'orders'|'order'|'profile'|'settings';
type Row=Record<string, any>;
const nav=[['home','Home',Home],['farm','My Farm',Wheat],['market','Market',ShoppingBag],['orders','Orders',Package],['profile','Profile',User]] as const;

export default function FarmPlugFarmerApp(){
 const [screen,setScreen]=useState<Screen>('splash');
 const [session,setSession]=useState<any>(null); const [name,setName]=useState('Farmer');
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState('');
 const [farm,setFarm]=useState<Row|null>(null); const [crops,setCrops]=useState<Row[]>([]); const [supplies,setSupplies]=useState<Row[]>([]); const [requirements,setRequirements]=useState<Row[]>([]); const [orders,setOrders]=useState<Row[]>([]); const [prices,setPrices]=useState<Row[]>([]); const [forecasts,setForecasts]=useState<Row[]>([]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 const [crop,setCrop]=useState('Tomato'); const [qty,setQty]=useState('500'); const [quality,setQuality]=useState('Grade A');
 useEffect(()=>{let active=true; const boot=async()=>{if(!supabase){setScreen('login');setMessage('Supabase is not configured in this deployment.');return} const {data}=await supabase.auth.getSession(); if(!active)return; if(data.session){setSession(data.session);await load(data.session.user.id);setScreen('home')}else setScreen('login')}; boot(); const {data:sub}=supabase?.auth.onAuthStateChange(async(_e,s)=>{if(s&&active){setSession(s);await load(s.user.id);setScreen('home')}}) || {data:{subscription:{unsubscribe(){}}}}; return()=>{active=false;sub.subscription.unsubscribe()};},[]);
 const load=async(uid:string)=>{if(!supabase)return; const [p,f,c,s,r,o,mp,pf]=await Promise.all([supabase.from('profiles').select('email,farm_role').eq('id',uid).maybeSingle(),supabase.from('farms').select('*').eq('owner_id',uid).order('created_at').limit(1).maybeSingle(),supabase.from('crops').select('*').order('created_at',{ascending:false}),supabase.from('farmplug_supply_listings').select('*').eq('created_by',uid).order('created_at',{ascending:false}),supabase.from('farmplug_buyer_requirements').select('*').eq('status','open').order('created_at',{ascending:false}),supabase.from('farmplug_orders').select('*').or(`farmer_id.eq.${uid},buyer_id.eq.${uid}`).order('created_at',{ascending:false}),supabase.from('market_prices').select('*').order('price_date',{ascending:false}).limit(20),supabase.from('price_forecasts').select('*').order('forecast_date',{ascending:false}).limit(20)]); setName((p.data as any)?.full_name || (p.data as any)?.email?.split('@')[0] || session?.user?.email?.split('@')[0] || 'Farmer'); setFarm(f.data); setCrops(c.data||[]); setSupplies(s.data||[]); setRequirements(r.data||[]); setOrders(o.data||[]); setPrices(mp.data||[]); setForecasts(pf.data||[]); };
 const go=(s:Screen)=>{setMessage('');setScreen(s)};
 const signIn=async()=>{if(!supabase){setMessage('Supabase is not configured.');return}setBusy(true);const {error,data}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error){setMessage(error.message);return}setSession(data.session);await load(data.user.id);setScreen('home')};
 const signUp=async()=>{if(!supabase){setMessage('Supabase is not configured.');return}if(password.length<8||password!==confirm){setMessage('Use matching passwords with at least 8 characters.');return}setBusy(true);const {data,error}=await supabase.auth.signUp({email,password});if(error){setBusy(false);setMessage(error.message);return}if(data.user){await supabase.from('profiles').upsert({id:data.user.id,email,farm_role:'farmer'});await supabase.from('farmer_profiles').upsert({id:data.user.id,full_name:name.trim()||'Farmer'});}setBusy(false);setMessage(data.session?'Account created.':'Account created. Check your email to confirm sign-in.');if(data.session){setSession(data.session);setScreen('home')}};
 const createFarm=async()=>{if(!supabase||!session)return; if(farm)return;setBusy(true);const {data,error}=await supabase.from('farms').insert({owner_id:session.user.id,name:'My Farm',location:'Coimbatore, Tamil Nadu',area_acres:1}).select().single();setBusy(false);if(error)setMessage(error.message);else setFarm(data)};
 const addSupply=async()=>{if(!supabase||!session)return;const n=Number(qty);if(!n||n<=0){setMessage('Enter a valid quantity.');return}setBusy(true);const {error}=await supabase.from('farmplug_supply_listings').insert({farmer_name:name,crop,quantity_kg:n,quality,location:'Coimbatore, Tamil Nadu',created_by:session.user.id,status:'available'});setBusy(false);if(error)setMessage(error.message);else{setMessage('Supply published to the live marketplace.');await load(session.user.id)}};
 const signOut=async()=>{await supabase?.auth.signOut();setSession(null);setFarm(null);setCrops([]);setOrders([]);setScreen('login')};
 if(screen==='splash')return <div className="v2 splash"><div className="logoMark"><Leaf size={44}/></div><h1>FarmPlug <span>AI</span></h1><p>Right Market. Right Buyer. Right Time.</p><div className="loader"/></div>;
 if(screen==='login')return <div className="v2 auth"><div className="authLogo"><Leaf/></div><p className="kicker">FARMPLUG AI</p><h1>Right market.<br/>Right buyer. Right time.</h1><p className="muted">Secure sign-in for the shared FarmPlug platform.</p><label>Email</label><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="farmer@example.com"/><label>Password</label><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy} onClick={signIn}><LogIn size={18}/>{busy?'Signing in…':'Sign in'}<ArrowRight size={18}/></button><div className="divider"><span>NEW TO FARMPLUG?</span></div><button className="outlineBtn" onClick={()=>go('signup')}><UserPlus size={18}/> Create account</button><p className="muted authFoot">Supabase Auth • No passwords stored in the app</p></div>;
 if(screen==='signup')return <div className="v2 auth"><button className="backTop" onClick={()=>go('login')}><ChevronLeft/> Back</button><div className="authLogo"><UserPlus/></div><p className="kicker">CREATE ACCOUNT</p><h1>Join FarmPlug AI.</h1><label>Full name</label><input value={name==='Farmer'?'':name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><label>Email</label><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><label>Password</label><input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/><label>Confirm password</label><input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat password"/>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy} onClick={signUp}><UserPlus size={18}/>{busy?'Creating…':'Create account'}<ArrowRight size={18}/></button><p className="muted authFoot">Secure account creation through Supabase Auth.</p></div>;
 if(screen==='home')return <AppShell title="Home" go={go}><header className="homeHead"><div><small>GOOD MORNING</small><h2>Vanakkam, {name} 👋</h2></div><button className="avatar" onClick={()=>go('profile')}><User/></button></header><div className="weather"><div><small>YOUR FARM</small><b>{farm?.location||'Add your farm'}</b></div><div className="weatherRight"><span>🌱</span><b>{farm?.area_acres?`${farm.area_acres} acres`:'Not added'}</b><small>Farm area</small></div></div><div className="sectionTitle"><b>Decision center</b><span>Live account data</span></div><div className="cards2"><button onClick={()=>go('ai')}><div className="roundIcon"><Sparkles/></div><b>Ask FarmPlug AI</b><span>Forecasts & recommendations</span></button><button onClick={()=>go('farm')}><div className="roundIcon"><Wheat/></div><b>My Farm</b><span>{crops.length} crop records</span></button></div><div className="stats"><div><small>SUPPLY</small><strong>{supplies.length}</strong><span>Listings</span></div><div><small>DEMAND</small><strong>{requirements.length}</strong><span>Open requirements</span></div><div><small>ORDERS</small><strong>{orders.length}</strong><span>My orders</span></div></div><button className="listCard" onClick={()=>go('ai')}><span className="listIcon">📈</span><div><b>Market intelligence</b><p>{prices.length?`${prices.length} market records loaded.`:'No market data loaded yet.'}</p></div><ArrowRight/></button></AppShell>;
 if(screen==='ai')return <AppShell title="AI Intelligence" go={go}><div className="aiHero"><div className="bot"><Sparkles/></div><h1>Decision support,<br/>not guaranteed prices.</h1><p>FarmPlug reads stored market and forecast records. Account-specific answers should come from authenticated application data.</p></div><div className="sectionTitle"><b>Price intelligence</b><span>Prototype Forecast if marked</span></div>{forecasts.length?<div className="marketList">{forecasts.slice(0,6).map(f=><div className="marketCard" key={f.id}><div className="produceEmoji">📈</div><div><b>{f.crop} • {f.horizon_days}-day</b><p>₹{Number(f.predicted_price).toFixed(2)}/kg • {f.forecast_date}</p><small>{f.is_prototype?'Prototype Forecast':'Validated forecast'} • Model {f.model_version}</small></div></div>)}</div>:<div className="notice">No forecast has been generated for this account/environment yet. This screen will not invent a prediction.</div>}<div className="chips"><button onClick={()=>go('market')}>🛒 Find buyers</button><button onClick={()=>go('farm')}>🌱 View crops</button><button onClick={()=>go('orders')}>📦 Show orders</button></div></AppShell>;
 if(screen==='farm')return <AppShell title="My Farm" go={go}><div className="farmHero"><div><small>TOTAL AREA</small><strong>{farm?.area_acres||0} acres</strong></div><span>🌾</span></div>{!farm&&<button className="mainBtn" disabled={busy} onClick={createFarm}>{busy?'Creating…':'＋ Add my farm'}</button>}<div className="sectionTitle"><b>My crops</b><span>{crops.length} records</span></div>{crops.length?crops.map(c=><div className="cropRow" key={c.id}><span className="cropEmoji">🌱</span><div><b>{c.crop_name}</b><small>{c.available_quantity_kg||0} kg • {c.status}</small></div></div>):<div className="notice">No crop records yet. Add crops through the farm workflow.</div>}<button className="outlineBtn" onClick={()=>go('produce')}>Create supply listing <ArrowRight/></button></AppShell>;
 if(screen==='market')return <AppShell title="Market" go={go}><div className="search"><Search/><input placeholder="Search crop or market"/></div><div className="sectionTitle"><b>Open buyer demand</b><span>{requirements.length} requirements</span></div>{requirements.length?requirements.map(r=><div className="marketCard" key={r.id}><div className="produceEmoji">🍅</div><div><b>{r.crop} • {r.quantity_kg} kg</b><p>{r.quality} • {r.location}</p><small>{r.delivery_days} day delivery • {r.buyer_name}</small></div><span className="match">Open</span></div>):<div className="notice">No open buyer requirements are available from the live database.</div>}<div className="sectionTitle"><b>Market prices</b><span>Stored source data</span></div>{prices.slice(0,8).map(p=><div className="marketRow" key={p.id}><div><b>{p.crop}</b><div style={{fontSize:12}}>{p.price_date} • {p.source}{p.is_demo?' • DEMO DATA':''}</div></div><strong>₹{Number(p.price_per_kg).toFixed(2)}/kg</strong></div>)}<button className="mainBtn" onClick={()=>go('produce')}>Create supply <ArrowRight/></button></AppShell>;
 if(screen==='produce')return <AppShell title="Create Supply" go={go}><p className="muted">Publish your actual available produce. The record is saved to Supabase.</p><label>Crop</label><select value={crop} onChange={e=>setCrop(e.target.value)}><option>Tomato</option><option>Onion</option><option>Potato</option><option>Mango</option></select><label>Quantity (kg)</label><input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><label>Quality</label><select value={quality} onChange={e=>setQuality(e.target.value)}><option>Grade A</option><option>Grade B</option><option>Grade C</option></select><div className="location">📍 Coimbatore, Tamil Nadu</div>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy} onClick={addSupply}>{busy?'Publishing…':'Publish supply'}<Check/></button></AppShell>;
 if(screen==='orders')return <AppShell title="Orders" go={go}><div className="sectionTitle"><b>Live orders</b><span>{orders.length} records</span></div>{orders.length?orders.map(o=><button className="orderCard" key={o.id} onClick={()=>go('order')}><div className="orderTop"><b>Order #{String(o.id).slice(0,8)}</b><span className="status">{o.status}</span></div><div className="orderProduct">📦 <div><b>{o.quantity_kg} kg</b><p>{o.delivery_location}</p></div></div><div className="orderBottom"><span>{o.currency||'INR'}</span><b>{o.total_amount?`₹${o.total_amount}`:'Amount pending'}</b></div></button>):<div className="notice">No orders are linked to this account yet.</div>}</AppShell>;
 if(screen==='order')return <AppShell title="Order" go={go}><div className="notice">Order lifecycle is enforced by backend state. Select an order from the Orders screen to connect detailed delivery, payment and dispute data.</div></AppShell>;
 if(screen==='profile')return <AppShell title="Profile" go={go}><div className="profileHead"><div className="bigAvatar"><User/></div><h2>{name}</h2><p>{session?.user?.email}</p><span className="pill">{session?'Authenticated':'Signed out'}</span></div><div className="notice"><Leaf/><span>FarmPlug AI uses one authenticated backend across the web, PWA and Android experience.</span></div><button className="menuRow" onClick={()=>go('settings')}><span>⚙️</span><b>Settings & security</b><ChevronLeft className="rotate"/></button><button className="logout" onClick={signOut}><LogOut size={17}/> Log out</button></AppShell>;
 return <AppShell title="Settings" go={go}><div className="settingsGroup"><b>Security</b><div className="notice">Authentication: Supabase Auth<br/>Session persistence: enabled<br/>Passwords: never stored in FarmPlug database tables.</div></div><div className="settingsGroup"><b>Data honesty</b><div className="notice">Forecasts without a validated model are labelled Prototype Forecast. Simulated payments are labelled Payment Simulation.</div></div></AppShell>;
}
function AppShell({title,children,go}:{title:string,children:React.ReactNode,go:(s:Screen)=>void}){return <div className="v2 app"><header className="top"><button className="iconBtn" onClick={()=>go('home')}><ChevronLeft/></button><div><b>{title}</b><small>FarmPlug AI</small></div><button className="iconBtn" onClick={()=>go('profile')}><User/></button></header><main>{children}</main><nav className="bottomNav">{nav.map(([id,label,Icon])=><button key={id} className={title.toLowerCase().includes(label.toLowerCase().split(' ')[0])?'active':''} onClick={()=>go(id)}><Icon size={18}/><span>{label}</span></button>)}</nav></div>}
