'use client';
import './v2.css';
import { useEffect, useState } from 'react';
import { ArrowRight, ChevronLeft, Home, Leaf, LogIn, Package, Search, ShoppingBag, Sparkles, User, Wheat, UserPlus, LogOut, Bell, Check } from 'lucide-react';
import { supabase } from '../../lib/supabase';

type Screen='splash'|'onboarding-goal'|'onboarding-farm'|'onboarding-insight'|'login'|'signup'|'home'|'ai'|'farm'|'farm-add'|'market'|'produce'|'orders'|'order'|'profile'|'settings';
type Row=Record<string, any>;
const nav=[['home','Home',Home],['market','Market',ShoppingBag],['ai','AI Center',Sparkles],['orders','Orders',Package],['profile','Profile',User]] as const;

export default function FarmPlugFarmerApp(){
 const [screen,setScreen]=useState<Screen>('splash');
 const [session,setSession]=useState<any>(null); const [name,setName]=useState('Farmer');
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState('');
 const [goal,setGoal]=useState(''); const [onboardLocation,setOnboardLocation]=useState(''); const [onboardArea,setOnboardArea]=useState(''); const [onboardCrop,setOnboardCrop]=useState(''); const [onboardQty,setOnboardQty]=useState('');
 const [farm,setFarm]=useState<Row|null>(null); const [crops,setCrops]=useState<Row[]>([]); const [supplies,setSupplies]=useState<Row[]>([]); const [requirements,setRequirements]=useState<Row[]>([]); const [orders,setOrders]=useState<Row[]>([]); const [prices,setPrices]=useState<Row[]>([]); const [forecasts,setForecasts]=useState<Row[]>([]);
 const [crop,setCrop]=useState('Tomato'); const [qty,setQty]=useState('500'); const [quality,setQuality]=useState('Grade A'); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);

 useEffect(()=>{let active=true; const boot=async()=>{if(!supabase){setScreen('login');setMessage('Supabase is not configured in this deployment.');return} const {data}=await supabase.auth.getSession(); if(!active)return; if(data.session){setSession(data.session);await load(data.session.user.id);setScreen('home')}else{setScreen(localStorage.getItem('farmplug_onboarding_done')==='1'?'login':'onboarding-goal')}}; boot(); const {data:sub}=supabase.auth.onAuthStateChange(async(_e,s)=>{if(!active)return;if(s){setSession(s);await load(s.user.id);setScreen('home')}}); return()=>{active=false;sub.subscription.unsubscribe()};},[]);

 const load=async(uid:string)=>{if(!supabase)return; const [p,fp,f,c,s,r,o,mp,pf]=await Promise.all([
   supabase.from('profiles').select('email,farm_role').eq('id',uid).maybeSingle(),
   supabase.from('farmer_profiles').select('full_name,phone,location,verification_status').eq('id',uid).maybeSingle(),
   supabase.from('farms').select('*').eq('owner_id',uid).order('created_at',{ascending:true}).limit(1).maybeSingle(),
   supabase.from('crops').select('*').order('created_at',{ascending:false}),
   supabase.from('farmplug_supply_listings').select('*').eq('created_by',uid).order('created_at',{ascending:false}),
   supabase.from('farmplug_buyer_requirements').select('*').eq('status','open').order('created_at',{ascending:false}),
   supabase.from('farmplug_orders').select('*').or(`farmer_id.eq.${uid},buyer_id.eq.${uid}`).order('created_at',{ascending:false}),
   supabase.from('market_prices').select('*').order('price_date',{ascending:false}).limit(20),
   supabase.from('price_forecasts').select('*').order('forecast_date',{ascending:false}).limit(20)
 ]); setName((fp.data as any)?.full_name || (p.data as any)?.email?.split('@')[0] || 'Farmer'); setFarm(f.data); setCrops(c.data||[]); setSupplies(s.data||[]); setRequirements(r.data||[]); setOrders(o.data||[]); setPrices(mp.data||[]); setForecasts(pf.data||[]); };
 const go=(s:Screen)=>{setMessage('');setScreen(s)};
 const finishOnboarding=()=>{localStorage.setItem('farmplug_onboarding_done','1');go('login')};
 const signIn=async()=>{if(!supabase){setMessage('Supabase is not configured.');return}setBusy(true);const {error,data}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error){setBusy(false);setMessage(error.message);return}setSession(data.session);await load(data.user.id);setBusy(false);setScreen('home')};
 const signUp=async()=>{if(!supabase){setMessage('Supabase is not configured.');return}if(password.length<8||password!==confirm){setMessage('Use matching passwords with at least 8 characters.');return}setBusy(true);const {data,error}=await supabase.auth.signUp({email:email.trim(),password,data:{full_name:name.trim()||'Farmer',farm_role:'farmer'}});if(error){setBusy(false);setMessage(error.message);return}if(data.user){const profileName=name.trim()||'Farmer';await supabase.from('farmer_profiles').upsert({id:data.user.id,full_name:profileName,location:onboardLocation||null});await supabase.from('profiles').upsert({id:data.user.id,email:email.trim(),farm_role:'farmer'});if(onboardLocation&&Number(onboardArea)>0){await supabase.from('farms').insert({owner_id:data.user.id,name:'My Farm',location:onboardLocation,area_acres:Number(onboardArea)})}}setBusy(false);if(data.session){setSession(data.session);await load(data.user.id);setScreen('home')}else setMessage('Account created. Check your email if confirmation is required.');};
 const createFarm=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase||!session)return;const form=e.currentTarget as HTMLFormElement;const fd=new FormData(form);const farmName=String(fd.get('name')||'My Farm').trim()||'My Farm';const location=String(fd.get('location')||'').trim();const area=Number(fd.get('area'));if(!location||!area||area<=0){setMessage('Enter a location and valid area greater than 0 acres.');return}setBusy(true);const {error}=await supabase.from('farms').insert({owner_id:session.user.id,name:farmName,location,area_acres:area});if(error)setMessage(error.message);else{setMessage('Farm saved to Supabase.');await load(session.user.id);setScreen('farm')}setBusy(false)};
 const addSupply=async()=>{if(!supabase||!session)return;const n=Number(qty);if(!n||n<=0){setMessage('Enter a valid quantity.');return}setBusy(true);const {error}=await supabase.from('farmplug_supply_listings').insert({farmer_name:name,crop,quantity_kg:n,quality,location:farm?.location||'Not specified',created_by:session.user.id,status:'available'});setBusy(false);if(error)setMessage(error.message);else{setMessage('Supply published to the shared FarmPlug marketplace.');await load(session.user.id)}};
 const signOut=async()=>{await supabase?.auth.signOut();setSession(null);setFarm(null);setCrops([]);setOrders([]);setScreen('login')};

 if(screen==='splash')return <div className="v2 splash"><div className="logoMark"><Leaf size={44}/></div><h1>FarmPlug <span>AI</span></h1><p>From Farm Intelligence to the Right Market.</p><div className="loader"/></div>;
 if(screen==='onboarding-goal')return <Onboarding step="1" title="What do you want to achieve?" subtitle="Choose what matters most. FarmPlug AI will personalize your farmer experience." onSkip={finishOnboarding}><div className="goalGrid">{['Sell my harvest','Find better market prices','Find buyers','Get AI farming advice'].map(g=><button key={g} className={goal===g?'goal selected':'goal'} onClick={()=>setGoal(g)}><Sparkles size={20}/><b>{g}</b><span>FarmPlug AI support</span></button>)}</div><button className="mainBtn" disabled={!goal} onClick={()=>{localStorage.setItem('farmplug_goal',goal);go('onboarding-farm')}}>Continue <ArrowRight/></button></Onboarding>;
 if(screen==='onboarding-farm')return <Onboarding step="2" title="Tell us about your farm" subtitle="This information stays connected to your FarmPlug account. You can edit it later." onSkip={finishOnboarding}><label>Farm location</label><input value={onboardLocation} onChange={e=>setOnboardLocation(e.target.value)} placeholder="Coimbatore, Tamil Nadu"/><label>Land area (acres)</label><input type="number" min="0.01" value={onboardArea} onChange={e=>setOnboardArea(e.target.value)} placeholder="0.5"/><label>Main crop</label><input value={onboardCrop} onChange={e=>setOnboardCrop(e.target.value)} placeholder="Tomato"/><label>Expected harvest quantity (kg) <span className="muted">optional</span></label><input type="number" min="0" value={onboardQty} onChange={e=>setOnboardQty(e.target.value)} placeholder="2000"/><button className="mainBtn" disabled={!onboardLocation||!Number(onboardArea)||!onboardCrop} onClick={()=>{localStorage.setItem('farmplug_onboard_location',onboardLocation);localStorage.setItem('farmplug_onboard_area',onboardArea);localStorage.setItem('farmplug_onboard_crop',onboardCrop);localStorage.setItem('farmplug_onboard_qty',onboardQty);go('onboarding-insight')}}>Continue <ArrowRight/></button></Onboarding>;
 if(screen==='onboarding-insight')return <Onboarding step="3" title="Your first FarmPlug AI insight" subtitle="A useful starting point based on your inputs. This is not a live market prediction." onSkip={finishOnboarding}><div className="aiHero"><div className="bot"><Sparkles/></div><h1>{onboardCrop||'Your crop'}</h1><p>{onboardQty?`${onboardQty} kg planned for harvest in ${onboardLocation}.`:`Your crop plan is saved locally until you sign in.`}</p></div><div className="notice"><b>Next best action</b><p>Sign in to connect your farm to Supabase and unlock market, buyer and AI decision data.</p></div><button className="mainBtn" onClick={finishOnboarding}>See My Farm Dashboard <ArrowRight/></button><button className="outlineBtn" onClick={finishOnboarding}>Skip for now</button></Onboarding>;
 if(screen==='login')return <div className="v2 auth"><div className="authLogo"><Leaf/></div><p className="kicker">FARMPLUG AI</p><h1>Welcome back.<br/>Grow with better decisions.</h1><p className="muted">One account for the Android app and FarmPlug web platform.</p><label>Email</label><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="farmer@example.com"/><label>Password</label><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy} onClick={signIn}><LogIn size={18}/>{busy?'Signing in…':'Sign in'}<ArrowRight/></button><div className="divider"><span>NEW TO FARMPLUG?</span></div><button className="outlineBtn" onClick={()=>go('signup')}><UserPlus size={18}/> Create farmer account</button><p className="muted authFoot">Supabase Auth • Your password is never stored in FarmPlug tables.</p></div>;
 if(screen==='signup')return <div className="v2 auth"><button className="backTop" onClick={()=>go('login')}><ChevronLeft/> Back</button><div className="authLogo"><UserPlus/></div><p className="kicker">CREATE ACCOUNT</p><h1>Join FarmPlug AI.</h1><label>Full name</label><input value={name==='Farmer'?'':name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><label>Email</label><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><label>Password</label><input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/><label>Confirm password</label><input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat password"/>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy} onClick={signUp}><UserPlus size={18}/>{busy?'Creating…':'Create account'}<ArrowRight/></button></div>;
 if(screen==='home')return <AppShell title="Home" go={go}><header className="homeHead"><div><small>GOOD MORNING</small><h2>Vanakkam, {name} 👋</h2></div><button className="avatar" onClick={()=>go('profile')}><User/></button></header><div className="weather"><div><small>YOUR FARM</small><b>{farm?.location||'Add your farm'}</b></div><div className="weatherRight"><span>🌱</span><b>{farm?.area_acres?`${farm.area_acres} acres`:'Not added'}</b><small>Farm area</small></div></div><div className="sectionTitle"><b>Your Next Best Action</b><span>Shared backend</span></div><button className="listCard" onClick={()=>go('ai')}><span className="listIcon">✨</span><div><b>Analyze your harvest</b><p>Use FarmPlug AI to review market signals and buyer opportunities.</p></div><ArrowRight/></button><div className="cards2"><button onClick={()=>go('farm')}><div className="roundIcon"><Wheat/></div><b>My Farm</b><span>{crops.length} crop records</span></button><button onClick={()=>go('market')}><div className="roundIcon"><ShoppingBag/></div><b>Find Buyers</b><span>{requirements.length} open requirements</span></button></div><div className="stats"><div><small>SUPPLY</small><strong>{supplies.length}</strong><span>Listings</span></div><div><small>DEMAND</small><strong>{requirements.length}</strong><span>Requirements</span></div><div><small>ORDERS</small><strong>{orders.length}</strong><span>Orders</span></div></div><div className="notice">{prices.length?`${prices.length} stored market records are available.`:'No market data is available yet. FarmPlug will not invent live prices.'}</div></AppShell>;
 if(screen==='farm')return <AppShell title="My Farm" go={go}><div className="farmHero"><div><small>TOTAL AREA</small><strong>{farm?.area_acres||0} acres</strong></div><span>🌾</span></div>{farm?<div className="notice"><b>{farm.name}</b><p>{farm.location}</p><p>Your farm record is stored in Supabase and can be shared across FarmPlug web and Android.</p></div>:<div className="notice">No farm yet. Add your first farm to start your farmer profile.</div>}<button className="mainBtn" onClick={()=>go('farm-add')}><Wheat/> {farm?'Add another farm':'Add my farm'} <ArrowRight/></button><div className="sectionTitle"><b>My crops</b><span>{crops.length} records</span></div>{crops.length?crops.map(c=><div className="cropRow" key={c.id}><span className="cropEmoji">🌱</span><div><b>{c.crop_name}</b><small>{c.available_quantity_kg||0} kg • {c.status}</small></div></div>):<div className="notice">No crop records yet. Crop/harvest management is the next implementation phase.</div>}<button className="outlineBtn" onClick={()=>go('produce')}>Create supply listing <ArrowRight/></button></AppShell>;
 if(screen==='farm-add')return <AppShell title="Add Farm" go={go}><form onSubmit={createFarm}><p className="muted">Create a real farm record under your authenticated Supabase user.</p><label>Farm name</label><input name="name" defaultValue="My Farm"/><label>Location</label><input name="location" placeholder="Coimbatore, Tamil Nadu" required/><label>Area (acres)</label><input name="area" type="number" min="0.01" step="0.01" placeholder="0.5" required/>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy} type="submit">{busy?'Saving…':'Save Farm'} <Check/></button></form></AppShell>;
 if(screen==='ai')return <AppShell title="AI Center" go={go}><div className="aiHero"><div className="bot"><Sparkles/></div><h1>AI Decision Center</h1><p>FarmPlug uses stored backend data. Prototype forecasts are labelled clearly; this screen never pretends mock data is live.</p></div><div className="sectionTitle"><b>Price intelligence</b><span>Stored records</span></div>{forecasts.length?forecasts.slice(0,6).map(f=><div className="marketCard" key={f.id}><div className="produceEmoji">📈</div><div><b>{f.crop} • {f.horizon_days}-day</b><p>₹{Number(f.predicted_price).toFixed(2)}/kg • {f.forecast_date}</p><small>{f.is_prototype?'Prototype Forecast':'Validated forecast'} • Model {f.model_version}</small></div></div>):<div className="notice">No forecast has been generated yet. Add harvest data and connect a validated model before presenting a prediction.</div>}<div className="chips"><button onClick={()=>go('market')}>🛒 Find buyers</button><button onClick={()=>go('farm')}>🌱 View my farm</button><button onClick={()=>go('orders')}>📦 Show orders</button></div></AppShell>;
 if(screen==='market')return <AppShell title="Market" go={go}><div className="search"><Search/><input placeholder="Search crop or market"/></div><div className="sectionTitle"><b>Open buyer demand</b><span>{requirements.length} requirements</span></div>{requirements.length?requirements.map(r=><div className="marketCard" key={r.id}><div className="produceEmoji">🍅</div><div><b>{r.crop} • {r.quantity_kg} kg</b><p>{r.quality} • {r.location}</p><small>{r.delivery_days} day delivery • {r.buyer_name}</small></div><span className="match">Open</span></div>):<div className="notice">No open buyer requirements are available from the live database.</div>}<div className="sectionTitle"><b>Market prices</b><span>Stored source data</span></div>{prices.slice(0,8).map(p=><div className="marketRow" key={p.id}><div><b>{p.crop}</b><div style={{fontSize:12}}>{p.price_date} • {p.source}{p.is_demo?' • DEMO DATA':''}</div></div><strong>₹{Number(p.price_per_kg).toFixed(2)}/kg</strong></div>)}<button className="mainBtn" onClick={()=>go('produce')}>Create supply <ArrowRight/></button></AppShell>;
 if(screen==='produce')return <AppShell title="List Produce" go={go}><p className="muted">Publish actual available produce. This creates a shared backend listing.</p><label>Crop</label><select value={crop} onChange={e=>setCrop(e.target.value)}><option>Tomato</option><option>Onion</option><option>Potato</option><option>Mango</option></select><label>Quantity (kg)</label><input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><label>Quality</label><select value={quality} onChange={e=>setQuality(e.target.value)}><option>Grade A</option><option>Grade B</option><option>Grade C</option></select><div className="location">📍 {farm?.location||'Add a farm first'}</div>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy} onClick={addSupply}>{busy?'Publishing…':'Publish produce'}<Check/></button></AppShell>;
 if(screen==='orders')return <AppShell title="Orders" go={go}><div className="sectionTitle"><b>Live orders</b><span>{orders.length} records</span></div>{orders.length?orders.map(o=><button className="orderCard" key={o.id} onClick={()=>go('order')}><div className="orderTop"><b>Order #{String(o.id).slice(0,8)}</b><span className="status">{o.status}</span></div><div className="orderProduct">📦 <div><b>{o.quantity_kg} kg</b><p>{o.delivery_location||'Delivery location pending'}</p></div></div><div className="orderBottom"><span>{o.currency||'INR'}</span><b>{o.total_amount?`₹${o.total_amount}`:'Amount pending'}</b></div></button>):<div className="notice">No orders are linked to this account yet.</div>}</AppShell>;
 if(screen==='order')return <AppShell title="Order" go={go}><div className="notice"><b>Order lifecycle</b><p>This order is controlled by the FarmPlug backend state machine. Delivery, payment and notification details will be expanded in the next implementation phase.</p></div></AppShell>;
 if(screen==='profile')return <AppShell title="Profile" go={go}><div className="profileHead"><div className="bigAvatar"><User/></div><h2>{name}</h2><p>{session?.user?.email}</p><span className="pill">Authenticated farmer</span></div><div className="notice"><Leaf/><span>One authenticated account is shared across FarmPlug Android and web experiences.</span></div><button className="menuRow" onClick={()=>go('farm')}><Wheat/><b>My Farm</b><ChevronLeft className="rotate"/></button><button className="menuRow" onClick={()=>go('settings')}><span>⚙️</span><b>Settings & security</b><ChevronLeft className="rotate"/></button><button className="logout" onClick={signOut}><LogOut size={17}/> Log out</button></AppShell>;
 return <AppShell title="Settings" go={go}><div className="settingsGroup"><b>Security</b><div className="notice">Authentication: Supabase Auth<br/>Session persistence: enabled<br/>Passwords: never stored in FarmPlug database tables.</div></div><div className="settingsGroup"><b>Data honesty</b><div className="notice">Prototype forecasts are labelled. No live GPS, payment or market feed is claimed without a configured provider.</div></div></AppShell>;
}

function Onboarding({step,title,subtitle,children,onSkip}:{step:string,title:string,subtitle:string,children:React.ReactNode,onSkip:()=>void}){return <div className="v2 auth"><div className="kicker">STEP {step} OF 3</div><h1>{title}</h1><p className="muted">{subtitle}</p><div className="progress"><span style={{width:`${Number(step)/3*100}%`}}/></div>{children}<button className="textBtn" onClick={onSkip}>Skip for now</button></div>}
function AppShell({title,children,go}:{title:string,children:React.ReactNode,go:(s:Screen)=>void}){return <div className="v2 app"><header className="top"><button className="iconBtn" onClick={()=>go('home')} aria-label="Back to home"><ChevronLeft/></button><div><b>{title}</b><small>FarmPlug AI</small></div><button className="iconBtn" onClick={()=>go('profile')} aria-label="Profile"><User/></button></header><main>{children}</main><nav className="bottomNav" aria-label="Farmer navigation">{nav.map(([id,label,Icon])=><button key={id} className={title.toLowerCase().includes(label.toLowerCase().split(' ')[0])?'active':''} onClick={()=>go(id)}><Icon size={18}/><span>{label}</span></button>)}</nav></div>}
