'use client';
import './v2.css';
import { useEffect, useState } from 'react';
import { ArrowRight, Bell, Check, ChevronLeft, Home, Leaf, MapPin, Package, Search, ShoppingBag, Sparkles, User, Wheat, LogIn, UserPlus, Eye, EyeOff } from 'lucide-react';

type Screen='splash'|'login'|'signup'|'home'|'ai'|'farm'|'crop'|'market'|'produce'|'orders'|'order'|'notifications'|'profile'|'settings';
const nav=[{id:'home' as Screen,label:'Home',icon:Home},{id:'farm' as Screen,label:'My Farm',icon:Wheat},{id:'market' as Screen,label:'Market',icon:ShoppingBag},{id:'orders' as Screen,label:'Orders',icon:Package},{id:'profile' as Screen,label:'Profile',icon:User}];

export default function FarmPlugFarmerApp(){
 const [screen,setScreen]=useState<Screen>('splash');
 const [username,setUsername]=useState('');
 const [password,setPassword]=useState('');
 const [name,setName]=useState('');
 const [newUsername,setNewUsername]=useState('');
 const [newPassword,setNewPassword]=useState('');
 const [confirmPassword,setConfirmPassword]=useState('');
 const [showPassword,setShowPassword]=useState(false);
 const [message,setMessage]=useState('');
 useEffect(()=>{const t=setTimeout(()=>setScreen('login'),1200);return()=>clearTimeout(t)},[]);
 const go=(s:Screen)=>{setMessage('');setScreen(s)};
 const createAccount=()=>{if(!name.trim()||!newUsername.trim()||newPassword.length<6||newPassword!==confirmPassword){setMessage('Enter your name, a username, and matching passwords (6+ characters).');return} localStorage.setItem('farmplug_account',JSON.stringify({name,username:newUsername,password:newPassword}));setUsername(newUsername);setPassword(newPassword);setMessage('Account created. You can now sign in.');setScreen('login')};
 const signIn=()=>{const raw=localStorage.getItem('farmplug_account');if(!raw){setMessage('No account found. Create a new account first.');return}try{const a=JSON.parse(raw);if(a.username===username&&a.password===password){setName(a.name||'Farmer');setMessage('');setScreen('home')}else setMessage('Incorrect username or password.')}catch{setMessage('Please create your account again.')}};
 const back=()=>setScreen(screen==='signup'?'login':screen==='crop'?'farm':screen==='produce'?'market':screen==='order'?'orders':screen==='notifications'||screen==='settings'?'profile':'home');
 if(screen==='splash')return <div className="v2 splash"><div className="logoMark"><Leaf size={44}/></div><h1>FarmPlug <span>AI</span></h1><p>From Farm Intelligence to the Right Market.</p><div className="loader"/></div>;
 if(screen==='login')return <div className="v2 auth"><div className="authLogo"><Leaf/></div><p className="kicker">FARMER / FPO</p><h1>Farm intelligence<br/>in your pocket.</h1><p className="muted">Sign in with your FarmPlug username and password to manage your farm, discover demand and connect with buyers.</p><label>Username</label><input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter username"/><label>Password</label><div className="passwordField"><input autoComplete="current-password" type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password"/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label="Show password">{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" onClick={signIn}><LogIn size={18}/> Sign in <ArrowRight size={18}/></button><div className="divider"><span>NEW TO FARMPLUG?</span></div><button className="outlineBtn" onClick={()=>go('signup')}><UserPlus size={18}/> Create new account</button><p className="muted authFoot">Farmer / FPO account • Secure sign-in</p></div>;
 if(screen==='signup')return <div className="v2 auth"><button className="backTop" onClick={back}><ChevronLeft/> Back to sign in</button><div className="authLogo"><UserPlus/></div><p className="kicker">CREATE ACCOUNT</p><h1>Join FarmPlug<br/>as a Farmer / FPO.</h1><p className="muted">Create one account for your farm, marketplace activity, AI guidance and orders.</p><label>Full name</label><input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your name"/><label>Username</label><input autoComplete="username" value={newUsername} onChange={e=>setNewUsername(e.target.value)} placeholder="Choose a username"/><label>Password</label><div className="passwordField"><input autoComplete="new-password" type={showPassword?'text':'password'} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="At least 6 characters"/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label="Show password">{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><label>Confirm password</label><input autoComplete="new-password" type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Re-enter password"/>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" onClick={createAccount}><UserPlus size={18}/> Create account <ArrowRight size={18}/></button><p className="muted authFoot">Demo account storage is local to this prototype. Connect shared backend authentication before production use.</p></div>;
 if(screen==='home')return <div className="v2 app"><header className="homeHead"><div><small>GOOD MORNING</small><h2>Vanakkam, {name||'Farmer'} 👋</h2></div><button className="avatar" onClick={()=>go('profile')}><User/></button></header><div className="weather"><div><small>YOUR FARM</small><b>Coimbatore, Tamil Nadu</b></div><div className="weatherRight"><span>🌱</span><b>My Farm</b><small>View details</small></div></div><div className="sectionTitle"><b>Today</b><span>Farm overview</span></div><div className="cards2"><button onClick={()=>go('ai')}><div className="roundIcon"><Sparkles/></div><b>Ask FarmPlug AI</b><span>Get crop & market advice</span></button><button onClick={()=>go('farm')}><div className="roundIcon"><Wheat/></div><b>My Farm</b><span>3 crops • 4.2 acres</span></button></div><div className="sectionTitle"><b>Farm overview</b></div><div className="stats"><div><small>LISTINGS</small><strong>4</strong><span>Active</span></div><div><small>MATCHES</small><strong>8</strong><span>Buyer demand</span></div><div><small>ORDERS</small><strong>2</strong><span>In progress</span></div></div><div className="sectionTitle"><b>FarmPlug Intelligence</b></div><button className="listCard" onClick={()=>go('ai')}><span className="listIcon">📈</span><div><b>Check your market signal</b><p>Review demand, selling-window and buyer matches.</p></div><ArrowRight/></button><BottomNav screen={screen} go={go}/></div>;
 if(screen==='ai')return <div className="v2 app">{header('AI Intelligence','FarmPlug Intelligence')}<div className="aiHero"><div className="bot"><Sparkles/></div><h1>What can I help<br/>you with today?</h1><p>Ask about crops, markets, selling windows or farm planning. Review AI guidance before acting.</p></div><div className="chips"><button>🌱 Is my crop healthy?</button><button>📈 When should I sell?</button><button>💧 How much should I water?</button><button>🛒 Find buyers for tomato</button></div><div className="chatInput"><input placeholder="Ask FarmPlug AI..."/><button><ArrowRight/></button></div><BottomNav screen={screen} go={go}/></div>;
 if(screen==='farm')return <div className="v2 app">{header('My Farm','Coimbatore, Tamil Nadu')}<div className="farmHero"><div><small>TOTAL AREA</small><strong>4.2 acres</strong></div><span>🌾</span></div><div className="sectionTitle"><b>My crops</b><button onClick={()=>go('crop')}>View details</button></div>{[['Tomato','2.0 acres','Healthy','🍅'],['Onion','1.2 acres','Growing','🧅'],['Coconut','1.0 acre','Healthy','🥥']].map(x=><button className="cropRow" key={x[0]} onClick={()=>go('crop')}><span className="cropEmoji">{x[3]}</span><div><b>{x[0]}</b><small>{x[1]} • {x[2]}</small></div><ChevronLeft className="rotate"/></button>)}<button className="addBtn">+ Add crop</button><BottomNav screen={screen} go={go}/></div>;
 if(screen==='crop')return <div className="v2 app">{header('Tomato','Crop health & insights')}<div className="cropHero"><span>🍅</span><div><small>HEALTH STATUS</small><h2>Healthy</h2><p>Good growth • review latest data</p></div></div><div className="metricGrid"><div><small>SOIL MOISTURE</small><b>68%</b><span>Good</span></div><div><small>HARVEST</small><b>12 days</b><span>Estimated</span></div><div><small>AI HEALTH</small><b>92%</b><span>Insight</span></div><div><small>DEMAND</small><b>High</b><span>Market signal</span></div></div><div className="advice"><Sparkles/><div><b>FarmPlug recommendation</b><p>Demand is strong. Review buyer requirements and prepare your harvest plan.</p><small>Prototype insight — confirm with current farm data.</small></div></div><button className="mainBtn" onClick={()=>go('market')}>Find matching buyers <ArrowRight/></button></div>;
 if(screen==='market')return <div className="v2 app">{header('Market','Find the right demand')}<div className="search"><Search/><input placeholder="Search crop, buyer or location"/></div><div className="filters"><button>Tomato</button><button>Nearby</button><button>Grade A</button></div><div className="marketList">{[['Tomato','5,000 kg','Grade A','Chennai','Processor','98%'],['Tomato','2,000 kg','Grade A','Coimbatore','Buyer','91%'],['Onion','3,000 kg','Grade A','Salem','Exporter','89%']].map((x,i)=><button className="marketCard" key={i} onClick={()=>go('produce')}><div className="produceEmoji">{x[0]==='Tomato'?'🍅':'🧅'}</div><div><b>{x[0]} • {x[1]}</b><p>{x[2]} • {x[3]}</p><small>Buyer: {x[4]}</small></div><span className="match">{x[5]} match</span></button>)}</div><button className="mainBtn" onClick={()=>go('produce')}>List my produce <ArrowRight/></button><BottomNav screen={screen} go={go}/></div>;
 if(screen==='produce')return <div className="v2 app">{header('Add Produce','Create a supply listing')}<p className="muted">Tell buyers what you have available.</p><label>Crop</label><select><option>Tomato</option><option>Onion</option><option>Mango</option></select><label>Quantity (kg)</label><input type="number" defaultValue="500"/><label>Quality</label><select><option>Grade A</option><option>Grade B</option></select><label>Available / harvest date</label><input type="date"/><div className="location"><MapPin/><span>Coimbatore, Tamil Nadu</span></div><button className="mainBtn" onClick={()=>go('market')}>Publish produce <Check/></button></div>;
 if(screen==='orders')return <div className="v2 app">{header('Orders','Your buying & selling activity')}<div className="tabs"><button className="active">Active</button><button>Completed</button></div><button className="orderCard" onClick={()=>go('order')}><div className="orderTop"><b>Order #FP-1024</b><span className="status">Confirmed</span></div><div className="orderProduct">🍅 <div><b>Tomato • 1,000 kg</b><p>Buyer: GreenFresh Foods</p></div></div><div className="orderBottom"><span>Delivery in 2 days</span><b>₹42/kg</b></div></button><button className="orderCard" onClick={()=>go('order')}><div className="orderTop"><b>Order #FP-1018</b><span className="status">Pickup planned</span></div><div className="orderProduct">🧅 <div><b>Onion • 500 kg</b><p>Buyer: City Market</p></div></div><div className="orderBottom"><span>Pickup tomorrow</span><b>₹31/kg</b></div></button><BottomNav screen={screen} go={go}/></div>;
 if(screen==='order')return <div className="v2 app">{header('Order #FP-1024','GreenFresh Foods')}<div className="orderSummary"><span>🍅</span><div><b>Tomato</b><p>1,000 kg • Grade A</p></div><strong>₹42/kg</strong></div><div className="timeline">{[['Order confirmed','Buyer accepted your produce','✓'],['Pickup scheduled','6 Sept • 8:00 AM','✓'],['In transit','Coming next','3'],['Delivered','Pending','4']].map((x,i)=><div className="timeRow" key={x[0]}><span className={i<2?'done':''}>{x[2]}</span><div><b>{x[0]}</b><p>{x[1]}</p></div></div>)}</div><div className="notice"><MapPin/> Pickup: Coimbatore FPO collection point</div></div>;
 if(screen==='notifications')return <div className="v2 app">{header('Notifications')}<div className="notif"><span>📦</span><div><b>Order #FP-1024 confirmed</b><p>Your buyer accepted the listed produce.</p><small>Recent</small></div></div><div className="notif"><span>📈</span><div><b>Demand alert</b><p>Tomato demand is high in nearby markets.</p><small>Recent</small></div></div><div className="notif"><span>🤖</span><div><b>AI recommendation</b><p>Your crop insight is ready for review.</p><small>Recent</small></div></div></div>;
 if(screen==='profile')return <div className="v2 app">{header('Profile','Farmer / FPO account')}<div className="profileHead"><div className="bigAvatar"><User/></div><h2>{name||'Farmer'}</h2><p>Coimbatore, Tamil Nadu</p></div>{[['👨‍🌾','Personal details'],['🌾','Farm information'],['🔔','Notifications'],['⚙️','Settings']].map((x,i)=><button className="menuRow" key={x[1]} onClick={()=>i===2?go('notifications'):i===3?go('settings'):go('farm')}><span>{x[0]}</span><b>{x[1]}</b><ChevronLeft className="rotate"/></button>)}<div className="notice"><Leaf/><span>Farmer app: mobile-first operational workspace connected to the shared FarmPlug platform.</span></div><button className="logout" onClick={()=>{setUsername('');setPassword('');go('login')}}>Log out</button><BottomNav screen={screen} go={go}/></div>;
 return <div className="v2 app">{header('Settings')}<div className="settingsGroup"><b>Preferences</b><button><span>Language</span><span>English ›</span></button><button><span>Notifications</span><span className="toggle">ON</span></button></div><div className="settingsGroup"><b>Account</b><button><span>Privacy & security</span><span>›</span></button><button><span>Help & support</span><span>›</span></button></div></div>;
 function header(title:string,sub?:string){return <header className="top"><button className="iconBtn" onClick={back}><ChevronLeft/></button><div><b>{title}</b>{sub&&<small>{sub}</small>}</div><button className="iconBtn" onClick={()=>go('notifications')}><Bell/></button></header>}
}
function BottomNav({screen,go}:{screen:Screen;go:(s:Screen)=>void}){return <nav className="bottomNav">{nav.map(n=>{const I=n.icon;return <button key={n.id} className={screen===n.id?'selected':''} onClick={()=>go(n.id)}><I size={19}/><span>{n.label}</span></button>})}</nav>}
