'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowRight, ChevronLeft, Home, Leaf, LogIn, Package, Search, ShoppingBag, Sparkles, User, Wheat, UserPlus, LogOut, Check, CalendarDays } from 'lucide-react';
import { supabase } from '../../lib/supabase';

type Screen='splash'|'onboarding'|'login'|'signup'|'home'|'farm'|'add-farm'|'crop'|'add-crop'|'ai'|'market'|'buyer'|'produce'|'orders'|'profile'|'settings';
type Row=Record<string,any>;
const nav=[['home','Home',Home],['market','Market',ShoppingBag],['ai','AI Center',Sparkles],['orders','Orders',Package],['profile','Profile',User]] as const;

export default function FarmerAppPhase2(){
 const [screen,setScreen]=useState<Screen>('splash'); const [session,setSession]=useState<any>(null); const [name,setName]=useState('Farmer'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState('');
 const [farm,setFarm]=useState<Row|null>(null); const [farms,setFarms]=useState<Row[]>([]); const [crops,setCrops]=useState<Row[]>([]); const [requirements,setRequirements]=useState<Row[]>([]); const [prices,setPrices]=useState<Row[]>([]); const [forecasts,setForecasts]=useState<Row[]>([]); const [orders,setOrders]=useState<Row[]>([]); const [listings,setListings]=useState<Row[]>([]); const [matches,setMatches]=useState<Row[]>([]);
 const [selectedReq,setSelectedReq]=useState<Row|null>(null); const [selectedListing,setSelectedListing]=useState<Row|null>(null); const [crop,setCrop]=useState('Tomato'); const [qty,setQty]=useState('500'); const [quality,setQuality]=useState('Grade A'); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const go=(s:Screen)=>{setMessage('');setScreen(s)};
 const load=async(uid:string)=>{if(!supabase)return; const [p,fp,fs,cs,rs,ps,fr,os,ls]=await Promise.all([
  supabase.from('profiles').select('email,farm_role').eq('id',uid).maybeSingle(),supabase.from('farmer_profiles').select('full_name').eq('id',uid).maybeSingle(),supabase.from('farms').select('*').eq('owner_id',uid).order('created_at'),supabase.from('crops').select('*').order('created_at',{ascending:false}),supabase.from('farmplug_buyer_requirements').select('*').eq('status','open').order('created_at',{ascending:false}),supabase.from('market_prices').select('*').order('price_date',{ascending:false}).limit(30),supabase.from('price_forecasts').select('*').order('forecast_date',{ascending:false}).limit(20),supabase.from('farmplug_orders').select('*').or(`farmer_id.eq.${uid},buyer_id.eq.${uid}`).order('created_at',{ascending:false}),supabase.from('farmplug_supply_listings').select('*').eq('created_by',uid).order('created_at',{ascending:false})
 ]); setName(fp.data?.full_name||p.data?.email?.split('@')[0]||'Farmer'); setFarms(fs.data||[]); setFarm(fs.data?.[0]||null); setCrops(cs.data||[]); setRequirements(rs.data||[]); setPrices(ps.data||[]); setForecasts(fr.data||[]); setOrders(os.data||[]); setListings(ls.data||[]); };
 useEffect(()=>{let active=true; const boot=async()=>{if(!supabase){setScreen('login');return} const {data}=await supabase.auth.getSession(); if(!active)return; if(data.session){setSession(data.session);await load(data.session.user.id);setScreen('home')}else setScreen(localStorage.getItem('farmplug_onboarding_done')?'login':'onboarding')}; boot(); const {data:sub}=supabase.auth.onAuthStateChange(async(_e,s)=>{if(!active)return;if(s){setSession(s);await load(s.user.id);setScreen('home')}}); return()=>{active=false;sub.subscription.unsubscribe()};},[]);
 const signIn=async()=>{if(!supabase)return;setBusy(true);const {data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)setMessage(error.message);else{setSession(data.session);await load(data.user.id);setScreen('home')}setBusy(false)};
 const signUp=async()=>{if(!supabase)return;if(password.length<8||password!==confirm){setMessage('Use matching passwords with at least 8 characters.');return}setBusy(true);const {data,error}=await supabase.auth.signUp({email:email.trim(),password,data:{full_name:name.trim()||'Farmer',farm_role:'farmer'}});if(error){setMessage(error.message);setBusy(false);return}if(data.user){await supabase.from('profiles').upsert({id:data.user.id,email:email.trim(),farm_role:'farmer'});await supabase.from('farmer_profiles').upsert({id:data.user.id,full_name:name.trim()||'Farmer'})}setBusy(false);if(data.session){setSession(data.session);await load(data.user.id);setScreen('home')}else setMessage('Account created. Check your email if confirmation is required.')};
 const createFarm=async(e:FormEvent)=>{e.preventDefault();if(!supabase||!session)return;const fd=new FormData(e.currentTarget as HTMLFormElement);const location=String(fd.get('location')||'').trim();const area=Number(fd.get('area'));if(!location||area<=0){setMessage('Enter a valid location and area.');return}setBusy(true);const {error}=await supabase.from('farms').insert({owner_id:session.user.id,name:String(fd.get('name')||'My Farm'),location,area_acres:area});setBusy(false);if(error)setMessage(error.message);else{await load(session.user.id);go('farm')}};
 const createCrop=async(e:FormEvent)=>{e.preventDefault();if(!supabase||!session||!farm){setMessage('Add a farm first.');return}const fd=new FormData(e.currentTarget as HTMLFormElement);const cropName=String(fd.get('crop')||'').trim();const q=Number(fd.get('quantity'));const area=Number(fd.get('area'));const harvest=String(fd.get('harvest')||'')||null;if(!cropName||q<0){setMessage('Enter crop and valid quantity.');return}setBusy(true);const {error}=await supabase.from('crops').insert({farm_id:farm.id,crop_name:cropName,area_acres:area||null,harvest_date:harvest,available_quantity_kg:q,quality_grade:String(fd.get('quality')||'Grade A'),status:'harvest_ready'});setBusy(false);if(error)setMessage(error.message);else{await load(session.user.id);go('crop')}};
 const createListing=async()=>{if(!supabase||!session||!farm)return;const n=Number(qty);if(n<=0){setMessage('Enter a valid quantity.');return}setBusy(true);const {data,error}=await supabase.from('farmplug_supply_listings').insert({farmer_name:name,crop,quantity_kg:n,quality,location:farm.location,created_by:session.user.id,status:'available'}).select().single();if(error){setMessage(error.message);setBusy(false);return}await load(session.user.id);setSelectedListing(data);const token=(await supabase.auth.getSession()).data.session?.access_token;if(token){const res=await fetch('/api/farmer/matches',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({listingId:data.id})});const json=await res.json();if(res.ok)setMatches(json.matches||[]);else setMessage(json.error||'Buyer matching failed.')}setBusy(false);go('market')};
 const analyze=async()=>{if(!supabase)return;setBusy(true);const res=await fetch('/api/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({crop,quantity_kg:Number(qty),location:farm?.location||'',quality,storage:'Ambient'})});const json=await res.json().catch(()=>({}));if(!res.ok)setMessage(json.error||'AI analysis unavailable.');else setMessage(JSON.stringify(json));setBusy(false)};
 const openBuyer=async(r:Row)=>{setSelectedReq(r);setMatches([]);if(listings.length){const listing=listings.find(l=>String(l.crop).toLowerCase()===String(r.crop).toLowerCase())||listings[0];if(listing&&supabase){const token=(await supabase.auth.getSession()).data.session?.access_token;const res=await fetch('/api/farmer/matches',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({listingId:listing.id})});const json=await res.json();if(res.ok)setMatches((json.matches||[]).filter((m:Row)=>m.requirement?.id===r.id));}}go('buyer')};
 const signOut=async()=>{await supabase?.auth.signOut();setSession(null);go('login')};
 if(screen==='splash')return <div className="v2 splash"><div className="logoMark"><Leaf size={44}/></div><h1>FarmPlug <span>AI</span></h1><p>From Farm Intelligence to the Right Market.</p><div className="loader"/></div>;
 if(screen==='onboarding')return <div className="v2 auth"><div className="authLogo"><Leaf/></div><p className="kicker">FARMER APP • PHASE 2</p><h1>Your farm to the right market.</h1><p className="muted">Create your account, add your farm and harvest, then use real stored market and buyer data.</p><div className="notice"><b>What you can do</b><p>Crop & harvest records • AI decision support • Buyer requirements • Transparent matching</p></div><button className="mainBtn" onClick={()=>{localStorage.setItem('farmplug_onboarding_done','1');go('login')}}>Get started <ArrowRight/></button></div>;
 if(screen==='login')return <Auth title="Welcome back." email={email} setEmail={setEmail} password={password} setPassword={setPassword} busy={busy} message={message} signIn={signIn} go={go}/>;
 if(screen==='signup')return <div className="v2 auth"><button className="backTop" onClick={()=>go('login')}><ChevronLeft/> Back</button><div className="authLogo"><UserPlus/></div><p className="kicker">CREATE FARMER ACCOUNT</p><h1>Join FarmPlug AI.</h1><label>Full name</label><input value={name==='Farmer'?'':name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/><label>Confirm password</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat password"/>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy} onClick={signUp}>{busy?'Creating…':'Create account'} <ArrowRight/></button></div>;
 if(screen==='home')return <Shell title="Home" go={go}><div className="homeHead"><div><small>GOOD MORNING</small><h2>Vanakkam, {name} 👋</h2></div><button className="avatar" onClick={()=>go('profile')}><User/></button></div><div className="weather"><div><small>YOUR FARM</small><b>{farm?.location||'Add your farm'}</b></div><div className="weatherRight"><span>🌱</span><b>{farm?.area_acres||0} acres</b><small>Farm area</small></div></div><div className="sectionTitle"><b>Your Next Best Action</b><span>Phase 2</span></div><button className="listCard" onClick={()=>go('crop')}><span className="listIcon">🌾</span><div><b>Add or review harvest</b><p>Crop data powers market intelligence and buyer matching.</p></div><ArrowRight/></button><div className="cards2"><button onClick={()=>go('farm')}><div className="roundIcon"><Wheat/></div><b>My Farm</b><span>{farms.length} farms</span></button><button onClick={()=>go('market')}><div className="roundIcon"><ShoppingBag/></div><b>Find Buyers</b><span>{requirements.length} open</span></button></div><div className="stats"><div><small>CROPS</small><strong>{crops.length}</strong><span>Records</span></div><div><small>BUYERS</small><strong>{requirements.length}</strong><span>Demand</span></div><div><small>ORDERS</small><strong>{orders.length}</strong><span>Orders</span></div></div></Shell>;
 if(screen==='farm')return <Shell title="My Farm" go={go}><div className="farmHero"><div><small>FARM AREA</small><strong>{farm?.area_acres||0} acres</strong></div><span>🌾</span></div>{farms.map(f=><div className="notice" key={f.id}><b>{f.name}</b><p>{f.location} • {f.area_acres} acres</p></div>)}{!farms.length&&<div className="notice">No farm record yet.</div>}<button className="mainBtn" onClick={()=>go('add-farm')}>Add farm <ArrowRight/></button><div className="sectionTitle"><b>Crop & harvest records</b><span>{crops.length}</span></div>{crops.map(c=><button className="marketCard" key={c.id} onClick={()=>go('crop')}><div className="produceEmoji">🌱</div><div><b>{c.crop_name}</b><p>{c.available_quantity_kg||0} kg • {c.quality_grade||'Grade not set'}</p><small>{c.harvest_date||'Harvest date not set'} • {c.status}</small></div></button>)}{!crops.length&&<div className="notice">Add your first crop/harvest.</div>}<button className="outlineBtn" onClick={()=>go('add-crop')}>Add crop / harvest <ArrowRight/></button></Shell>;
 if(screen==='add-farm')return <Shell title="Add Farm" go={go}><form onSubmit={createFarm}><label>Farm name</label><input name="name" defaultValue="My Farm"/><label>Location</label><input name="location" placeholder="Coimbatore, Tamil Nadu" required/><label>Area (acres)</label><input name="area" type="number" min="0.01" step="0.01" required/>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy}>{busy?'Saving…':'Save farm'} <Check/></button></form></Shell>;
 if(screen==='crop')return <Shell title="Crop & Harvest" go={go}><div className="aiHero"><div className="bot"><Wheat/></div><h1>Your harvest data</h1><p>Keep crop quantity, quality and harvest timing connected to your farm.</p></div>{crops.map(c=><div className="marketCard" key={c.id}><div className="produceEmoji">🌱</div><div><b>{c.crop_name}</b><p>{c.available_quantity_kg||0} kg • {c.quality_grade||'Grade not set'}</p><small>Harvest {c.harvest_date||'date pending'} • {c.status}</small></div></div>)}<button className="mainBtn" onClick={()=>go('add-crop')}>Add crop / harvest <ArrowRight/></button><button className="outlineBtn" onClick={()=>go('ai')}>Analyze with AI <Sparkles/></button></Shell>;
 if(screen==='add-crop')return <Shell title="Add Crop / Harvest" go={go}><form onSubmit={createCrop}><label>Crop</label><input name="crop" placeholder="Tomato" required/><label>Area (acres) <span className="muted">optional</span></label><input name="area" type="number" min="0" step="0.01"/><label>Available quantity (kg)</label><input name="quantity" type="number" min="0" required/><label>Quality</label><select name="quality" defaultValue="Grade A"><option>Grade A</option><option>Grade B</option><option>Grade C</option></select><label>Harvest date</label><input name="harvest" type="date"/><button className="mainBtn" disabled={busy}>{busy?'Saving…':'Save harvest'} <Check/></button></form></Shell>;
 if(screen==='ai')return <Shell title="AI Center" go={go}><div className="aiHero"><div className="bot"><Sparkles/></div><h1>AI Decision Center</h1><p>Use your crop/harvest context with the existing decision service. Results are shown exactly as returned and prototype status is not hidden.</p></div><label>Crop</label><input value={crop} onChange={e=>setCrop(e.target.value)}/><label>Quantity (kg)</label><input type="number" value={qty} onChange={e=>setQty(e.target.value)}/><label>Quality</label><select value={quality} onChange={e=>setQuality(e.target.value)}><option>Grade A</option><option>Grade B</option><option>Grade C</option></select>{message&&<div className="notice"><b>Decision service response</b><p>{message}</p></div>}<button className="mainBtn" disabled={busy} onClick={analyze}>{busy?'Analyzing…':'Analyze harvest'} <Sparkles/></button><div className="sectionTitle"><b>Stored forecasts</b><span>{forecasts.length}</span></div>{forecasts.slice(0,6).map(f=><div className="marketRow" key={f.id}><div><b>{f.crop}</b><div>{f.forecast_date} • {f.horizon_days} days</div></div><strong>₹{Number(f.predicted_price).toFixed(2)}/kg</strong></div>)}{!forecasts.length&&<div className="notice">No stored forecast is available.</div>}<button className="outlineBtn" onClick={()=>go('market')}>Find my best buyer <ArrowRight/></button></Shell>;
 if(screen==='market')return <Shell title="Market" go={go}><div className="search"><Search/><input placeholder="Search buyer or crop"/></div><div className="sectionTitle"><b>Buyer requirements</b><span>{requirements.length} open</span></div>{requirements.map(r=><button className="marketCard" key={r.id} onClick={()=>openBuyer(r)}><div className="produceEmoji">🍅</div><div><b>{r.crop} • {r.quantity_kg} kg</b><p>{r.quality||'Any quality'} • {r.location}</p><small>{r.delivery_days||'—'} day delivery • {r.buyer_name||'Verified buyer'}</small></div><span className="match">View</span></button>)}{!requirements.length&&<div className="notice">No open buyer requirements in the database.</div>}<div className="sectionTitle"><b>Market prices</b><span>{prices.length} stored</span></div>{prices.slice(0,8).map(p=><div className="marketRow" key={p.id}><div><b>{p.crop}</b><div>{p.price_date} • {p.source}{p.is_demo?' • DEMO':''}</div></div><strong>₹{Number(p.price_per_kg).toFixed(2)}/kg</strong></div>)}<button className="mainBtn" onClick={()=>go('produce')}>List my produce <ArrowRight/></button></Shell>;
 if(screen==='buyer')return <Shell title="Buyer Details" go={go}>{selectedReq&&<><div className="aiHero"><div className="bot"><ShoppingBag/></div><h1>{selectedReq.buyer_name||'Buyer requirement'}</h1><p>{selectedReq.crop} • Requirement {selectedReq.quantity_kg} kg</p></div><div className="notice"><b>Requirement</b><p>Quality: {selectedReq.quality||'Not specified'}<br/>Location: {selectedReq.location||'Not specified'}<br/>Delivery: {selectedReq.delivery_days||'Not specified'} days</p></div><div className="sectionTitle"><b>Match breakdown</b><span>Transparent scoring</span></div>{matches.length?matches.map(m=><div className="stats" key={m.id||m.buyer_id}><div><small>TOTAL</small><strong>{m.totalScore}%</strong><span>Match</span></div><div><small>CROP</small><strong>{m.cropScore}%</strong><span>Crop</span></div><div><small>QTY</small><strong>{m.quantityScore}%</strong><span>Quantity</span></div></div>):<div className="notice">No calculated match exists yet. Create a produce listing for this crop to calculate it.</div>}<button className="mainBtn" onClick={()=>go('produce')}>List produce for this buyer <ArrowRight/></button></>}</Shell>;
 if(screen==='produce')return <Shell title="List Produce" go={go}><p className="muted">Publish real available produce. After publishing, FarmPlug calculates transparent buyer matches.</p><label>Crop</label><input value={crop} onChange={e=>setCrop(e.target.value)}/><label>Quantity (kg)</label><input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><label>Quality</label><select value={quality} onChange={e=>setQuality(e.target.value)}><option>Grade A</option><option>Grade B</option><option>Grade C</option></select><div className="location">📍 {farm?.location||'Add a farm first'}</div>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy||!farm} onClick={createListing}>{busy?'Publishing & matching…':'Publish & find buyers'} <Check/></button></Shell>;
 if(screen==='orders')return <Shell title="Orders" go={go}><div className="sectionTitle"><b>My orders</b><span>{orders.length}</span></div>{orders.map(o=><div className="orderCard" key={o.id}><div className="orderTop"><b>Order #{String(o.id).slice(0,8)}</b><span className="status">{o.status}</span></div><div className="orderProduct">📦 <div><b>{o.quantity_kg} kg</b><p>{o.delivery_location||'Delivery pending'}</p></div></div></div>)}{!orders.length&&<div className="notice">No orders yet. Buyer matching and quote acceptance will create orders.</div>}</Shell>;
 if(screen==='profile')return <Shell title="Profile" go={go}><div className="profileHead"><div className="bigAvatar"><User/></div><h2>{name}</h2><p>{session?.user?.email}</p><span className="pill">Authenticated farmer</span></div><button className="menuRow" onClick={()=>go('farm')}><Wheat/><b>My Farm & Crops</b><ChevronLeft className="rotate"/></button><button className="menuRow" onClick={()=>go('settings')}><span>⚙️</span><b>Settings</b><ChevronLeft className="rotate"/></button><button className="logout" onClick={signOut}><LogOut size={17}/> Log out</button></Shell>;
 return <Shell title="Settings" go={go}><div className="notice"><b>Account</b><p>Supabase Auth session is used for this farmer account. Farm and crop records are scoped to the authenticated user.</p></div><div className="notice"><b>Data honesty</b><p>Market records show their source/demo flag. AI responses are not relabelled as scientifically validated when the backend marks them as prototype.</p></div></Shell>;
}
function Auth({title,email,setEmail,password,setPassword,busy,message,signIn,go}:{title:string,email:string,setEmail:(v:string)=>void,password:string,setPassword:(v:string)=>void,busy:boolean,message:string,signIn:()=>void,go:(s:Screen)=>void}){return <div className="v2 auth"><div className="authLogo"><Leaf/></div><p className="kicker">FARMPLUG AI</p><h1>{title}<br/>Grow with better decisions.</h1><p className="muted">One Supabase account across Farmer Android and FarmPlug web.</p><label>Email</label><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="farmer@example.com"/><label>Password</label><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/>{message&&<p className="formMessage">{message}</p>}<button className="mainBtn" disabled={busy} onClick={signIn}><LogIn size={18}/>{busy?'Signing in…':'Sign in'} <ArrowRight/></button><button className="outlineBtn" onClick={()=>go('signup')}><UserPlus/> Create farmer account</button></div>}
function Shell({title,children,go}:{title:string,children:React.ReactNode,go:(s:Screen)=>void}){return <div className="v2 app"><header className="top"><button className="iconBtn" onClick={()=>go('home')}><ChevronLeft/></button><div><b>{title}</b><small>FarmPlug AI</small></div><button className="iconBtn" onClick={()=>go('profile')}><User/></button></header><main>{children}</main><nav className="bottomNav">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>go(id)}><Icon size={18}/><span>{label}</span></button>)}</nav></div>}
