'use client';
import { useEffect, useState } from 'react';
import { CheckCircle2, ChevronLeft, MapPin, PackageCheck, Truck, Users, XCircle } from 'lucide-react';
import { supabase } from '../../lib/supabase';

type Row=Record<string,any>;
type Screen='home'|'groups'|'logistics'|'orders'|'done';

export default function FarmerAppPhase3(){
 const [screen,setScreen]=useState<Screen>('home'); const [uid,setUid]=useState(''); const [groups,setGroups]=useState<Row[]>([]); const [orders,setOrders]=useState<Row[]>([]); const [deliveries,setDeliveries]=useState<Row[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [selected,setSelected]=useState<Row|null>(null);
 const load=async(id:string)=>{setUid(id);const token=(await supabase?.auth.getSession())?.data.session?.access_token;if(!token)return;const r=await fetch('/api/farmer/phase3',{headers:{Authorization:`Bearer ${token}`}});const j=await r.json();if(r.ok){setGroups(j.groups||[]);setOrders(j.orders||[]);setDeliveries(j.deliveries||[])}else setMessage(j.error||'Unable to load Phase 3 data')};
 useEffect(()=>{supabase?.auth.getSession().then(({data})=>{if(data.session)load(data.session.user.id)});},[]);
 const join=async(g:Row)=>{if(!uid)return;const contribution=Number(prompt(`Contribution to ${g.crop||'this aggregation'} (kg):`));if(!contribution||contribution<=0)return;setBusy(true);const token=(await supabase.auth.getSession()).data.session?.access_token;const r=await fetch('/api/farmer/aggregation',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({groupId:g.id,contributionKg:contribution})});const j=await r.json();setMessage(r.ok?`Joined aggregation. Current quantity: ${j.currentQuantityKg} kg.`:(j.error||'Could not join'));await load(uid);setBusy(false)};
 const setupDelivery=async(o:Row)=>{setSelected(o);const pickup=prompt('Pickup address / farm location:');if(!pickup)return;setBusy(true);const token=(await supabase.auth.getSession()).data.session?.access_token;const r=await fetch('/api/farmer/deliveries',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({orderId:o.id,pickupAddress:pickup})});const j=await r.json();setMessage(r.ok?'Logistics saved. Delivery is ready for tracking.':(j.error||'Could not save logistics'));await load(uid);setBusy(false);setScreen('logistics')};
 const transition=async(o:Row,status:string)=>{setBusy(true);const token=(await supabase.auth.getSession()).data.session?.access_token;const r=await fetch('/api/farmer/order-status',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({orderId:o.id,status})});const j=await r.json();setMessage(r.ok?`Order updated to ${status}.`:(j.error||'Status update failed'));await load(uid);setBusy(false);if(status==='COMPLETED')setScreen('done')};
 return <div className="v2 appShell"><header className="appTop"><button onClick={()=>setScreen('home')}><ChevronLeft/> Farmer App</button><span>Phase 3</span></header><main className="appBody">
 {message&&<div className="notice"><b>Update</b><p>{message}</p></div>}
 {screen==='home'&&<><div className="aiHero"><div className="bot"><PackageCheck/></div><h1>From buyer match to completed sale.</h1><p>Join an aggregation when a buyer needs more produce, prepare logistics, track your order and complete the sale.</p></div><div className="cards2"><button onClick={()=>setScreen('groups')}><Users/><b>Aggregation</b><span>{groups.length} open groups</span></button><button onClick={()=>setScreen('orders')}><PackageCheck/><b>Orders</b><span>{orders.length} farmer orders</span></button></div><button className="listCard" onClick={()=>setScreen('logistics')}><Truck/><div><b>Logistics & tracking</b><p>Collection, pickup and delivery status.</p></div></button></>}
 {screen==='groups'&&<><h1>Supply Aggregation</h1><p className="muted">Join an eligible buyer aggregation and contribute only the quantity you choose.</p>{groups.map(g=><div className="marketCard" key={g.id}><Users/><div><b>{g.crop||'Produce aggregation'}</b><p>Target {g.target_quantity_kg||0} kg • Current {g.current_quantity_kg||0} kg</p><small>Status: {g.status} • Buyer: {g.buyer_id||'Matched buyer'}</small></div><button disabled={busy||g.status==='READY'} onClick={()=>join(g)}>Join</button></div>)}{!groups.length&&<div className="notice">No open aggregation groups are available yet.</div>}</>}
 {screen==='orders'&&<><h1>Order Tracking</h1>{orders.map(o=><div className="marketCard" key={o.id}><PackageCheck/><div><b>Order #{String(o.id).slice(0,8)}</b><p>{o.quantity_kg||o.total_quantity_kg||0} kg</p><small>Status: {o.status}</small></div>{o.status==='CONFIRMED'&&<button onClick={()=>transition(o,'AGGREGATING')}>Start</button>}{o.status==='AGGREGATING'&&<button onClick={()=>setupDelivery(o)}>Logistics</button>}{o.status==='PICKUP'&&<button onClick={()=>transition(o,'IN_TRANSIT')}>Picked up</button>}{o.status==='IN_TRANSIT'&&<button onClick={()=>transition(o,'DELIVERED')}>Delivered</button>}{o.status==='DELIVERED'&&<button onClick={()=>transition(o,'COMPLETED')}>Complete</button>}</div>)}{!orders.length&&<div className="notice">No orders yet. A confirmed buyer match will appear here.</div>}</>}
 {screen==='logistics'&&<><h1>Logistics</h1><div className="aiHero"><div className="bot"><MapPin/></div><h2>Pickup → Collection → Buyer</h2><p>Only backend-saved logistics are shown. No fake GPS or live ETA is claimed.</p></div>{deliveries.map(d=><div className="notice" key={d.id}><b><Truck/> {d.vehicle_number||'Vehicle pending'}</b><p>{d.pickup_address||'Pickup pending'} • {d.distance_km||'—'} km</p><small>Status: {d.status} • ETA: {d.eta||'Not set'}</small></div>)}{!deliveries.length&&<div className="notice">No delivery plan yet. Open an order and configure logistics.</div>}</>}
 {screen==='done'&&<div className="successScreen"><CheckCircle2 size={64}/><h1>Sale completed</h1><p>The order reached COMPLETED in the FarmPlug workflow.</p><button className="mainBtn" onClick={()=>setScreen('orders')}>View order history</button></div>}
 </main><nav className="bottomNav"><button onClick={()=>setScreen('home')}>Home</button><button onClick={()=>setScreen('groups')}>Aggregation</button><button onClick={()=>setScreen('logistics')}>Logistics</button><button onClick={()=>setScreen('orders')}>Orders</button></nav></div>;
}
