"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

interface Listing { id:string; created_by:string; farmer_name:string; crop:string; quantity_kg:number; quality:string; }

export default function FpoAggregatePage(){
 const [available,setAvailable]=useState<Listing[]>([]); const [selected,setSelected]=useState<Record<string,number>>({}); const [cropName,setCropName]=useState(""); const [loading,setLoading]=useState(true); const [creating,setCreating]=useState(false); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{load();},[]);
 async function load(){const s=createClient(); const {data:{user}}=await s.auth.getUser(); if(!user){setLoading(false);return;} const {data,error}=await s.from("farmplug_supply_listings").select("id, created_by, farmer_name, crop, quantity_kg, quality").eq("status","available").order("created_at",{ascending:false}); if(error)setError(error.message); setAvailable(data??[]); setLoading(false);}
 function toggle(l:Listing){setSelected(p=>{const n={...p}; if(n[l.id]!==undefined)delete n[l.id];else n[l.id]=l.quantity_kg; return n;});}
 async function createLot(){const ids=Object.keys(selected); if(!ids.length||!cropName.trim()){setError("Pick at least one listing and enter a crop name.");return;} setCreating(true);setError(null); const s=createClient(); const {data:{user}}=await s.auth.getUser(); if(!user){setCreating(false);return;} const {data:lot,error:e}=await s.from("aggregated_lots").insert({fpo_id:user.id,crop_name:cropName.trim(),status:"collecting"}).select("id").single(); if(e||!lot){setError(e?.message??"Couldn't create the lot.");setCreating(false);return;} const items=ids.map(id=>{const l=available.find(x=>x.id===id)!;return {lot_id:lot.id,listing_id:id,farmer_id:l.created_by,quantity_kg:selected[id]};}); const {error:ie}=await s.from("aggregated_lot_items").insert(items); if(ie)setError(ie.message);else{setSelected({});setCropName("");}setCreating(false);}
 if(loading)return <div className="p-6 text-gray-500">Loading member supply...</div>;
 return <div className="mx-auto max-w-2xl p-6"><h1 className="text-xl font-semibold text-gray-900">Aggregate supply</h1><p className="mt-1 text-sm text-gray-500">Select available farmer listings to pool into one lot.</p><input placeholder="Crop name for this lot" value={cropName} onChange={e=>setCropName(e.target.value)} className="mt-4 w-full rounded-md border border-gray-300 px-3 py-2"/><div className="mt-4 space-y-2">{available.length===0&&<p className="text-sm text-gray-400">No available listings.</p>}{available.map(l=><label key={l.id} className="flex items-center gap-3 rounded-md border border-gray-200 p-3"><input type="checkbox" checked={selected[l.id]!==undefined} onChange={()=>toggle(l)}/><div className="flex-1"><div className="text-sm font-medium text-gray-900">{l.crop} · {l.quantity_kg} kg</div><div className="text-xs text-gray-500">{l.farmer_name} · {l.quality}</div></div></label>)}</div>{error&&<p className="mt-3 text-sm text-red-600" role="alert">{error}</p>}<div className="mt-4 flex items-center justify-between"><span className="text-sm text-gray-600">Selected total: {Object.values(selected).reduce((a,b)=>a+b,0)} kg</span><button onClick={createLot} disabled={creating} className="rounded-md bg-green-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{creating?"Creating...":"Create pooled lot"}</button></div></div>;
}
