'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect,useState } from 'react';
import { Home,Sparkles,Store,Info,Menu,X,Users,Download,LayoutGrid,LogIn,LogOut } from 'lucide-react';
import { supabase } from '../../lib/supabase';

const items=[
 {href:'/',label:'Home',icon:Home},{href:'/platform',label:'Platform',icon:LayoutGrid},{href:'/decision-center',label:'AI Intelligence',icon:Sparkles},{href:'/marketplace',label:'Marketplace',icon:Store},{href:'/farmer',label:'Farmers / FPOs',icon:Users},{href:'/buyer',label:'For Buyers',icon:Store},{href:'/about',label:'About',icon:Info},{href:'/signin',label:'Sign In',icon:LogIn},{href:'/download',label:'Download App',icon:Download},
];
const appItems=[{href:'/',label:'Home',icon:Home},{href:'/decision-center',label:'AI',icon:Sparkles},{href:'/marketplace',label:'Market',icon:Store},{href:'/farmer',label:'Farmer',icon:Users},{href:'/about',label:'About',icon:Info}];
const logo=<img src="/icons/farmplug-icon.svg" alt="FarmPlug AI logo" width={40} height={40}/>;
export default function Sidebar(){const pathname=usePathname();const[open,setOpen]=useState(false);const[session,setSession]=useState(false);const isActive=(href:string)=>href==='/'?pathname==='/':pathname===href||pathname.startsWith(`${href}/`);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(!!data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(!!s));return()=>data.subscription.unsubscribe()},[]);
 async function signOut(){if(!supabase)return;await supabase.auth.signOut();setOpen(false);location.href='/signin'}
 const nav=()=> <nav className="sideNav" aria-label="FarmPlug navigation">{items.map(({href,label,icon:Icon})=><Link key={href} href={href} onClick={()=>setOpen(false)} className={isActive(href)?'sideItem active':'sideItem'}><Icon size={19} strokeWidth={isActive(href)?2.5:2}/><span>{href==='/signin'&&session?'Account':' '+label}</span></Link>)}{session&&<button className="sideItem" onClick={signOut} style={{border:0,background:'transparent',cursor:'pointer',font:'inherit',textAlign:'left'}}><LogOut size={19}/><span>Sign out</span></button>}</nav>;
 return <><button className="desktopMenuButton" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={22}/></button>{open&&<div className="sideOverlay" onClick={()=>setOpen(false)} aria-hidden="true"/>}<aside className={open?'desktopSidebar open':'desktopSidebar'} aria-label="Desktop navigation"><div className="sideBrand"><div className="sideLogo">{logo}</div><div><strong>FarmPlug AI</strong><small>Farm intelligence → market</small></div><button className="sideClose" onClick={()=>setOpen(false)} aria-label="Close navigation"><X size={21}/></button></div>{nav()}<div className="sideFooter">SIH 2026 · PS 26033<br/><span>Professional platform prototype</span></div></aside><button className="mobileMenuButton" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={22}/></button><aside className={open?'mobileSidebar open':'mobileSidebar'} aria-label="Mobile navigation"><div className="sideBrand"><div className="sideLogo">{logo}</div><div><strong>FarmPlug AI</strong><small>Platform</small></div><button className="sideClose" onClick={()=>setOpen(false)} aria-label="Close navigation"><X size={21}/></button></div>{nav()}<div className="sideFooter">SIH 2026 · PS 26033</div></aside><nav className="standaloneBottomNav" aria-label="App navigation">{appItems.map(({href,label,icon:Icon})=><Link key={href} href={href} className={isActive(href)?'bottomItem active':'bottomItem'}><Icon size={20} strokeWidth={isActive(href)?2.5:2}/><span>{label}</span></Link>)}</nav></>;
}
