"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Farm = { id:string; name:string; location:string; area_acres:number };
type Crop = { id:string; crop_name:string; variety:string|null; area_acres:number|null; harvest_date:string|null; available_quantity_kg:number|null; quality_grade:string|null; status:string|null };

export default function MyFarmPage(){
 const [farm,setFarm]=useState<Farm|null>(null),[crops,setCrops]=useState<Crop[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({name:"",location:"",area_acres:""});
 useEffect(()=>{load()},[]);
 async function load(){setLoading(true);setError(null);const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setError("Not signed in.");setLoading(false);return;}const {data:f,error:fe}=await s.from("farms").select("id,name,location,area_acres").eq("owner_id",user.id).maybeSingle();if(fe){setError("Couldn't load your farm profile.");setLoading(false);return;}setFarm(f);if(f){setForm({name:f.name??"",location:f.location??"",area_acres:f.area_acres?.toString()??""});const {data:c}=await s.from("crops").select("id,crop_name,variety,area_acres,harvest_date,available_quantity_kg,quality_grade,status").eq("farm_id",f.id).order("created_at",{ascending:false});setCrops(c??[])}else setEditing(true);setLoading(false)}
 async function save(){const name=form.name.trim(),location=form.location.trim(),area=Number(form.area_acres);if(!name||!location||!Number.isFinite(area)||area<=0){setError("Farm name, location and a positive area are required.");return}setSaving(true);setError(null);const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setError("Not signed in.");setSaving(false);return;}const payload={owner_id:user.id,name,location,area_acres:area};const {error:e}=farm?await s.from("farms").update(payload).eq("id",farm.id).eq("owner_id",user.id):await s.from("farms").insert(payload);if(e){setError("Couldn't save your farm profile.");setSaving(false);return;}setEditing(false);setSaving(false);load()}
 if(loading)return <div className="p-6 text-sm text-gray-500">Loading your farm...</div>;
 return <div className="mx-auto max-w-2xl p-6"><div className="flex items-center justify-between"><h1 className="text-xl font-semibold text-[#17211B]">My Farm</h1>{farm&&!editing&&<button onClick={()=>setEditing(true)} className="text-sm font-medium text-[#1B4332]">Edit</button>}</div>{error&&<p className="mt-3 text-sm text-[#B42318]" role="alert">{error}</p>}{editing?<div className="mt-4 space-y-3 rounded-xl border border-gray-200 bg-white p-4"><input placeholder="Farm name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"/><input placeholder="Location" value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"/><input placeholder="Area (acres)" type="number" min="0.01" step="0.01" value={form.area_acres} onChange={e=>setForm({...form,area_acres:e.target.value})} className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm"/><div className="flex justify-end gap-2">{farm&&<button onClick={()=>setEditing(false)} className="px-4 py-2 text-sm">Cancel</button>}<button disabled={saving||!form.name.trim()||!form.location.trim()||!(Number(form.area_acres)>0)} onClick={save} className="rounded-md bg-[#1B4332] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{saving?"Saving...":"Save farm"}</button></div></div>:farm&&<div className="mt-4 rounded-xl border border-gray-200 bg-white p-4"><p className="font-medium">{farm.name}</p><p className="mt-1 text-sm text-[#5F6B63]">{farm.location} · {farm.area_acres} acres</p></div>}{farm&&<div className="mt-6"><div className="flex items-center justify-between"><h2 className="font-semibold">Crops</h2><Link href="/dashboard/farmer/crops/new" className="text-sm font-medium text-[#1B4332]">+ Add Crop</Link></div>{crops.length===0?<div className="mt-3 rounded-xl border border-dashed p-6 text-center text-sm text-[#5F6B63]">No crops added yet.</div>:<div className="mt-3 space-y-2">{crops.map(c=><Link key={c.id} href={`/dashboard/farmer/crops/${c.id}`} className="flex items-center justify-between rounded-xl border border-gray-200 bg-white p-3"><div><p className="text-sm font-medium">{c.crop_name}{c.variety?` · ${c.variety}`:""}</p><p className="text-xs text-[#5F6B63]">{c.available_quantity_kg??0} kg · {c.quality_grade??"Grade not set"} · {c.harvest_date?`Harvest ${c.harvest_date}`:"Harvest not set"}</p></div><span className="text-xs text-[#5F6B63]">{c.status??"active"}</span></Link>)}</div>}</div>}</div>
}
