// File location: app/dashboard/farmer/decision-center/page.tsx
"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
interface Crop { id:string; crop_name:string; expected_harvest_date:string|null; health_status:string; }
interface Recommendation { id:string; title:string; reason:string; confidence:number; dataStatus:string; }
function buildRecommendations(crops:Crop[]):Recommendation[]{const recs:Recommendation[]=[];crops.forEach(crop=>{if(crop.health_status==="at_risk")recs.push({id:`health-${crop.id}`,title:`Review ${crop.crop_name} — marked at risk`,reason:"You logged this crop's health status as 'at risk'.",confidence:100,dataStatus:"Based on your own crop health entry"});if(crop.expected_harvest_date){const days=Math.ceil((new Date(crop.expected_harvest_date).getTime()-Date.now())/(1000*60*60*24));if(days>=0&&days<=14)recs.push({id:`harvest-${crop.id}`,title:`${crop.crop_name} harvest in ${days} day${days===1?"":"s"}`,reason:"Expected harvest date is within the next two weeks — consider listing produce soon.",confidence:90,dataStatus:"Calculated from your crop record"});}});if(recs.length===0)recs.push({id:"none",title:"No urgent actions right now",reason:"No crops are flagged at risk and no harvest dates fall within the next two weeks.",confidence:100,dataStatus:"Calculated from your crop records"});return recs;}
export default function DecisionCenterPage(){const[crops,setCrops]=useState<Crop[]>([]);const[dismissed,setDismissed]=useState<Set<string>>(new Set());const[loading,setLoading]=useState(true);useEffect(()=>{load();},[]);async function load(){const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return;}const{data}=await supabase.from("crops").select("id, crop_name, expected_harvest_date, health_status").eq("farmer_id",user.id);setCrops(data??[]);setLoading(false);}if(loading)return <div className="p-6 text-sm text-gray-500">Loading...</div>;const recommendations=buildRecommendations(crops).filter(r=>!dismissed.has(r.id));return <div className="mx-auto max-w-2xl p-6"><h1 className="text-xl font-semibold text-[#17211B]">Decision Center</h1><p className="mt-1 text-xs text-[#5F6B63]">Recommendations are calculated from the crop data you've entered — not a live AI model.</p><div className="mt-4 space-y-3">{recommendations.map(rec=><div key={rec.id} className="rounded-md border border-gray-200 p-4"><p className="text-sm font-medium text-[#17211B]">{rec.title}</p><p className="mt-1 text-xs text-[#5F6B63]">{rec.reason}</p><div className="mt-2 flex items-center justify-between text-xs text-[#5F6B63]"><span>Confidence: {rec.confidence}% · {rec.dataStatus}</span>{rec.id!=="none"&&<button onClick={()=>setDismissed(prev=>new Set(prev).add(rec.id))} className="font-medium text-[#1B4332] hover:underline">Dismiss</button>}</div></div>)}</div></div>;}
