import Link from 'next/link';
import { ArrowRight, CheckCircle2, Leaf, ScanLine, ShoppingBag, Truck, Wheat, Download } from 'lucide-react';

const capabilities=[
 ['Crop Health','Scan a crop image and review transparent prototype risk signals.','/crop-health',ScanLine],
 ['Farm Intelligence','Review crop-stage, weather and irrigation guidance.','/farm-intelligence',Wheat],
 ['Market Prices','Compare market opportunities and price-discovery signals.','/marketplace',ShoppingBag],
 ['Buyer & Logistics','Match supply to buyers and coordinate delivery.','/buyer',Truck],
] as const;
const journey=['Crop Scan','Risk Detection','Farm Decision','Harvest Planning','Price Discovery','Buyer Matching','Order','Logistics','Sale Completed'];

export default function Home(){return <main><nav className="nav"><div className="wrap navin"><Link className="brand" href="/"><span className="leaf"><Leaf size={20}/></span>FarmPlug AI</Link><div className="links"><Link href="/sih">SIH Journey</Link><Link href="/platform">Platform</Link><Link href="/about">About</Link><Link href="/download">Download App</Link></div><div className="actions"><Link className="btn secondary" href="/signin">Sign in</Link><Link className="btn primary" href="/download">Download App <Download size={16}/></Link></div></div></nav><section className="hero"><div className="wrap heroGrid"><div><span className="eyebrow"><Leaf size={14}/> SMART INDIA HACKATHON 2026 • SIH26131 + SIH26132</span><h1>From Farm Intelligence to the Right Market.</h1><p>Detect crop problems early. Make smarter farm decisions. Discover better prices, connect with buyers and coordinate logistics through one connected farmer-first platform.</p><div className="heroBtns"><Link className="btn primary" href="/crop-health">Scan Crop <ScanLine size={17}/></Link><Link className="btn secondary" href="/farm-intelligence">Explore Farm Intelligence <ArrowRight size={17}/></Link><Link className="btn secondary" href="/download">Download Android App <Download size={17}/></Link></div><div className="notice">SIH26131 + SIH26132: FarmPlug AI connects crop-health intelligence before harvest with market linkage and price discovery after harvest.</div></div><div className="flow"><b>One connected farmer journey</b>{journey.map((step,i)=><div className="flowStep" key={step}><span className="num">{String(i+1).padStart(2,'0')}</span><b>{step}</b></div>)}</div></div></section><section className="section"><div className="wrap"><span className="eyebrow">CORE CAPABILITIES</span><h2>Detect → Decide → Sell → Deliver</h2><p className="lead">The product is organized around the farmer's next best action rather than disconnected AI features.</p><div className="grid6">{capabilities.map(([title,desc,href,Icon])=><article className="card" key={title}><div className="icon"><Icon size={20}/></div><h3>{title}</h3><p>{desc}</p><Link className="btn secondary" style={{marginTop:16}} href={href}>Open <ArrowRight size={15}/></Link></article>)}</div></div></section><section className="section alt"><div className="wrap"><span className="eyebrow">PROTOTYPE INTEGRITY</span><h2>Transparent by design.</h2><div className="two"><div className="card"><CheckCircle2 size={22}/><h3>Crop Health</h3><p>The current crop screen is an image-assisted heuristic prototype, not a validated agricultural disease classifier.</p></div><div className="card"><CheckCircle2 size={22}/><h3>Market & Logistics</h3><p>Demo values and route suggestions remain explicitly labelled until connected to verified live data sources.</p></div></div></div></section><footer className="footer"><div className="wrap">FarmPlug AI • SIH26131 + SIH26132 • From Farm Intelligence to the Right Market.</div></footer></main>}
