'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, Bell, CheckCircle2, CloudRain, Droplets, ImagePlus, Leaf, Lock, MapPin, RefreshCw, Settings, ShieldCheck, ShoppingBag, Sun, Thermometer, Truck, Upload, User, XCircle } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Mode = 'crop-health' | 'farm-intelligence' | 'offers' | 'notifications' | 'settings';
const nav=[['/app-v2','Home'],['/crop-health','Crop Health'],['/farm-intelligence','Farm Intelligence'],['/offers','Offers'],['/notifications','Notifications'],['/settings','Settings']];

function Header({title,subtitle}:{title:string;subtitle:string}){return <><nav className="opNav">{nav.map(([href,label])=><Link href={href} key={href}>{label}</Link>)}</nav><header className="opHeader"><span className="eyebrow"><Leaf size={14}/> FARMPLUG AI</span><h1>{title}</h1><p className="muted">{subtitle}</p></header></>}
function State({kind,text,onRetry}:{kind:'loading'|'empty'|'error'|'success';text:string;onRetry?:()=>void}){return <div className={`opState ${kind}`}>{kind==='loading'&&<RefreshCw size={18}/>} {kind==='empty'&&<Leaf size={18}/>} {kind==='error'&&<XCircle size={18}/>} {kind==='success'&&<CheckCircle2 size={18}/>}<b>{text}</b>{kind==='error'&&onRetry&&<button className="btn secondary" onClick={onRetry}>Try again</button>}</div>}

export default function FarmPlugOperationalScreens({mode}:{mode:Mode}){
 if(mode==='crop-health') return <CropHealth/>;
 if(mode==='farm-intelligence') return <FarmIntelligence/>;
 if(mode==='offers') return <Offers/>;
 if(mode==='notifications') return <Notifications/>;
 return <SettingsScreen/>;
}

function CropHealth(){
 const [crop,setCrop]=useState('Tomato'); const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState(''); const [symptoms,setSymptoms]=useState<string[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState<{label:string;confidence:number;severity:string;reason:string;action:string}|null>(null);
 const toggle=(s:string)=>setSymptoms(x=>x.includes(s)?x.filter(v=>v!==s):[...x,s]);
 const analyze=async()=>{setError('');if(!file){setError('Upload a crop image first.');return}setBusy(true);setResult(null);try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const size=160;canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image processing unavailable.');ctx.drawImage(bitmap,0,0,size,size);const data=ctx.getImageData(0,0,size,size).data;let brown=0,green=0,total=0;for(let i=0;i<data.length;i+=4){const r=data[i],g=data[i+1],b=data[i+2];const max=Math.max(r,g,b),min=Math.min(r,g,b);if(max-min<18&&max<245&&max>25)continue;total++;if(g>r*1.08&&g>b*1.12)green++;if(r>g*1.15&&g>b*1.05)brown++}const brownRatio=brown/Math.max(total,1);const symptomBoost=symptoms.length*0.06;const raw=Math.min(.94,Math.max(.58,.62+brownRatio*.8+symptomBoost));const confidence=Math.round(raw*100);const hasSpots=symptoms.includes('Leaf spots')||brownRatio>.08;const label=crop==='Tomato'&&hasSpots?'Possible early blight / leaf-spot stress':symptoms.length?'Possible crop stress pattern':'No clear disease pattern detected';const severity=hasSpots&&confidence>80?'Moderate':hasSpots?'Low':'Low';const action=hasSpots?'Isolate affected leaves, avoid overhead irrigation, and confirm with a local agronomist before treatment.':'Continue monitoring and rescan a clear leaf image if symptoms appear.';setResult({label,confidence,severity,reason:`Prototype image heuristic: ${(brownRatio*100).toFixed(1)}% brown/spot-like pixels; ${symptoms.length} farmer-selected symptom(s).`,action})}catch{setError('The image could not be analyzed. Try a clear JPG/PNG leaf photo.')}finally{setBusy(false)}};
 return <main className="operationalPage"><div className="operationalWrap"><Header title="Crop Health AI" subtitle="Upload a crop image and review a transparent prototype health assessment."/><div className="opGrid"><section className="opCard"><h2><ImagePlus size={20}/> 1. Crop image</h2><select className="opInput" value={crop} onChange={e=>setCrop(e.target.value)}><option>Tomato</option><option>Onion</option><option>Potato</option><option>Mango</option><option>Rice</option></select><label className="opDrop" style={{display:'block',marginTop:12}}><Upload size={28}/><b>Upload leaf/crop image</b><span className="muted" style={{display:'block',fontSize:12}}>JPG or PNG • clear daylight image recommended</span><input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);setResult(null);if(f)setPreview(URL.createObjectURL(f))}}/>{preview&&<img className="opImage" src={preview} alt="Selected crop"/>}</label></section><section className="opCard"><h2><AlertTriangle size={20}/> 2. Symptoms</h2>{['Leaf spots','Yellowing','Wilting','Insect damage'].map(s=><label key={s} style={{display:'flex',gap:9,alignItems:'center',padding:'11px 0',borderBottom:'1px solid var(--line)'}}><input type="checkbox" checked={symptoms.includes(s)} onChange={()=>toggle(s)}/>{s}</label>)}<button className="btn primary" style={{width:'100%',marginTop:14}} onClick={analyze} disabled={busy}>{busy?'ANALYZING…':'ANALYZE CROP'} <ArrowRight size={16}/></button>{error&&<State kind="error" text={error}/>}</section></div>{busy&&<State kind="loading" text="Running the image heuristic…"/>}{!busy&&!result&&!error&&<State kind="empty" text="Upload an image and analyze it to see the assessment."/>}{result&&<section className="opCard" style={{marginTop:14}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'flex-start'}}><div><span className="opBadge">PROTOTYPE ASSESSMENT</span><h2 style={{marginTop:10}}>{result.label}</h2></div><strong style={{fontSize:24,color:'var(--green)'}}>{result.confidence}%</strong></div><div className="opGrid"><div className="opState success"><b>Confidence</b><p>{result.confidence}% heuristic score</p></div><div className="opState"><b>Severity</b><p>{result.severity}</p></div><div className="opState"><b>Symptoms / signal</b><p>{result.reason}</p></div><div className="opState"><b>Recommended next action</b><p>{result.action}</p></div></div><div className="notice">AI Demo Prediction — Prototype Demonstration. This is a simple image heuristic, not a validated disease diagnosis. Confirm important crop-health decisions with a qualified local agricultural expert.</div><div className="opActions"><button className="btn secondary" onClick={()=>{setResult(null);setFile(null);setPreview('')}}>Scan Again</button><Link className="btn primary" href="/farm-intelligence">View Recommendations</Link></div></section>}</div></main>
}

function FarmIntelligence(){return <main className="operationalPage"><div className="operationalWrap"><Header title="Farm Intelligence" subtitle="Weather, crop-stage risk and irrigation guidance in one practical view."/><div className="opGrid"><section className="opCard"><h2><Sun size={20}/> Weather</h2><div className="opList"><div className="opRow"><span><Thermometer size={16}/> Temperature</span><b>29°C</b></div><div className="opRow"><span><Droplets size={16}/> Humidity</span><b>72%</b></div><div className="opRow"><span><CloudRain size={16}/> Rainfall outlook</span><b>Moderate</b></div></div><div className="notice">Prototype weather values. Connect a live weather provider before production use.</div></section><section className="opCard"><h2><Leaf size={20}/> Crop-stage risk</h2><div className="opList"><div className="opRow"><span>Tomato · Flowering</span><span className="opBadge warn">MEDIUM RISK</span></div><div className="opRow"><span>Fungal disease risk</span><b>Monitor leaves</b></div><div className="opRow"><span>Heat stress</span><b>Low</b></div><div className="opRow"><span>Pest pressure</span><b>Watch</b></div></div></section><section className="opCard"><h2><Droplets size={20}/> Irrigation recommendation</h2><div className="opState success"><b>Review irrigation today</b><p>Check soil moisture before watering. If the topsoil is dry and no rainfall is expected, prefer an early-morning irrigation cycle.</p></div><div className="notice">Advisory only — not an automated irrigation command.</div></section><section className="opCard"><h2><AlertTriangle size={20}/> Action alerts</h2><div className="opList"><div className="opRow"><span>Crop Health</span><span className="opBadge">Scan affected leaves</span></div><div className="opRow"><span>Farm Alert</span><span className="opBadge warn">Review irrigation</span></div><div className="opRow"><span>Market Opportunity</span><span className="opBadge">Check tomato buyers</span></div></div></section></div></div></main>}

function Offers(){const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [rows,setRows]=useState<any[]>([]);const [filter,setFilter]=useState('All');const load=async()=>{setLoading(true);setError('');try{const {data:{session}}=await supabase!.auth.getSession();if(!session){setRows([]);return}const {data,error}=await supabase!.from('farmplug_orders').select('id,buyer_id,quantity_kg,unit_price,status,created_at,delivery_location').eq('farmer_id',session.user.id).order('created_at',{ascending:false});if(error)throw error;setRows(data||[])}catch(e){setError('Could not load live offers.');}finally{setLoading(false)}};useMemo(()=>{void load()},[]);const normalized=(s:string)=>s.toLowerCase().replaceAll('_',' ');const statuses=['Pending','Accepted','Rejected','Negotiating','Completed'];const visible=filter==='All'?rows:rows.filter(r=>normalized(String(r.status))===filter.toLowerCase());return <main className="operationalPage"><div className="operationalWrap"><Header title="Offers & Negotiation" subtitle="Track buyer offers through one clear lifecycle."/><div className="opNav">{['All',...statuses].map(x=><button className="btn secondary" key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div>{loading?<State kind="loading" text="Loading your offers…"/>:error?<State kind="error" text={error} onRetry={load}/>:rows.length===0?<State kind="empty" text="No live offers yet. Buyer quotes will appear here when they are created."/>:<div className="opList">{visible.map(r=><article className="opCard" key={r.id}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><h3>Buyer offer</h3><p className="muted">{Number(r.quantity_kg||0).toLocaleString()} kg · ₹{Number(r.unit_price||0).toLocaleString()}/kg</p><p className="muted"><MapPin size={14}/> {r.delivery_location||'Delivery location pending'}</p></div><span className={`opBadge ${normalized(r.status)==='rejected'?'error':normalized(r.status)==='negotiating'?'warn':''}`}>{normalized(r.status)}</span></div><div className="opActions"><button className="btn secondary">View offer</button><button className="btn primary">Open negotiation</button></div></article>)}</div>}<div className="notice">Negotiating is a first-class FarmPlug status. State changes must be performed by the authenticated order/quote API; this screen never invents an accepted offer.</div></div></main>}

function Notifications(){const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [items,setItems]=useState<any[]>([]);const categories=['Crop Health','Farm Alerts','Market Opportunities','Buyer Offers','Orders','Logistics'];const load=async()=>{setLoading(true);setError('');try{const {data:{session}}=await supabase!.auth.getSession();if(!session){setItems([]);return}const {data,error}=await supabase!.from('notifications').select('id,title,body,read_at,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(50);if(error)throw error;setItems(data||[])}catch{setError('Could not load notifications.')}finally{setLoading(false)}};useMemo(()=>{void load()},[]);return <main className="operationalPage"><div className="operationalWrap"><Header title="Notifications" subtitle="Actionable alerts for crop health, farm decisions, markets, buyers, orders and logistics."/><div className="opGrid">{categories.map(c=><section className="opCard" key={c}><h3>{c}</h3><p className="muted">Prioritize the next action related to {c.toLowerCase()}.</p></section>)}</div>{loading?<State kind="loading" text="Loading notifications…"/>:error?<State kind="error" text={error} onRetry={load}/>:items.length===0?<State kind="empty" text="You have no notifications yet."/>:<section className="opCard" style={{marginTop:14}}><div className="opList">{items.map(n=><article className="opRow" key={n.id}><div><b>{n.title}</b><p className="muted" style={{margin:'4px 0'}}>{n.body}</p><small className="muted">{new Date(n.created_at).toLocaleString()}</small></div>{n.read_at?<span className="opBadge">Read</span>:<span className="opBadge warn">New</span>}</article>)}</div></section>}</div></main>}

function SettingsScreen(){const [theme,setTheme]=useState<'light'|'dark'>(()=>typeof window==='undefined'?'light':(localStorage.getItem('farmplug_theme') as 'light'|'dark')||'light');const saveTheme=(v:'light'|'dark')=>{setTheme(v);localStorage.setItem('farmplug_theme',v);document.documentElement.dataset.theme=v};return <main className="operationalPage"><div className="operationalWrap"><Header title="Settings" subtitle="Account, preferences, security, support and FarmPlug information."/><div className="opGrid"><section className="opCard"><h2><User size={20}/> Account</h2><div className="opRow"><span>Profile</span><b>Manage account</b></div><div className="opRow"><span>Farm details</span><b>Manage farms</b></div></section><section className="opCard"><h2><Settings size={20}/> Preferences</h2><label className="opRow"><span>Language</span><select className="opInput" style={{width:150}}><option>English</option><option>Tamil</option></select></label><div className="opRow"><span>Theme</span><div className="opActions" style={{margin:0}}><button className="btn secondary" onClick={()=>saveTheme('light')} aria-pressed={theme==='light'}>Light</button><button className="btn secondary" onClick={()=>saveTheme('dark')} aria-pressed={theme==='dark'}>Dark</button></div></div></section><section className="opCard"><h2><Lock size={20}/> Security</h2><div className="opRow"><span>Password</span><b>Supabase Auth</b></div><div className="opRow"><span>Sessions</span><b>Review active sessions</b></div><div className="notice">Never share your password or secret API keys.</div></section><section className="opCard"><h2><ShieldCheck size={20}/> Support & About</h2><div className="opRow"><span>Help</span><b>Farmer support</b></div><div className="opRow"><span>Privacy</span><b>FarmPlug AI</b></div><div className="opRow"><span>Terms</span><b>Prototype platform</b></div></section></div><State kind="success" text="Settings are ready. Theme preference is stored on this device."/></div></main>}
