"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Building2, Leaf, ShoppingBasket } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Role="farmer"|"buyer"|"fpo";
const roles:{value:Role;label:string;description:string;icon:typeof Leaf}[]=[
 {value:"farmer",label:"Farmer",description:"Manage your farm, crops, health insights and selling opportunities.",icon:Leaf},
 {value:"buyer",label:"Buyer",description:"Source produce, manage requirements and connect with reliable supply.",icon:ShoppingBasket},
 {value:"fpo",label:"FPO / Aggregator",description:"Coordinate farmers, aggregate supply and manage collection and logistics.",icon:Building2},
];
export default function RoleSelectionPage(){const router=useRouter();const[selected,setSelected]=useState<Role|null>(null);const[error,setError]=useState("");const[saving,setSaving]=useState(false);async function submit(){if(!selected)return;setSaving(true);setError("");const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace("/signin");return}const{error}=await s.from("profiles").update({farm_role:selected}).eq("id",user.id);if(error){setError(error.message);setSaving(false);return}router.replace("/onboarding/complete-profile")}return <main className="min-h-screen bg-[#F7FAF7] px-4 py-8 text-[#172117] sm:px-6"><div className="mx-auto max-w-2xl"><div className="flex items-center gap-2 text-sm font-bold"><span className="grid size-9 place-items-center rounded-xl bg-[#EAF6ED] text-[#1E7A3D]"><Leaf size={19}/></span>FarmPlug AI</div><div className="mt-12"><p className="text-sm font-semibold text-[#2E9E4F]">Set up your workspace</p><h1 className="mt-2 text-4xl font-semibold tracking-tight sm:text-5xl">How will you use FarmPlug?</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#647064]">Choose the workspace that matches your work. You can then complete the details needed for that workspace.</p></div><div className="mt-8 grid gap-3">{roles.map(r=>{const Icon=r.icon;const active=selected===r.value;return <button key={r.value} type="button" onClick={()=>setSelected(r.value)} className={`group flex min-h-28 items-start gap-4 rounded-2xl border p-5 text-left transition ${active?"border-[#2E9E4F] bg-[#EDF8EF]":"border-[#DCE6DC] bg-white hover:border-[#B8DCC0] hover:bg-[#FAFCFA]"}`}><span className={`grid size-12 shrink-0 place-items-center rounded-xl ${active?"bg-[#2E9E4F] text-white":"bg-[#EAF6ED] text-[#1E7A3D]"}`}><Icon size={23}/></span><span><span className="flex items-center gap-2 font-semibold">{r.label}{active&&<span className="rounded-full bg-[#EAF6ED] px-2 py-0.5 text-xs text-[#1E7A3D]">Selected</span>}</span><span className="mt-1 block text-sm leading-6 text-[#647064]">{r.description}</span></span></button>})}</div>{error&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<button disabled={!selected||saving} onClick={submit} className="group mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#2E9E4F] text-sm font-bold text-white disabled:opacity-40">{saving?"Saving…":"Continue"}<ArrowRight size={17}/></button><p className="mt-4 text-center text-xs text-[#7A857A]">Administrator access is assigned separately and cannot be self-selected.</p></div></main>}
