"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Building2, Leaf, ShoppingBasket } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Role="farmer"|"buyer"|"fpo";
const roles:{value:Role;label:string;description:string;icon:typeof Leaf}[]=[
 {value:"farmer",label:"Farmer",description:"Manage your farm, crops, health insights and selling opportunities.",icon:Leaf},
 {value:"buyer",label:"Buyer",description:"Source produce, manage requirements and connect with reliable supply.",icon:ShoppingBasket},
 {value:"fpo",label:"FPO / Aggregator",description:"Coordinate farmers, aggregate supply and manage collection and logistics.",icon:Building2},
];
export default function RoleSelectionPage(){const router=useRouter();const[selected,setSelected]=useState<Role|null>(null);const[error,setError]=useState("");const[saving,setSaving]=useState(false);async function submit(){if(!selected)return;setSaving(true);setError("");const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){router.replace("/signin");return}const{error}=await s.from("profiles").update({farm_role:selected}).eq("id",user.id);if(error){setError(error.message);setSaving(false);return}router.replace("/onboarding/complete-profile")}return <main className="min-h-screen bg-[#07130D] px-4 py-8 text-white sm:px-6"><div className="mx-auto max-w-2xl"><div className="flex items-center gap-2 text-sm font-bold"><span className="grid size-9 place-items-center rounded-xl bg-[#E3B341] text-[#07130D]"><Leaf size={19}/></span>FarmPlug AI</div><div className="mt-12"><p className="text-sm font-semibold text-[#7FD79B]">Set up your workspace</p><h1 className="mt-2 text-4xl font-semibold tracking-tight sm:text-5xl">How will you use FarmPlug?</h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/55">Choose the workspace that matches your work. You can then complete the details needed for that workspace.</p></div><div className="mt-8 grid gap-3">{roles.map(r=>{const Icon=r.icon;const active=selected===r.value;return <button key={r.value} type="button" onClick={()=>setSelected(r.value)} className={`group flex min-h-28 items-start gap-4 rounded-2xl border p-5 text-left transition ${active?"border-[#E3B341] bg-[#E3B341]/10":"border-white/10 bg-white/[0.04] hover:border-white/20 hover:bg-white/[0.07]"}`}><span className={`grid size-12 shrink-0 place-items-center rounded-xl ${active?"bg-[#E3B341] text-[#07130D]":"bg-[#7FD79B]/10 text-[#7FD79B]"}`}><Icon size={23}/></span><span><span className="flex items-center gap-2 font-semibold">{r.label}{active&&<span className="rounded-full bg-[#E3B341]/15 px-2 py-0.5 text-xs text-[#E3B341]">Selected</span>}</span><span className="mt-1 block text-sm leading-6 text-white/55">{r.description}</span></span></button>})}</div>{error&&<p className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200" role="alert">{error}</p>}<button disabled={!selected||saving} onClick={submit} className="group mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#E3B341] text-sm font-bold text-[#07130D] disabled:opacity-40">{saving?"Saving…":"Continue"}<ArrowRight size={17}/></button><p className="mt-4 text-center text-xs text-white/35">Administrator access is assigned separately and cannot be self-selected.</p></div></main>}
