'use client';
import { FormEvent,useState } from 'react';
import Link from 'next/link';
import { Loader2,UserPlus } from 'lucide-react';
import { supabase } from '../../lib/supabase';
export default function SignUpPage(){const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [role,setRole]=useState<'farmer'|'buyer'|'fpo'>('farmer');const [busy,setBusy]=useState(false);const [google,setGoogle]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setError('');setMessage('');if(!supabase){setError('Supabase authentication is not configured.');return}if(password.length<8){setError('Password must be at least 8 characters.');return}if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);const {data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim(),farm_role:role}}});if(error){setError(error.message);setBusy(false);return}if(data.session)location.href='/auth/callback';else{setMessage('Account created. Check your email if verification is enabled, then sign in.');setBusy(false)}}
 async function googleLogin(){setError('');if(!supabase){setError('Supabase authentication is not configured.');return}setGoogle(true);const inWebView=navigator.userAgent.includes('; wv');const redirectTo=inWebView?'farmplug://auth/callback':`${location.origin}/auth/callback`;const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error){setError(error.message);setGoogle(false)}}
 return <main className="pageShell"><div className="mobilePageHead"><span>ACCOUNT</span><b>FarmPlug AI</b><span>Sign up</span></div><section className="pageHero"><span className="eyebrow"><UserPlus size={14}/> CREATE ACCOUNT</span><h1>Start your FarmPlug workspace.</h1><p>Create a real account with email/password or continue securely with Google.</p></section><section className="pageCard"><form onSubmit={submit}><h2><UserPlus size={21}/> Create account</h2><div className="field"><label htmlFor="name">Name</label><input id="name" value={name} onChange={e=>setName(e.target.value)} required autoComplete="name"/></div><div className="field"><label htmlFor="email">Email</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></div><div className="field"><label htmlFor="role">Workspace</label><select id="role" value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="farmer">Farmer</option><option value="buyer">Buyer</option><option value="fpo">FPO / Aggregator</option></select></div><div className="field"><label htmlFor="password">Password</label><input id="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} autoComplete="new-password"/></div><div className="field"><label htmlFor="confirm">Confirm password</label><input id="confirm" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required autoComplete="new-password"/></div>{error&&<div role="alert" className="notice" style={{color:'#8b1e1e',background:'#fff1f1'}}>{error}</div>}{message&&<div role="status" className="notice">{message}</div>}<button className="btn primary full" disabled={busy||google}>{busy?<><Loader2 size={16}/> Creating…</>:<>Create Account <UserPlus size={16}/></>}</button></form><div style={{display:'flex',alignItems:'center',gap:10,margin:'18px 0',color:'#64756a'}}><span style={{height:1,background:'#e3ece5',flex:1}/> OR <span style={{height:1,background:'#e3ece5',flex:1}/></div><button className="btn secondary full" type="button" disabled={busy||google} onClick={googleLogin}>{google?<><Loader2 size={16}/> Connecting…</>:<>ⓖ Continue with Google</>}</button><p className="mutedText" style={{marginTop:15}}>By creating an account you agree to the FarmPlug AI Terms and Privacy Policy.</p><div style={{fontSize:13}}><Link href="/signin">Already have an account? Sign in</Link></div></section></main>}
