create extension if not exists pgcrypto;

alter table public.profiles add column if not exists farm_role text not null default 'farmer';
alter table public.profiles drop constraint if exists profiles_farm_role_check;
alter table public.profiles add constraint profiles_farm_role_check check (farm_role in ('farmer','fpo','buyer','admin'));

create table if not exists public.farmer_profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, phone text, location text, verification_status text not null default 'unverified' check (verification_status in ('unverified','pending','verified','rejected')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.fpo_profiles (id uuid primary key references auth.users(id) on delete cascade, organization_name text not null, location text, verification_status text not null default 'unverified' check (verification_status in ('unverified','pending','verified','rejected')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.buyer_profiles (id uuid primary key references auth.users(id) on delete cascade, business_name text not null, buyer_type text, location text, required_crops text[] not null default '{}', typical_quantity_kg numeric check (typical_quantity_kg is null or typical_quantity_kg > 0), quality_requirements text, delivery_locations text, verification_status text not null default 'unverified' check (verification_status in ('unverified','pending','verified','rejected')), reliability_score numeric check (reliability_score is null or reliability_score between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.farms (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null default 'My Farm', location text not null, area_acres numeric not null check (area_acres > 0), latitude double precision, longitude double precision, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.crops (id uuid primary key default gen_random_uuid(), farm_id uuid not null references public.farms(id) on delete cascade, crop_name text not null, variety text, area_acres numeric check (area_acres is null or area_acres > 0), harvest_date date, available_quantity_kg numeric check (available_quantity_kg is null or available_quantity_kg >= 0), quality_grade text, status text not null default 'growing' check (status in ('planned','growing','harvest_ready','harvested','sold')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.markets (id uuid primary key default gen_random_uuid(), name text not null, location text not null, state text, latitude double precision, longitude double precision, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.market_prices (id uuid primary key default gen_random_uuid(), market_id uuid not null references public.markets(id) on delete cascade, crop text not null, price_per_kg numeric not null check (price_per_kg >= 0), min_price numeric, max_price numeric, price_date date not null, source text not null, is_demo boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.market_arrivals (id uuid primary key default gen_random_uuid(), market_id uuid not null references public.markets(id) on delete cascade, crop text not null, arrival_kg numeric not null check (arrival_kg >= 0), arrival_date date not null, source text not null, is_demo boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.market_demand (id uuid primary key default gen_random_uuid(), market_id uuid references public.markets(id) on delete set null, crop text not null, demand_kg numeric not null check (demand_kg >= 0), demand_date date not null, source text not null, is_demo boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.price_forecasts (id uuid primary key default gen_random_uuid(), crop text not null, market_id uuid references public.markets(id) on delete set null, forecast_date date not null, horizon_days integer not null check (horizon_days > 0), predicted_price numeric not null check (predicted_price >= 0), lower_bound numeric, upper_bound numeric, confidence numeric check (confidence is null or confidence between 0 and 1), model_version text not null, dataset_version text not null, generated_at timestamptz not null default now(), is_prototype boolean not null default true);
create table if not exists public.demand_forecasts (id uuid primary key default gen_random_uuid(), crop text not null, market_id uuid references public.markets(id) on delete set null, forecast_date date not null, horizon_days integer not null check (horizon_days > 0), predicted_demand_kg numeric not null check (predicted_demand_kg >= 0), lower_bound numeric, upper_bound numeric, confidence numeric check (confidence is null or confidence between 0 and 1), model_version text not null, dataset_version text not null, generated_at timestamptz not null default now(), is_prototype boolean not null default true);
create table if not exists public.ai_predictions (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, prediction_type text not null, input_snapshot jsonb not null default '{}', prediction jsonb not null default '{}', model_version text not null, dataset_version text not null, horizon_days integer, confidence numeric, mae numeric, rmse numeric, mape numeric, created_at timestamptz not null default now());
create table if not exists public.ai_recommendations (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, crop_id uuid references public.crops(id) on delete set null, recommendation_type text not null, recommendation jsonb not null default '{}', reason text, confidence numeric, is_prototype boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.buyer_matches (id uuid primary key default gen_random_uuid(), supply_listing_id uuid not null references public.farmplug_supply_listings(id) on delete cascade, buyer_id uuid not null references auth.users(id) on delete cascade, crop_score numeric not null default 0 check (crop_score between 0 and 100), quantity_score numeric not null default 0 check (quantity_score between 0 and 100), quality_score numeric not null default 0 check (quality_score between 0 and 100), location_score numeric not null default 0 check (location_score between 0 and 100), delivery_score numeric not null default 0 check (delivery_score between 0 and 100), total_score numeric not null default 0 check (total_score between 0 and 100), explanation jsonb not null default '{}', created_at timestamptz not null default now(), unique(supply_listing_id,buyer_id));
create table if not exists public.supply_aggregations (id uuid primary key default gen_random_uuid(), requirement_id uuid not null references public.farmplug_buyer_requirements(id) on delete cascade, total_quantity_kg numeric not null default 0 check (total_quantity_kg >= 0), status text not null default 'forming' check (status in ('forming','ready','dispatched','completed','cancelled')), selected_listings jsonb not null default '[]', logistics_cost numeric, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.logistics_routes (id uuid primary key default gen_random_uuid(), order_id uuid references public.farmplug_orders(id) on delete set null, collection_hub text, buyer_location text not null, pickup_sequence jsonb not null default '[]', distance_km numeric, estimated_minutes integer, vehicle_capacity_kg numeric, estimated_cost numeric, status text not null default 'planned' check (status in ('planned','active','completed','cancelled')), routing_provider text, optimization_method text, is_prototype boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.delivery_events (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.farmplug_orders(id) on delete cascade, event_type text not null check (event_type in ('collecting','picked_up','in_transit','arrived','delivered','cancelled')), location text, notes text, occurred_at timestamptz not null default now());
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.farmplug_orders(id) on delete cascade, amount numeric not null check (amount >= 0), currency text not null default 'INR', status text not null default 'pending' check (status in ('pending','authorized','paid','released','refunded','failed')), provider text, provider_reference text, is_simulation boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.escrow_transactions (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.farmplug_orders(id) on delete cascade, amount numeric not null check (amount >= 0), status text not null default 'simulation_pending' check (status in ('simulation_pending','funded','held','released','refunded')), is_simulation boolean not null default true, created_at timestamptz not null default now(), released_at timestamptz);
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.disputes (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.farmplug_orders(id) on delete cascade, opened_by uuid not null references auth.users(id) on delete cascade, reason text not null, status text not null default 'open' check (status in ('open','investigating','resolved','rejected')), resolution text, created_at timestamptz not null default now(), resolved_at timestamptz);
create table if not exists public.audit_logs (id bigint generated always as identity primary key, actor_id uuid references auth.users(id) on delete set null, action text not null, entity_type text not null, entity_id text, metadata jsonb not null default '{}', created_at timestamptz not null default now());

create index if not exists farms_owner_id_idx on public.farms(owner_id);
create index if not exists crops_farm_id_idx on public.crops(farm_id);
create index if not exists market_prices_crop_date_idx on public.market_prices(crop,price_date desc);
create index if not exists market_demand_crop_date_idx on public.market_demand(crop,demand_date desc);
create index if not exists buyer_matches_listing_score_idx on public.buyer_matches(supply_listing_id,total_score desc);
create index if not exists notifications_user_idx on public.notifications(user_id,created_at desc);
create index if not exists audit_logs_actor_idx on public.audit_logs(actor_id,created_at desc);

alter table public.farmer_profiles enable row level security;
alter table public.fpo_profiles enable row level security;
alter table public.buyer_profiles enable row level security;
alter table public.farms enable row level security;
alter table public.crops enable row level security;
alter table public.markets enable row level security;
alter table public.market_prices enable row level security;
alter table public.market_arrivals enable row level security;
alter table public.market_demand enable row level security;
alter table public.price_forecasts enable row level security;
alter table public.demand_forecasts enable row level security;
alter table public.ai_predictions enable row level security;
alter table public.ai_recommendations enable row level security;
alter table public.buyer_matches enable row level security;
alter table public.supply_aggregations enable row level security;
alter table public.logistics_routes enable row level security;
alter table public.delivery_events enable row level security;
alter table public.payments enable row level security;
alter table public.escrow_transactions enable row level security;
alter table public.notifications enable row level security;
alter table public.disputes enable row level security;
alter table public.audit_logs enable row level security;

create policy farmer_profile_owner on public.farmer_profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy fpo_profile_owner on public.fpo_profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy buyer_profile_owner on public.buyer_profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy farms_owner on public.farms for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy crops_owner on public.crops for all using (exists(select 1 from public.farms f where f.id=crops.farm_id and f.owner_id=auth.uid())) with check (exists(select 1 from public.farms f where f.id=crops.farm_id and f.owner_id=auth.uid()));
create policy markets_read_authenticated on public.markets for select to authenticated using (active=true);
create policy market_prices_read_authenticated on public.market_prices for select to authenticated using (true);
create policy market_arrivals_read_authenticated on public.market_arrivals for select to authenticated using (true);
create policy market_demand_read_authenticated on public.market_demand for select to authenticated using (true);
create policy price_forecasts_read_authenticated on public.price_forecasts for select to authenticated using (true);
create policy demand_forecasts_read_authenticated on public.demand_forecasts for select to authenticated using (true);
create policy ai_predictions_owner on public.ai_predictions for select using (user_id=auth.uid());
create policy ai_recommendations_owner on public.ai_recommendations for select using (user_id=auth.uid());
create policy buyer_matches_participant on public.buyer_matches for select using (buyer_id=auth.uid() or exists(select 1 from public.farmplug_supply_listings s where s.id=buyer_matches.supply_listing_id and s.created_by=auth.uid()));
create policy supply_aggregations_authenticated_read on public.supply_aggregations for select to authenticated using (true);
create policy logistics_order_participant on public.logistics_routes for select using (exists(select 1 from public.farmplug_orders o where o.id=logistics_routes.order_id and (o.buyer_id=auth.uid() or o.farmer_id=auth.uid())));
create policy delivery_order_participant on public.delivery_events for select using (exists(select 1 from public.farmplug_orders o where o.id=delivery_events.order_id and (o.buyer_id=auth.uid() or o.farmer_id=auth.uid())));
create policy payments_order_participant on public.payments for select using (exists(select 1 from public.farmplug_orders o where o.id=payments.order_id and (o.buyer_id=auth.uid() or o.farmer_id=auth.uid())));
create policy escrow_order_participant on public.escrow_transactions for select using (exists(select 1 from public.farmplug_orders o where o.id=escrow_transactions.order_id and (o.buyer_id=auth.uid() or o.farmer_id=auth.uid())));
create policy notifications_owner on public.notifications for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy disputes_participant on public.disputes for select using (opened_by=auth.uid() or exists(select 1 from public.farmplug_orders o where o.id=disputes.order_id and (o.buyer_id=auth.uid() or o.farmer_id=auth.uid())));
create policy audit_owner_read on public.audit_logs for select using (actor_id=auth.uid());
