'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, BarChart3, CheckCircle2, Leaf, Plus, Route, Truck, Users, XCircle } from 'lucide-react';
import { supabase } from '../../lib/supabase';

type Listing={id:string;farmer_name:string;crop:string;quantity_kg:number;quality:string;location:string;available_until:string|null;status:string;created_at:string};
type Quote={id:string;status:string;message:string|null;created_at:string;buyer_name:string;buyer_email:string|null;supply:Listing|null;requirement:{id:string;buyer_name:string;crop:string;quantity_kg:number;quality:string;location:string;delivery_days:number;status:string}|null};
const kpis=['Buyer Match Rate','Order Fulfilment Rate','Supply Aggregation Volume','Selling-Window Utilization','Logistics Efficiency','Market Access'];

export default function Dashboard(){
 const [listings,setListings]=useState<Listing[]>([]),[quotes,setQuotes]=useState<Quote[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const [form,setForm]=useState({farmerName:'',crop:'Tomato',quantityKg:'1000',quality:'Grade A',location:'Coimbatore',availableUntil:''});
 async function authHeader(){if(!supabase)return null;const {data:{session}}=await supabase.auth.getSession();return session?{Authorization:`Bearer ${session.access_token}`} : null}
 async function load(){setLoading(true);setMessage('');const h=await authHeader();if(!h){setLoading(false);setMessage('Sign in to manage your farm supply and buyer requests.');return}try{const [lr,qr]=await Promise.all([fetch('/api/farmer/listings',{headers:h,cache:'no-store'}),fetch('/api/farmer/quotes',{headers:h,cache:'no-store'})]);const lj=await lr.json(),qj=await qr.json();if(!lr.ok||!qr.ok)setMessage(lj.error||qj.error||'Could not load dashboard data.');else{setListings(lj.listings||[]);setQuotes(qj.quotes||[])}}catch{setMessage('Could not load live dashboard data.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function addListing(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');const h=await authHeader();if(!h){setMessage('Sign in first to publish supply.');setSaving(false);return}const r=await fetch('/api/farmer/listings',{method:'POST',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)setMessage(j.error||'Could not publish listing.');else{setListings(x=>[j.listing,...x]);setMessage('Supply listing published to the marketplace.');setForm(x=>({...x,quantityKg:'1000',availableUntil:''}))}setSaving(false)}
 async function updateStatus(id:string,status:string){const h=await authHeader();if(!h)return;const r=await fetch('/api/farmer/listings',{method:'PATCH',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify({id,status})});const j=await r.json();if(!r.ok){setMessage(j.error||'Update failed.');return}setListings(x=>x.map(a=>a.id===id?{...a,status}:a));setMessage(`Listing marked ${status}.`)}
 async function updateQuote(id:string,status:'accepted'|'rejected'){const h=await authHeader();if(!h)return;const r=await fetch('/api/farmer/quotes',{method:'PATCH',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify({id,status})});const j=await r.json();if(!r.ok){setMessage(j.error||'Could not update buyer request.');return}setQuotes(x=>x.map(q=>q.id===id?{...q,status}:q));if(status==='accepted'&&j.request)setListings(x=>x.map(l=>l.id===quotes.find(q=>q.id===id)?.supply_listing_id?{...l,status:'reserved'}:l));setMessage(status==='accepted'?'Buyer request accepted and supply reserved.':'Buyer request rejected.');await load()}
 const total=listings.reduce((n,x)=>n+Number(x.quantity_kg),0),available=listings.filter(x=>x.status==='available').length,pending=quotes.filter(x=>x.status==='pending').length;
 return <main className="pageShell"><header className="mobilePageHead"><Link href="/" className="back"><ArrowLeft size={18}/></Link><div><b>FarmPlug AI</b><span>Farmer / FPO Dashboard</span></div><Leaf size={20}/></header>
 <section className="pageHero"><span className="eyebrow"><BarChart3 size={14}/> FARMER / FPO DASHBOARD</span><h1>Turn your harvest into a market-ready supply.</h1><p>Publish produce, track availability and respond to matched buyers from one place.</p></section>
 <section className="dashboardGrid"><div className="statCard"><Users size={20}/><small>ACTIVE LISTINGS</small><strong>{available}</strong><span>Live marketplace supply</span></div><div className="statCard"><Truck size={20}/><small>LISTED SUPPLY</small><strong>{total.toLocaleString()} kg</strong><span>From your account</span></div><div className="statCard"><Route size={20}/><small>BUYER REQUESTS</small><strong>{pending}</strong><span>Waiting for your response</span></div><div className="statCard"><BarChart3 size={20}/><small>BUYER SIGNAL</small><strong>{quotes.length?'Active':'—'}</strong><span>Live quote activity</span></div></section>
 <section className="pageCard"><h2><Plus size={19}/> Publish produce</h2><form className="listingForm" onSubmit={addListing}><label>Farmer / FPO name<input value={form.farmerName} onChange={e=>setForm({...form,farmerName:e.target.value})} placeholder="Your farm or FPO"/></label><label>Crop<select value={form.crop} onChange={e=>setForm({...form,crop:e.target.value})}><option>Tomato</option><option>Onion</option><option>Potato</option><option>Mango</option><option>Other</option></select></label><label>Quantity (kg)<input type="number" min="1" value={form.quantityKg} onChange={e=>setForm({...form,quantityKg:e.target.value})}/></label><label>Quality<select value={form.quality} onChange={e=>setForm({...form,quality:e.target.value})}><option>Grade A</option><option>Grade B</option><option>Mixed</option></select></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="District / market"/></label><label>Available until<input type="date" value={form.availableUntil} onChange={e=>setForm({...form,availableUntil:e.target.value})}/></label><button className="primaryButton" disabled={saving}>{saving?'Publishing…':'Publish supply'}</button></form>{message&&<div className="notice">{message}</div>}</section>
 <section className="pageCard"><div className="sectionHead"><h2>Incoming buyer requests</h2><span className="countBadge">{quotes.length} total</span></div>{loading?<p className="mutedText">Loading live buyer requests…</p>:quotes.length===0?<p className="mutedText">No buyer requests yet. Keep your available listings active to receive matches.</p>:<div className="quoteStack">{quotes.map(q=><article className="quoteCard" key={q.id}><div className="quoteTop"><div><b>{q.buyer_name}</b><span>{q.buyer_email||'Verified FarmPlug buyer'}</span></div><span className={`status ${q.status}`}>{q.status}</span></div><div className="quoteDetails"><b>{q.requirement?.crop||q.supply?.crop||'Produce'} · {Number(q.requirement?.quantity_kg||0).toLocaleString()} kg</b><span>Needs {q.requirement?.quality||'—'} · {q.requirement?.location||'—'} · Delivery {q.requirement?.delivery_days??'—'} days</span><small>Your supply: {Number(q.supply?.quantity_kg||0).toLocaleString()} kg · {q.supply?.quality||'—'} · {q.supply?.location||'—'}</small>{q.message&&<em>“{q.message}”</em>}</div>{q.status==='pending'&&<div className="quoteActions"><button className="accept" onClick={()=>updateQuote(q.id,'accepted')}><CheckCircle2 size={15}/> Accept & reserve</button><button className="reject" onClick={()=>updateQuote(q.id,'rejected')}><XCircle size={15}/> Reject</button></div>}</article>)}</div>}</section>
 <section className="pageCard"><h2>Your supply listings</h2>{loading?<p className="mutedText">Loading live listings…</p>:listings.length===0?<p className="mutedText">No listings yet. Publish your first harvest above.</p>:<div className="listingStack">{listings.map(x=><article className="listingCard" key={x.id}><div><b>{x.crop}</b><span>{x.quantity_kg} kg • {x.quality} • {x.location}</span><small>{x.available_until?`Available until ${x.available_until}`:'Availability date not set'}</small></div><div className="listingActions"><span className={`status ${x.status}`}>{x.status}</span>{x.status==='available'&&<button onClick={()=>updateStatus(x.id,'sold')}>Mark sold</button>}{x.status==='reserved'&&<button onClick={()=>updateStatus(x.id,'available')}>Release</button>}</div></article>)}</div>}</section>
 <section className="pageCard"><h2>Recommended collection plan</h2>{[['Collection sequence','Farmer → Hub → Warehouse → Buyer'],['Vehicle capacity','Aligned to listed quantity'],['Route status','Prototype recommendation']].map(x=><div className="marketRow" key={x[0]}><span className="mutedText">{x[0]}</span><b>{x[1]}</b></div>)}<div className="notice">Demo Route Optimization. No real-time GPS or live routing is claimed.</div></section>
 <section className="pageCard"><h2>Pilot KPIs</h2>{kpis.map(x=><div className="kpiRow" key={x}><b>{x}</b><span>To be measured and validated</span></div>)}</section>
 <style jsx>{`.sectionHead,.quoteTop,.quoteActions{display:flex;justify-content:space-between;align-items:center;gap:12px}.countBadge{font-size:11px;background:#eef7ef;padding:6px 9px;border-radius:999px;color:#42704b}.quoteStack{display:grid;gap:12px}.quoteCard{border:1px solid #dce8de;border-radius:14px;padding:15px;background:#fbfdfb}.quoteTop>div b,.quoteTop>div span,.quoteDetails b,.quoteDetails span,.quoteDetails small{display:block}.quoteTop>div span{font-size:11px;color:#708076;margin-top:3px}.quoteDetails{margin:12px 0}.quoteDetails b{font-size:14px}.quoteDetails span{font-size:12px;color:#5d7063;margin-top:5px}.quoteDetails small{font-size:11px;color:#75847a;margin-top:4px}.quoteDetails em{display:block;margin-top:8px;padding:8px;background:#f3f8f3;border-radius:8px;font-size:11px;color:#5b6e61}.quoteActions{justify-content:flex-start}.quoteActions button{border:0;border-radius:9px;padding:9px 11px;font-size:11px;font-weight:800;display:flex;align-items:center;gap:5px;cursor:pointer}.accept{background:#28733b;color:white}.reject{background:#fff0ef;color:#8a3d36}.status.pending{background:#fff2d8;color:#805c10}.status.accepted{background:#e4f5e6;color:#176329}.status.rejected{background:#fff0ef;color:#8a3d36}@media(max-width:700px){.quoteActions{flex-direction:column;align-items:stretch}.quoteActions button{justify-content:center}}`}</style>
 </main>
}
