'use client';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { BarChart3, CheckCircle2, Package, RefreshCw, ShieldCheck, Truck, Users } from 'lucide-react';
import { supabase } from '@/lib/supabase';
type Row=Record<string,any>;
const statuses=['PENDING','CONFIRMED','AGGREGATING','PICKUP','IN_TRANSIT','DELIVERED','COMPLETED','CANCELLED'];
export default function PortalsPage(){
 const [role,setRole]=useState(''),[tab,setTab]=useState('overview'),[requirements,setRequirements]=useState<Row[]>([]),[listings,setListings]=useState<Row[]>([]),[groups,setGroups]=useState<Row[]>([]),[orders,setOrders]=useState<Row[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);const {data:{session}}=await supabase!.auth.getSession();if(!session){setMessage('Please log in first.');setLoading(false);return}const r=await fetch('/api/portals/overview',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const j=await r.json();if(!r.ok)setMessage(j.error||'Unable to load portal.');else{setRole(j.role||'farmer');setRequirements(j.requirements||[]);setListings(j.listings||[]);setGroups(j.groups||[]);setOrders(j.orders||[])}setLoading(false)};
 useEffect(()=>{load();const c=supabase!.channel('farmplug-portals-live').on('postgres_changes',{event:'*',schema:'public',table:'farmplug_orders'},load).on('postgres_changes',{event:'*',schema:'public',table:'aggregation_groups'},load).on('postgres_changes',{event:'*',schema:'public',table:'farmplug_buyer_requirements'},load).on('postgres_changes',{event:'*',schema:'public',table:'farmplug_supply_listings'},load).subscribe();return()=>{supabase!.removeChannel(c)}},[]);
 const admin=['admin','super_admin'].includes(role),buyer=['buyer','buyer_admin'].includes(role),fpo=['fpo','aggregator'].includes(role);const title=admin?'Admin Dashboard':buyer?'Buyer Portal':fpo?'FPO / Aggregator Portal':'Shared Operations';const completed=useMemo(()=>orders.filter(o=>String(o.status).toUpperCase()==='COMPLETED').length,[orders]);
 return <main className="min-h-screen bg-white text-slate-900"><div className="mx-auto max-w-6xl px-4 py-6 sm:px-6"><header className="flex items-center justify-between gap-3 border-b pb-5"><div><p className="text-xs font-bold tracking-[.2em] text-green-700">FARMPLUG AI</p><h1 className="mt-1 text-2xl font-bold">{title}</h1><p className="text-sm text-slate-500">Shared visibility across Farmer, Buyer, FPO and Admin.</p></div><button onClick={load} className="rounded-xl border p-3" aria-label="Refresh"><RefreshCw size={18}/></button></header>
 <nav className="flex gap-2 overflow-x-auto py-4">{['overview','orders','aggregation','market'].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full px-4 py-2 text-sm font-semibold ${tab===x?'bg-green-700 text-white':'bg-slate-100'}`}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>{message&&<div className="mb-4 rounded-xl bg-amber-50 p-4 text-sm">{message}</div>}{loading?<div className="rounded-2xl bg-slate-50 p-8 text-center">Loading shared data…</div>:<><section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat icon={<Package/>} label="Listings" value={listings.length}/><Stat icon={<Users/>} label="Aggregations" value={groups.length}/><Stat icon={<Truck/>} label="Orders" value={orders.length}/><Stat icon={<CheckCircle2/>} label="Completed" value={completed}/></section>
 {tab==='overview'&&<div className="mt-5 grid gap-4 md:grid-cols-2"><Panel title="Order pipeline">{statuses.map(s=><div className="flex justify-between border-b py-2 text-sm" key={s}><span>{s.replace('_',' ')}</span><b>{orders.filter(o=>String(o.status).toUpperCase()===s).length}</b></div>)}</Panel><Panel title="Aggregation readiness">{groups.slice(0,8).map(g=><div className="border-b py-3" key={g.id}><div className="flex justify-between"><b>{g.crop||'Produce aggregation'}</b><span className="text-xs font-bold">{g.status}</span></div><p className="text-sm text-slate-500">{g.current_quantity_kg||0} / {g.target_quantity_kg||0} kg</p></div>)}{!groups.length&&<Empty/>}</Panel></div>}
 {tab==='orders'&&<Panel title="Shared order tracking">{orders.map(o=><div key={o.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3"><div><b>Order {String(o.id).slice(0,8)}</b><p className="text-xs text-slate-500">{o.crop||o.product||'Produce'} • {o.quantity_kg||o.quantity||'-'} kg</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{o.status}</span></div>)}{!orders.length&&<Empty/>}</Panel>}
 {tab==='aggregation'&&<Panel title="Supply aggregation">{groups.map(g=><div key={g.id} className="border-b py-4"><div className="flex justify-between"><b>{g.crop||'Aggregation group'}</b><span className="text-xs font-bold">{g.status}</span></div><div className="mt-2 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-green-600" style={{width:`${Math.min(100,(Number(g.current_quantity_kg||0)/Math.max(1,Number(g.target_quantity_kg||1)))*100)}%`}}/></div><p className="mt-1 text-xs text-slate-500">{g.current_quantity_kg||0} / {g.target_quantity_kg||0} kg</p></div>)}{!groups.length&&<Empty/>}</Panel>}
 {tab==='market'&&<Panel title={buyer?'Buyer requirements':'Market requirements'}>{requirements.map(r=><div key={r.id} className="border-b py-3"><b>{r.crop||r.product||'Produce'}</b><p className="text-sm text-slate-500">Need {r.quantity_kg||r.quantity||'-'} kg • {r.quality||r.quality_grade||'Quality flexible'} • {r.location||'Location not set'}</p></div>)}{!requirements.length&&<Empty/>}</Panel>}</>}</div><footer className="mx-auto max-w-6xl px-4 pb-6 text-xs text-slate-500"><ShieldCheck size={15} className="mr-1 inline"/>Shared data uses Supabase. Realtime must be enabled for the subscribed tables.</footer></main>}
function Stat({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <div className="rounded-2xl border p-4"><div className="text-green-700">{icon}</div><p className="mt-2 text-xs text-slate-500">{label}</p><strong className="text-2xl">{value}</strong></div>}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="rounded-2xl border p-5"><div className="mb-2 flex items-center gap-2"><BarChart3 size={18}/><h2 className="font-bold">{title}</h2></div>{children}</section>}
function Empty(){return <p className="py-8 text-center text-sm text-slate-500">No records yet.</p>}
