'use client';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { BarChart3, CheckCircle2, Package, RefreshCw, ShieldCheck, Truck, Users, PlayCircle, XCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase';
type Row=Record<string,any>;
const statuses=['PENDING','CONFIRMED','AGGREGATING','PICKUP','IN_TRANSIT','DELIVERED','COMPLETED','CANCELLED'];
const nextFor=(s:string)=>({PENDING:'CONFIRMED',CONFIRMED:'AGGREGATING',AGGREGATING:'PICKUP',PICKUP:'IN_TRANSIT',IN_TRANSIT:'DELIVERED',DELIVERED:'COMPLETED'} as Record<string,string>)[s];
export default function PortalsPage(){
 const [role,setRole]=useState(''),[tab,setTab]=useState('overview'),[requirements,setRequirements]=useState<Row[]>([]),[listings,setListings]=useState<Row[]>([]),[groups,setGroups]=useState<Row[]>([]),[orders,setOrders]=useState<Row[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);setMessage('');const {data:{session}}=await supabase!.auth.getSession();if(!session){setMessage('Please log in first.');setLoading(false);return}const r=await fetch('/api/portals/overview',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const j=await r.json();if(!r.ok)setMessage(j.error||'Unable to load portal.');else{setRole(j.role||'farmer');setRequirements(j.requirements||[]);setListings(j.listings||[]);setGroups(j.groups||[]);setOrders(j.orders||[])}setLoading(false)};
 const action=async(body:Row)=>{const {data:{session}}=await supabase!.auth.getSession();if(!session)return;setMessage('Saving…');const r=await fetch('/api/portals/actions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(body)});const j=await r.json();setMessage(r.ok?'Saved successfully.':j.error||'Action failed.');if(r.ok)load()};
 useEffect(()=>{load();const c=supabase!.channel('farmplug-portals-live').on('postgres_changes',{event:'*',schema:'public',table:'farmplug_orders'},load).on('postgres_changes',{event:'*',schema:'public',table:'supply_aggregations'},load).on('postgres_changes',{event:'*',schema:'public',table:'farmplug_buyer_requirements'},load).subscribe();return()=>{supabase!.removeChannel(c)}},[]);
 const admin=['admin','super_admin'].includes(role),buyer=['buyer','buyer_admin'].includes(role),fpo=['fpo','aggregator'].includes(role);const title=admin?'Admin Dashboard':buyer?'Buyer Portal':fpo?'FPO / Aggregator Portal':'Shared Operations';const completed=useMemo(()=>orders.filter(o=>String(o.status).toUpperCase()==='COMPLETED').length,[orders]);
 return <main className="min-h-screen bg-white text-slate-900"><div className="mx-auto max-w-6xl px-4 py-6 sm:px-6"><header className="flex items-center justify-between gap-3 border-b pb-5"><div><p className="text-xs font-bold tracking-[.2em] text-green-700">FARMPLUG AI</p><h1 className="mt-1 text-2xl font-bold">{title}</h1><p className="text-sm text-slate-500">Role-aware operations and shared live visibility.</p></div><button onClick={load} className="rounded-xl border p-3" aria-label="Refresh"><RefreshCw size={18}/></button></header>
 <nav className="flex gap-2 overflow-x-auto py-4">{['overview','orders','aggregation','market'].map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full px-4 py-2 text-sm font-semibold ${tab===x?'bg-green-700 text-white':'bg-slate-100'}`}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>{message&&<div className="mb-4 rounded-xl bg-amber-50 p-4 text-sm">{message}</div>}{loading?<div className="rounded-2xl bg-slate-50 p-8 text-center">Loading shared data…</div>:<><section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat icon={<Package/>} label="Listings" value={listings.length}/><Stat icon={<Users/>} label="Aggregations" value={groups.length}/><Stat icon={<Truck/>} label="Orders" value={orders.length}/><Stat icon={<CheckCircle2/>} label="Completed" value={completed}/></section>
 {tab==='overview'&&<div className="mt-5 grid gap-4 md:grid-cols-2"><Panel title="Order pipeline">{statuses.map(s=><div className="flex justify-between border-b py-2 text-sm" key={s}><span>{s.replace('_',' ')}</span><b>{orders.filter(o=>String(o.status).toUpperCase()===s).length}</b></div>)}</Panel><Panel title={admin?'Admin controls':buyer?'Buyer controls':fpo?'FPO controls':'Operations'}>{buyer&&requirements.map(r=><div key={r.id} className="flex items-center justify-between gap-3 border-b py-3"><div><b>{r.crop}</b><p className="text-xs text-slate-500">{r.quantity_kg} kg • {r.status}</p></div><button onClick={()=>action({action:'update_requirement',id:r.id,status:String(r.status).toUpperCase()==='OPEN'?'PAUSED':'OPEN'})} className="rounded-lg border px-3 py-2 text-xs font-bold">{String(r.status).toUpperCase()==='OPEN'?'Pause':'Reopen'}</button></div>)}{(fpo||admin)&&requirements.slice(0,8).map(r=><div key={r.id} className="flex items-center justify-between gap-3 border-b py-3"><div><b>{r.crop}</b><p className="text-xs text-slate-500">Target {r.quantity_kg} kg • {r.status}</p></div><button onClick={()=>action({action:'create_aggregation',requirement_id:r.id})} className="rounded-lg bg-green-700 px-3 py-2 text-xs font-bold text-white">Create aggregation</button></div>)}{admin&&<p className="pt-3 text-xs text-slate-500">Admin can manage requirement and order lifecycle controls. Sensitive role changes remain protected by Supabase RLS.</p>}{!buyer&&!fpo&&!admin&&<p className="py-5 text-sm text-slate-500">Use the Farmer App for farmer-specific actions.</p>}</Panel></div>}
 {tab==='orders'&&<Panel title="Order management">{orders.map(o=>{const s=String(o.status).toUpperCase(),n=nextFor(s);return <div key={o.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3"><div><b>Order {String(o.id).slice(0,8)}</b><p className="text-xs text-slate-500">{o.quantity_kg||'-'} kg • {s}</p></div><div className="flex gap-2">{n&&(admin||buyer||fpo)&&<button onClick={()=>action({action:'update_order',id:o.id,status:n})} className="flex items-center gap-1 rounded-lg bg-green-700 px-3 py-2 text-xs font-bold text-white"><PlayCircle size={14}/>{n.replace('_',' ')}</button>}{s!=='COMPLETED'&&s!=='CANCELLED'&&(admin||buyer)&&<button onClick={()=>action({action:'update_order',id:o.id,status:'CANCELLED'})} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold"><XCircle size={14}/>Cancel</button>}</div></div>})}{!orders.length&&<Empty/>}</Panel>}
 {tab==='aggregation'&&<Panel title="Supply aggregation">{requirements.map(r=><div key={r.id} className="mb-3 flex items-center justify-between rounded-xl border p-4"><div><b>{r.crop}</b><p className="text-xs text-slate-500">Buyer target: {r.quantity_kg} kg</p></div>{(fpo||admin)&&<button onClick={()=>action({action:'create_aggregation',requirement_id:r.id})} className="rounded-lg bg-green-700 px-3 py-2 text-xs font-bold text-white">Create group</button>}</div>)}{!requirements.length&&<Empty/>}{groups.length>0&&<div className="mt-4">{groups.map(g=><div key={g.id} className="flex items-center justify-between border-t py-3"><div><b>Group {String(g.id).slice(0,8)}</b><p className="text-xs text-slate-500">{g.total_quantity_kg||0} kg • {g.status}</p></div>{(fpo||admin)&&g.status!=='completed'&&<button onClick={()=>action({action:'update_aggregation',id:g.id,status:g.status==='forming'?'ready':'completed'})} className="rounded-lg border px-3 py-2 text-xs font-bold">{g.status==='forming'?'Mark ready':'Complete'}</button>}</div>)}</div>}</Panel>}
 {tab==='market'&&<Panel title={buyer?'Buyer requirements':'Market requirements'}>{requirements.map(r=><div key={r.id} className="border-b py-3"><div className="flex items-center justify-between"><b>{r.crop||'Produce'}</b><span className="text-xs font-bold">{r.status}</span></div><p className="text-sm text-slate-500">Need {r.quantity_kg||'-'} kg • {r.quality||'Quality flexible'} • {r.location||'Location not set'}</p></div>)}{!requirements.length&&<Empty/>}</Panel>}</>}</div><footer className="mx-auto max-w-6xl px-4 pb-6 text-xs text-slate-500"><ShieldCheck size={15} className="mr-1 inline"/>Actions are server-authorized and use the authenticated Supabase account.</footer></main>}
function Stat({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <div className="rounded-2xl border p-4"><div className="text-green-700">{icon}</div><p className="mt-2 text-xs text-slate-500">{label}</p><strong className="text-2xl">{value}</strong></div>}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="rounded-2xl border p-5"><div className="mb-2 flex items-center gap-2"><BarChart3 size={18}/><h2 className="font-bold">{title}</h2></div>{children}</section>}
function Empty(){return <p className="py-8 text-center text-sm text-slate-500">No records yet.</p>}
